### ISSUE TITLE
fdr 0x unknown packet error

### ISSUE THREAD

**Issue by Ryan222222** [LukeZGD/iOS-OTA-Downgrader#100]
it shows like a milion of these errors then exits with segementation fault. i am on iphone 5s 12.5.4 trying to get to 10.3.3 and using Linux mint 20.1 on live usb

**Comment by LukeZGD** [comment]
Please give full terminal log/output

**Comment by Ryan222222** [comment]
I got it working by downgrading to iOS 12.5.3 before restore thank you!

**Comment by Ryan222222** [comment]
Fixed it by downgrading to 12.5.3 before restore.
