### ISSUE TITLE
Support for Mac on M1 chip

### ISSUE THREAD

**Issue by isofttouch** [LukeZGD/iOS-OTA-Downgrader#104]
Got the error as indicated on the screenshot for the new Mac M1 chip. 

<img width="571" alt="Screenshot 2021-07-09 at 22 47 06" src="https://user-images.githubusercontent.com/66465052/125139210-0aac8b00-e108-11eb-8daa-6875e6736702.png">

**Comment by LukeZGD** [comment]
m1 is already supported, try removing spaces from path/folder name

**Comment by isofttouch** [comment]
Thanks.
