### ISSUE TITLE
iPhone4,1_6.1.3_10B329_CustomW/048-2613-005.dmg:  write error

### ISSUE THREAD

**Issue by hyperpixel34** [LukeZGD/iOS-OTA-Downgrader#105]
I'm having trouble downgrading my iPhone 4s to iOS 6.1.3. It gives me a write error. Here's my whole command line output:

`
******* iOS-OTA-Downgrader ******* 
   Downgrader script by LukeZGD    

[Log] Running on platform: linux (Ubuntu 20.04.2 LTS) 
[Log] Finding device in Normal mode... 
[Log] Found iPhone4,1 in Normal mode. 
*** Main Menu *** 
[Input] Select an option: 
1) Downgrade device		 4) (Re-)Install Dependencies
2) Save OTA blobs		 5) (Any other key to exit)
3) Just put device in kDFU mode
#? 1
[Input] Select iOS version: 
1) iOS 8.4.1		    3) Other (use SHSH blobs)
2) iOS 6.1.3		    4) (Any other key to exit)
#? 2
[Log] Option: Downgrade 
[Input] Jailbreak the selected iOS version? (Y/n): n
[Log] Saving 6.1.3 blobs with tsschecker... 
Version: 7895a76c8ac57e45b87bb756e6d8a617740aab62 - 317
libfragmentzip version: 0.60-120447d0f410dffb49948fa155467fc5d91ca3c8
[TSSC] manually specified ECID to use, parsed "2524870438347" to dec:2524870438347 hex:24bde016dcb
[TSSC] opening resources/manifests/BuildManifest_iPhone4,1_6.1.3.plist
[TSSR] Checking BuildIdentity 0
[WARNING] [TSSC] could not get BuildIdentity for installType=Erase. Using fallback installType=Update since user did not specify installType manually
[TSSR] Checking BuildIdentity 0
[TSSR] Selected BuildIdentity for request
[TSSR] Request URL set to https://gs.apple.com/TSS/controller?action=2
[TSSR] Sending TSS request attempt 1... success
[TSSR] Checking BuildIdentity 0
[Error] [TSSR] Error: could not get BuildIdentity for installType=Erase
Saved shsh blobs!

iOS 6.1.3 for device iPhone4,1 IS being signed!
[Log] Successfully saved 6.1.3 blobs. 
* Select 1 (futurerestore) if unsure 
* Select 2 (idevicerestore) if you experience issues with futurerestore 
[Input] Select restore tool to use: 
1) futurerestore
2) idevicerestore
#? 2
[Log] Found existing Custom IPSW. Skipping verification. 
[Log] Setting restore IPSW to: iPhone4,1_6.1.3_10B329_CustomW.ipsw 
[Log] Patching iBSS... 
[Log] Copying stuff to device via SSH... 
* Make sure OpenSSH/Dropbear is installed on the device and running! 
* Dropbear is only needed for devices on iOS 10 
* To make sure that SSH is successful, try these steps: 
* Reinstall OpenSSH/Dropbear, reboot and rejailbreak, then reinstall them again 

[Input] Enter the root password of your iOS device when prompted 
* The default password is "alpine" 
Creating listening port 2222 for device port 22
waiting for connection
New connection for 2222->22, fd = 5
waiting for connection
Requesting connecion to USB device handle 1 (serial: d22ade3a02fd7467b52c577078ee35350825210c), port 22
Warning: Permanently added '[127.0.0.1]:2222' (RSA) to the list of known hosts.
root@127.0.0.1's password: 
kloader                                       100%   51KB 715.2KB/s   00:00    
pwnediBSS                                     100%   76KB 872.2KB/s   00:00    
[Log] Entering kDFU mode... 
* Press POWER or HOME button when screen goes black on the device 
[Log] Finding device in DFU mode... 
New connection for 2222->22, fd = 5
waiting for connection
Requesting connecion to USB device handle 1 (serial: d22ade3a02fd7467b52c577078ee35350825210c), port 22
root@127.0.0.1's password: 
Connection to 127.0.0.1 closed by remote host.
[Log] Found device in DFU mode. 
[Log] Found existing Custom IPSW. Skipping IPSW creation. 
[Log] Extracting IPSW: iPhone4,1_6.1.3_10B329_CustomW.ipsw 
iPhone4,1_6.1.3_10B329_CustomW/048-2613-005.dmg:  write error (disk full?).  Continue? (y/n/^C) 
`

**Comment by LukeZGD** [comment]
Your disk seems to be full, check your storage

If you are doing this in a live USB, check if your working directory is full, also try putting things in an external drive to have enough space

**Comment by Grandboy46** [comment]
as @LukeZGD said, your storage is full. Another possible reason this may be the custom ipsw may be corrupted. Remove the custom ipsw from iOS oat downgraded directory and rerun the script.

**Comment by hyperpixel34** [comment]
Yes, I'm on a live usb. I'll try it again after clearing my storage.

**Comment by hyperpixel34** [comment]
I cleaned up my storage, but now i'm getting another error:

```
run 4874: sectors=512, left=4584
run 4875: sectors=512, left=4072
run 4876: sectors=512, left=3560
run 4877: sectors=512, left=3048
run 4878: sectors=512, left=2536
run 4879: sectors=512, left=2024
run 4880: sectors=512, left=1512
run 4881: sectors=512, left=1000
run 4882: sectors=488, left=488
Inserting main blkx...
Inserting cSum data...
Inserting nsiz data
Writing free partition...
Writing XML data...
making size data
we know to flip this size resource
Generating UDIF metadata...
Master checksum: 6dae868b
Writing out UDIF resource file...
Cleaning up...
Done.
packing: 048-2516-005.dmg (9955508)
packing: 048-2613-005.dmg (923818290)
packing: 048-2679-005.dmg (9951588)
packing: BuildManifest.plist (21092)
packing: Downgrade/ (0)
packing: Downgrade/DeviceTree.n94ap.img3 (80872)
packing: Downgrade/applelogo@2x.s5l8940x.img3 (15008)
packing: Downgrade/kernelcache.release.n94 (7753844)
packing: Firmware/ (0)
packing: Firmware/Trek-3.4.03.Release.bbfw (11256863)
packing: Firmware/Trek-3.4.03.Release.plist (732)
packing: Firmware/all_flash/ (0)
packing: Firmware/all_flash/all_flash.n94ap.production/ (0)
packing: Firmware/all_flash/all_flash.n94ap.production/DeviceTree.n94ap.img3 (81060)
packing: Firmware/all_flash/all_flash.n94ap.production/LLB.n94ap.RELEASE.img3 (149988)
packing: Firmware/all_flash/all_flash.n94ap.production/applelogo@2x.s5l8940x.img3 (15204)
packing: Firmware/all_flash/all_flash.n94ap.production/batterycharging0@2x.s5l8940x.img3 (11876)
packing: Firmware/all_flash/all_flash.n94ap.production/batterycharging1@2x.s5l8940x.img3 (37156)
packing: Firmware/all_flash/all_flash.n94ap.production/batteryfull@2x.s5l8940x.img3 (654308)
packing: Firmware/all_flash/all_flash.n94ap.production/batterylow0@2x.s5l8940x.img3 (170724)
packing: Firmware/all_flash/all_flash.n94ap.production/batterylow1@2x.s5l8940x.img3 (39844)
packing: Firmware/all_flash/all_flash.n94ap.production/glyphcharging@2x.s5l8940x.img3 (7396)
packing: Firmware/all_flash/all_flash.n94ap.production/glyphplugin@2x.s5l8940x.img3 (7076)
packing: Firmware/all_flash/all_flash.n94ap.production/iBoot.n94ap.RELEASE.img3 (276964)
packing: Firmware/all_flash/all_flash.n94ap.production/manifest (349)
packing: Firmware/all_flash/all_flash.n94ap.production/recoverymode@2x~iphone.s5l8940x.img3 (126564)
packing: Firmware/dfu/ (0)
packing: Firmware/dfu/iBEC.n94ap.RELEASE.dfu (276760)
packing: Firmware/dfu/iBSS.n94ap.RELEASE.dfu (76056)
packing: Firmware/usr/ (0)
packing: Firmware/usr/local/ (0)
packing: Firmware/usr/local/standalone/ (0)
packing: Restore.plist (2100)
packing: kernelcache.release.n94 (7754020)
[Log] Setting restore IPSW to: iPhone4,1_6.1.3_10B329_CustomW.ipsw 
[Log] Extracting IPSW: iPhone4,1_6.1.3_10B329_CustomW.ipsw 
[Log] Proceeding to idevicerestore... (Enter root password of your PC/Mac when prompted) 
Found device in DFU mode
Identified device as n94ap, iPhone4,1
Extracting BuildManifest from IPSW
Product Version: 6.1.3
Product Build: 10B329 Major: 10
Device supports Image4: false
Variant: Customer Erase Install (IPSW)
This restore will erase your device data.
Checking IPSW for required components...
All required components found in IPSW
Using cached filesystem from 'iPhone4,1_6.1.3_10B329_CustomW/048-2613-005.dmg'
Found ECID 2524870438347
Getting ApNonce in DFU mode... 47 11 ae af 3e 14 ea b2 56 9d 9c e1 e6 43 ea 00 75 e3 43 6e 
checking for local signing tickets
Using cached signing tickets
Extracting iBSS.n94ap.RELEASE.dfu...
Personalizing IMG3 component iBSS...
reconstructed size: 76110
Sending iBSS (76110 bytes)...
[==================================================] 100.0%
Nonce: 47 11 ae af 3e 14 ea b2 56 9d 9c e1 e6 43 ea 00 75 e3 43 6e 
Extracting iBEC.n94ap.RELEASE.dfu...
Not personalizing component iBEC...
Sending iBEC (276760 bytes)...
[==================================================] 100.0%
Getting ApNonce in recovery mode... 47 11 ae af 3e 14 ea b2 56 9d 9c e1 e6 43 ea 00 75 e3 43 6e 
ERROR: could not retrieve device serial number. Can't continue.

[Log] Restoring done! 
[Log] Downgrade script done! 
```

These are only the last few lines.

**Comment by LukeZGD** [comment]
>could not retrieve device serial number

That's a pretty weird issue that I have never seen before.. I tried looking it up and was unable to find any solutions for it. All I can suggest is to try again, try changing ports/cables, and/or check if it restores with iTunes successfully if needed

**Comment by hyperpixel34** [comment]
When I try downgrading with iTunes the progress bar on the iPhone always shows 0% and doesn't change.

**Comment by LukeZGD** [comment]
Not much else I can do to help here since it's not really a problem with the script. Try out the suggestions and see how it goes, closing.

**Comment by Grandboy46** [comment]
> I cleaned up my storage, but now i'm getting another error:
> 
> ```
> run 4874: sectors=512, left=4584
> run 4875: sectors=512, left=4072
> run 4876: sectors=512, left=3560
> run 4877: sectors=512, left=3048
> run 4878: sectors=512, left=2536
> run 4879: sectors=512, left=2024
> run 4880: sectors=512, left=1512
> run 4881: sectors=512, left=1000
> run 4882: sectors=488, left=488
> Inserting main blkx...
> Inserting cSum data...
> Inserting nsiz data
> Writing free partition...
> Writing XML data...
> making size data
> we know to flip this size resource
> Generating UDIF metadata...
> Master checksum: 6dae868b
> Writing out UDIF resource file...
> Cleaning up...
> Done.
> packing: 048-2516-005.dmg (9955508)
> packing: 048-2613-005.dmg (923818290)
> packing: 048-2679-005.dmg (9951588)
> packing: BuildManifest.plist (21092)
> packing: Downgrade/ (0)
> packing: Downgrade/DeviceTree.n94ap.img3 (80872)
> packing: Downgrade/applelogo@2x.s5l8940x.img3 (15008)
> packing: Downgrade/kernelcache.release.n94 (7753844)
> packing: Firmware/ (0)
> packing: Firmware/Trek-3.4.03.Release.bbfw (11256863)
> packing: Firmware/Trek-3.4.03.Release.plist (732)
> packing: Firmware/all_flash/ (0)
> packing: Firmware/all_flash/all_flash.n94ap.production/ (0)
> packing: Firmware/all_flash/all_flash.n94ap.production/DeviceTree.n94ap.img3 (81060)
> packing: Firmware/all_flash/all_flash.n94ap.production/LLB.n94ap.RELEASE.img3 (149988)
> packing: Firmware/all_flash/all_flash.n94ap.production/applelogo@2x.s5l8940x.img3 (15204)
> packing: Firmware/all_flash/all_flash.n94ap.production/batterycharging0@2x.s5l8940x.img3 (11876)
> packing: Firmware/all_flash/all_flash.n94ap.production/batterycharging1@2x.s5l8940x.img3 (37156)
> packing: Firmware/all_flash/all_flash.n94ap.production/batteryfull@2x.s5l8940x.img3 (654308)
> packing: Firmware/all_flash/all_flash.n94ap.production/batterylow0@2x.s5l8940x.img3 (170724)
> packing: Firmware/all_flash/all_flash.n94ap.production/batterylow1@2x.s5l8940x.img3 (39844)
> packing: Firmware/all_flash/all_flash.n94ap.production/glyphcharging@2x.s5l8940x.img3 (7396)
> packing: Firmware/all_flash/all_flash.n94ap.production/glyphplugin@2x.s5l8940x.img3 (7076)
> packing: Firmware/all_flash/all_flash.n94ap.production/iBoot.n94ap.RELEASE.img3 (276964)
> packing: Firmware/all_flash/all_flash.n94ap.production/manifest (349)
> packing: Firmware/all_flash/all_flash.n94ap.production/recoverymode@2x~iphone.s5l8940x.img3 (126564)
> packing: Firmware/dfu/ (0)
> packing: Firmware/dfu/iBEC.n94ap.RELEASE.dfu (276760)
> packing: Firmware/dfu/iBSS.n94ap.RELEASE.dfu (76056)
> packing: Firmware/usr/ (0)
> packing: Firmware/usr/local/ (0)
> packing: Firmware/usr/local/standalone/ (0)
> packing: Restore.plist (2100)
> packing: kernelcache.release.n94 (7754020)
> [Log] Setting restore IPSW to: iPhone4,1_6.1.3_10B329_CustomW.ipsw 
> [Log] Extracting IPSW: iPhone4,1_6.1.3_10B329_CustomW.ipsw 
> [Log] Proceeding to idevicerestore... (Enter root password of your PC/Mac when prompted) 
> Found device in DFU mode
> Identified device as n94ap, iPhone4,1
> Extracting BuildManifest from IPSW
> Product Version: 6.1.3
> Product Build: 10B329 Major: 10
> Device supports Image4: false
> Variant: Customer Erase Install (IPSW)
> This restore will erase your device data.
> Checking IPSW for required components...
> All required components found in IPSW
> Using cached filesystem from 'iPhone4,1_6.1.3_10B329_CustomW/048-2613-005.dmg'
> Found ECID 2524870438347
> Getting ApNonce in DFU mode... 47 11 ae af 3e 14 ea b2 56 9d 9c e1 e6 43 ea 00 75 e3 43 6e 
> checking for local signing tickets
> Using cached signing tickets
> Extracting iBSS.n94ap.RELEASE.dfu...
> Personalizing IMG3 component iBSS...
> reconstructed size: 76110
> Sending iBSS (76110 bytes)...
> [==================================================] 100.0%
> Nonce: 47 11 ae af 3e 14 ea b2 56 9d 9c e1 e6 43 ea 00 75 e3 43 6e 
> Extracting iBEC.n94ap.RELEASE.dfu...
> Not personalizing component iBEC...
> Sending iBEC (276760 bytes)...
> [==================================================] 100.0%
> Getting ApNonce in recovery mode... 47 11 ae af 3e 14 ea b2 56 9d 9c e1 e6 43 ea 00 75 e3 43 6e 
> ERROR: could not retrieve device serial number. Can't continue.
> 
> [Log] Restoring done! 
> [Log] Downgrade script done! 
> ```
> 
> These are only the last few lines.

This issue occurs on very late 8gb models of iPhone 4s and because those 4s models is not compatible with iOS 6. There is nothing to do for this issue. You can downgrade back to iOS 8.4.1 without any issues.
