### ISSUE TITLE
Script device.sh broken [fix]

### ISSUE THREAD

**Issue by dieguitus** [LukeZGD/iOS-OTA-Downgrader#108]
kDFU will fail unless you leave **resources/ipwndfu** before executing. Update lines 166-181 with:

    Log "Entering pwnDFU mode with $pwnDFUTool..."
    if [[ $pwnDFUTool == "ipwndfu" ]]; then
        cd resources/ipwndfu
        $ipwndfu -p
        if  [[ $DeviceProc == 7 ]]; then
            Log "Running rmsigchks.py..."
            $rmsigchks
            pwnDFUDevice=$?
            cd ../..
        else
            cd ../..
            Log "Sending iBSS..."
            kDFU iBSS || echo
            pwnDFUDevice=$?
        fi
    elif [[ $pwnDFUTool == "iPwnder32" ]]; then
        $ipwnder32 -p
    fi

**Comment by LukeZGD** [comment]
Thanks for this, I will be pushing this fix now
