### ISSUE TITLE
[Error] Verifying IPSW failed. Your IPSW may be corrupted or incomplete

### ISSUE THREAD

**Issue by brucelee2022** [LukeZGD/iOS-OTA-Downgrader#115]
[Input] Select an option: 
1) Downgrade device	      3) (Any other key to exit)
2) (Re-)Install Dependencies
#? 1
[Log] Option: Downgrade 
[Log] iOS 10.3.3 IPSW cannot be found. 
* If you already downloaded the IPSW, did you put it in the same directory as the script? 
* Do NOT rename the IPSW as the script will fail to detect it 
[Log] Downloading IPSW... (Press Ctrl+C to cancel) 
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 2330M  100 2330M    0     0  1499k      0  0:26:30  0:26:30 --:--:-- 1717k
[Log] Verifying IPSW... 

[Error] Verifying IPSW failed. Your IPSW may be corrupted or incomplete. 
* Delete/replace the IPSW and run the script again

**Comment by LukeZGD** [comment]
The script already tells you what to do

If it fails multiple times, there might be something wrong with your Internet connection

**Comment by LukeZGD** [comment]
I have added output log SHA1sum on verifying IPSW on the latest commit b6252ba

You may try again with the latest and check the output

The expected and the actual output SHA1sum should be the same for it to proceed

If the expected and the actual output are the same and it shows an error, let me know

**Comment by brucelee2022** [comment]
[Log] Option: Downgrade 
[Log] Verifying IPSW... 
[Log] Expected SHA1sum: 2da347b2e544d122bf30417048fafeaa66f9faa1 
[Log] Actual SHA1sum:   c4e6b02abaaab213d0a904af5005ed6fbedead17 

[Error] Verifying IPSW failed. Your IPSW may be corrupted or incomplete. 
* Delete/replace the IPSW and run the script again 
thanks for your reply . the problem is still . the  ipsw is Automatic download
