### ISSUE TITLE
iPad mini 2 downgrader fail

### ISSUE THREAD

**Issue by OwnerCM** [LukeZGD/iOS-OTA-Downgrader#117]
Ubuntu 20.4
![0acfc4811db73a25cdaa52065bbf5a9](https://user-images.githubusercontent.com/22722811/130805859-6f8302bb-2dad-4666-ba9e-4a266fefc713.jpg)

**Comment by LukeZGD** [comment]
Please read the note in the script output:

> * This step may fail a lot, especially on Linux, and unfortunately there is nothing I can do about the low success rates.
> * The only option is to make sure you are using an Intel or Apple Silicon device, and to try multiple times

**Comment by OwnerCM** [comment]
> Please read the note in the script output:
> 
> > * This step may fail a lot, especially on Linux, and unfortunately there is nothing I can do about the low success rates.
> > * The only option is to make sure you are using an Intel or Apple Silicon device, and to try multiple times
> > * For more details, read the "Other Notes" section of the README

I tried it 10 times
