### ISSUE TITLE
./restore.sh tells me to rerun the script to continue, when i rerun it tells me the same thing as before

### ISSUE THREAD

**Issue by C0deMakr** [LukeZGD/iOS-OTA-Downgrader#119]

**Comment by LukeZGD** [comment]
More details please

**Comment by C0deMakr** [comment]
******* iOS-OTA-Downgrader ******* 
   Downgrader script by LukeZGD    

[Log] Detected libimobiledevice and libirecovery installed from Homebrew (Intel Mac) 
[Log] Running on platform: macos (11.3.1) 
[Log] Installing dependencies... 
xcode-select: error: command line tools are already installed, use "Software Update" to install updates
* iOS-OTA-Downgrader provides a copy of libimobiledevice and libirecovery by default 
* In case that problems occur, try installing them from Homebrew 
* The script will detect this automatically and will use the Homebrew versions of the tools 
* Install using this command: 'brew install libimobiledevice libirecovery' 
[Log] Install script done! Please run the script again to proceed 
user@Jakes-Macbook-Air iOS-OTA-Downgrader-master %

**Comment by C0deMakr** [comment]
When i rerun, it gives me the exact same thing, and i do have the iPad plugged in without a usb C to lightning cable. just a regular usb to lightning cable

**Comment by LukeZGD** [comment]
Go to the resources folder and try creating a folder named `libimobiledevice_macos`, then run the script again
