### ISSUE TITLE
help me please

### ISSUE THREAD

**Issue by Brylle32** [LukeZGD/iOS-OTA-Downgrader#120]
![image](https://user-images.githubusercontent.com/89861904/131540763-14a24797-c3ee-4c1d-aaea-69a659224591.jpeg)
iphone 5s running ios 12.5
i tried so many times but no luck at all.. please help.

**Comment by Brylle32** [comment]
i really want to downgrade my iphone 5s.. i only use bootable Ubuntu to my dell PC.

**Comment by Brylle32** [comment]
i also located the .ipsw file on the same folder.. is this ok? i really don't know what to do. please help.

**Comment by LukeZGD** [comment]
Please see my comment in #117 , I can't help you with that

If you want pwndfu to succeed, get a mac:hackintosh

**Comment by Brylle32** [comment]
well.. i leave it here.. thankyou bro! keep up the good work.
