### ISSUE TITLE
Suggestion: Blob validity checker

### ISSUE THREAD

**Issue by vaishnav67** [LukeZGD/iOS-OTA-Downgrader#123]
It would be cool if it was possible.

**Comment by LukeZGD** [comment]
Tools already exist for this purpose:

- [img4tool](https://github.com/tihmstar/img4tool/) for 64-bit devices' blobs
- validate tool from [xpwn](https://github.com/nyuszika7h/xpwn/) for 32-bit devices' blobs (though I'm not sure if the results for this are accurate, it will most likely just throw "BROKEN" most of the time)

As for iOS-OTA-Downgrader, I don't think there is any reason for me to validate OTA blobs that are being saved. For user-saved blobs (for "Other" downgrades), that would be up to the user.

**Comment by vaishnav67** [comment]
Ah cool, I was trying to downgrade mainly using "Other" downgrades (currently stuck due to a what() exception being thrown which I think was fixed in the latest futurerestore.) so I thought it would be helpful.

**Comment by LukeZGD** [comment]
> Ah cool, I was trying to downgrade mainly using "Other" downgrades (currently stuck due to a what() exception being thrown which I think was fixed in the latest futurerestore.) so I thought it would be helpful.

Are you using the latest commit of iOS-OTA-Downgrader? I have pushed some fixes recently so you may want to re-download and try again

**Comment by vaishnav67** [comment]
> > Ah cool, I was trying to downgrade mainly using "Other" downgrades (currently stuck due to a what() exception being thrown which I think was fixed in the latest futurerestore.) so I thought it would be helpful.
> 
> Are you using the latest commit of iOS-OTA-Downgrader? I have pushed some fixes recently so you may want to re-download and try again

Tried, still the same error
```
Version: b99eb8140d8e6c23f34e950102bb79e61c72384d - 152
Libipatcher Version: f32e41d850f51448bd6c588ead9c7d6455733f3c - 44
Odysseus Support: yes
[INFO] 32bit device detected
futurerestore init done
reading ticket /home/ubuntu/Downloads/iOS-OTA-Downgrader-master/4017975542579_iPad34_p101ap_10.2.1-14D27_ab607ad1e1bd64778f15468586ca9d395e7f800d.shsh2 done

WARNING: user specified not to flash a baseband. This can make the restore fail if the device needs a baseband!
if you added this flag by mistake you can press CTRL-C now to cancel
continuing restore in 5 4 3 2 1 
Found device in DFU mode
requesting to get into pwnRecovery later
Found device in DFU mode
Identified device as p101ap, iPad3,4
Extracting BuildManifest from IPSW
Product Version: 10.2.1
Product Build: 14D27 Major: 14
Device supports Image4: false
checking APTicket to be valid for this restore...
Verified ECID in APTicket matches device ECID
[WARNING] skipping ramdisk hash check, since device is in pwnDFU according to user
Variant: Customer Erase Install (IPSW)
This restore will erase your device data.
Extracting iBSS.p101.RELEASE.dfu...
terminate called after throwing an instance of 'libipatcher::exception'
  what():  std::exception
./resources/downgrade.sh: line 42: 51662 Aborted                 $futurerestore -t $SHSH --no-baseband $ExtraArgs "$IPSWRestore.ipsw"
```

**Comment by vaishnav67** [comment]
> > Tried, still the same error
> 
> hm, then I guess the old futurerestore that the script uses does not work for 32-bit iOS 10 restores, it works fine on versions 8.4.1 and below though

Yeah, the new futurerestore update doesn't throw it but it gets stuck at `Device supports Image4: false`.
