### ISSUE TITLE
Allow downgrades on 64 bit devices with shsh blobs to the firmwares that have compatible sep and baseband with the latest version

### ISSUE THREAD

**Issue by Grandboy46** [LukeZGD/iOS-OTA-Downgrader#125]
Hello,

I heard that this tool can downgrade to firmwares that the user has shsh blobs for on 32 bit devices. Is it also possible to do the same for 64 bit devices as long as the sep and baseband is compatible with the latest iOS version? Also, can this tool allow downgrades by asking user to jailbreak and set the nonce on the blobs and restoring with futurerestore using recovery mode?

**Comment by vaishnav67** [comment]
The tool uses futurerestore to downgrade it.

**Comment by LukeZGD** [comment]
> can this tool allow downgrades by asking user to jailbreak and set the nonce on the blobs and restoring with futurerestore using recovery mode?

The "Other" downgrades for iOS-OTA-Downgrader will be for 32-bit only. For 64-bit devices, use dimentio or nonce setter of your jailbreak to set the nonce, then use futurerestore (the [CLI](https://github.com/m1stadev/futurerestore) or the [GUI](https://github.com/CoocooFroggy/FutureRestore-GUI))
