### ISSUE TITLE
[Suggestions] More ways to fix common errors (instant reboot, no langid, etc.)

### ISSUE THREAD

**Issue by loshvitalik** [LukeZGD/iOS-OTA-Downgrader#126]
Just wanted to leave my troubleshooting steps in the place where most people will start to look for solutions, and maybe they're worth adding to 'Other Notes' section in Readme. Most of common problems are related to ipwndfu, well discussed on their repo but the tips are really hard to find and a bit scary-looking for people who just want to downgrade their iDevice. I'll try to describe a complete story from beginning so someone could skip unsuccessful trials.
In the end I successfully downgraded iPad Mini 2 (iPad4,5) from iOS 12 to 10.3.3 on Linux Mint live USB.

Firstly I tried to downgrade in live USB Linux Mint on my main Intel PC (i3-9100f), but had no luck, the iPad would enter normal DFU okay but always rebooted back to recovery when entering pwnDFU. Then I briefly got access to a M1 Macbook (using USB-C cable since there are no USB-A ports), both in arm64 and Rosetta environment, but the iPad didn't even enter normal DFU, which is quite strange (obviously I know how to enter DFU and tried several dozen times). After some time I tried the process on my main PC again, now tried 50+ times, using different original cables, different USB 3.0 and 2.0 ports, running ipwndfu independently, but the result was the same - instant reboot. Now I think it's probably impossible to do on this particular PC config, but who knows.

What finally helped me was to use a different PC, I started trying on an older Intel PC (i3-2130 from 2011), the same Linux Mint live USB (make sure you've got enough RAM if you are running the tool completely in live USB environment, or put it on the other drive, I had 4 GB so there was not enough space to download and extract IPSW). Plugged iPad into USB 2.0 port and the behavior was different - 50% of the time instant reboot, 50% of the time the ipwndfu would detect the device and start entering pwnDFU, but then the iPad locks up at black screen and the tool doesn't detect it. I switched to USB 3.0 port, it worked better, entered pwnDFU but always threw "`Device has no langid`" error. I updated libusb with `sudo apt install libusb-dev`, nothing changed, but it could have helped later so I recommend doing that.
The main thing is, when the tool is throwing this error, the device is already in pwnDFU but for some reason lost connection to the PC. I found the final steps to resolve this problem deep in ipwndfu discussions, so to keep it simple:
1. The device hasn't rebooted, ipwndfu throws "`Device has no langid`" error.
2. Quickly unplug/plug the lightning cable from the device side. By quick, I mean really quick - without pulling the connector more than two millimeters out, just 0.1 sec unclick-click.
3. Run the command `lsusb -d 0x5AC:0x1227 -vv`. If it returns no output, then force reset the iDevice and continue from start (enter DFU, run restore.sh, and on later runs do the unplug/plug quickier). If it returns information about device, but lines `iManufacturer`, `iProduct`, `iSerial` and ` iConfiguration` contain a single number and then ` (error)` with/without error description, then go to step 2 (you may go through this cycle many times, it's a matter of perfect timing). If these lines contain full information and **no errors** , then it works - run restore.sh and it should downgrade successfully.

**Comment by LukeZGD** [comment]
Thanks for sharing, I will be adding this to the readme later

**Comment by OwnerCM** [comment]
> Just wanted to leave my troubleshooting steps in the place where most people will start to look for solutions, and maybe they're worth adding to 'Other Notes' section in Readme. Most of common problems are related to ipwndfu, well discussed on their repo but the tips are really hard to find and a bit scary-looking for people who just want to downgrade their iDevice. I'll try to describe a complete story from beginning so someone could skip unsuccessful trials. In the end I successfully downgraded iPad Mini 2 (iPad4,5) from iOS 12 to 10.3.3 on Linux Mint live USB.
> 
> Firstly I tried to downgrade in live USB Linux Mint on my main Intel PC (i3-9100f), but had no luck, the iPad would enter normal DFU okay but always rebooted back to recovery when entering pwnDFU. Then I briefly got access to a M1 Macbook (using USB-C cable since there are no USB-A ports), both in arm64 and Rosetta environment, but the iPad didn't even enter normal DFU, which is quite strange (obviously I know how to enter DFU and tried several dozen times). After some time I tried the process on my main PC again, now tried 50+ times, using different original cables, different USB 3.0 and 2.0 ports, running ipwndfu independently, but the result was the same - instant reboot. Now I think it's probably impossible to do on this particular PC config, but who knows.
> 
> What finally helped me was to use a different PC, I started trying on an older Intel PC (i3-2130 from 2011), the same Linux Mint live USB (make sure you've got enough RAM if you are running the tool completely in live USB environment, or put it on the other drive, I had 4 GB so there was not enough space to download and extract IPSW). Plugged iPad into USB 2.0 port and the behavior was different - 50% of the time instant reboot, 50% of the time the ipwndfu would detect the device and start entering pwnDFU, but then the iPad locks up at black screen and the tool doesn't detect it. I switched to USB 3.0 port, it worked better, entered pwnDFU but always threw "`Device has no langid`" error. I updated libusb with `sudo apt install libusb-dev`, nothing changed, but it could have helped later so I recommend doing that. The main thing is, when the tool is throwing this error, the device is already in pwnDFU but for some reason lost connection to the PC. I found the final steps to resolve this problem deep in ipwndfu discussions, so to keep it simple:
> 
> 1. The device hasn't rebooted, ipwndfu throws "`Device has no langid`" error.
> 2. Quickly unplug/plug the lightning cable from the device side. By quick, I mean really quick - without pulling the connector more than two millimeters out, just 0.1 sec unclick-click.
> 3. Run the command `lsusb -d 0x5AC:0x1227 -vv`. If it returns no output, then force reset the iDevice and continue from start (enter DFU, run restore.sh, and on later runs do the unplug/plug quickier). If it returns information about device, but lines `iManufacturer`, `iProduct`, `iSerial` and ` iConfiguration` contain a single number and then ` (error)` with/without error description, then go to step 2 (you may go through this cycle many times, it's a matter of perfect timing). If these lines contain full information and **no errors** , then it works - run restore.sh and it should downgrade successfully.

I met exactly the same problem, may I ask which part of the unplug/ plug operation in the second step was carried out? Thank you!

**Comment by loshvitalik** [comment]
> I met exactly the same problem, may I ask which part of the unplug/ plug operation in the second step was carried out? Thank you!

I might not have explained this thoroughly, the operation is to unplug THEN plug the cable from/to the device in a matter of milliseconds. The idea is to do it quickly so the PC does not 'forget' that the device is connected, but not too short to make the device send its information again. So, you're holding your device in one hand, and hold the Lightning connector with two fingers, but with the same hand, push slightly into the bottom of the device - this way you can do it really quickly. You can practice this without connecting to PC first and you should probably get the idea :)
