### ISSUE TITLE
Daibutsu Untether support for iPad2,1, iPad2,2 and iPad2,3

### ISSUE THREAD

**Issue by Grandboy46** [LukeZGD/iOS-OTA-Downgrader#130]
Hello, 

I saw that you are switching from eta son untether to daibutsu untether on A5 and A5X devices. As you switched from Etason to Daibutsu untether on iPhone 4s and iPad2,4, is it also possible to do the same on other iPad 2 models?

**Comment by LukeZGD** [comment]
No, since daibutsu does not support them (not sure if it will be added), and it is not really needed since EtasonJB works fine on those devices
