### ISSUE TITLE
Option to use Etason Untether on 4s along with Daibutsu Untether

### ISSUE THREAD

**Issue by Grandboy46** [LukeZGD/iOS-OTA-Downgrader#131]
Hello, 

I know that Daibutsu untether is more stable on A5 devices, but the Untether for coolbooter not working with Daibutsu untether. On iPhone 4s, can you please option to use either Daibutsu or Etason Untether?

**Comment by LukeZGD** [comment]
I planned on doing this, but I would prefer to wait for [Coolbooter Untetherer to be updated](https://www.reddit.com/r/LegacyJailbreak/comments/p50xqs/update_daibutsu_jailbreak_v11_beta_2_fixed_icon/h944qx5/) instead, not sure on when this update would come though

**Comment by dora2-iOS** [comment]
You should be able to impersonate TaiG by creating the following empty files and directories:
```
mkdir /taig
touch /taig/taig
```

**Comment by Nathanisadumbass** [comment]
lol the Medicine-Suspicious guy is me

**Comment by LukeZGD** [comment]
> You should be able to impersonate TaiG by creating the following empty files and directories:
> 
> ```
> mkdir /taig
> touch /taig/taig
> ```

It works! This gets Coolbooter Untetherer working in daibutsu

This seems to be a good workaround for now while waiting for the untetherer to get updated, I think I should close this issue now
