### ISSUE TITLE
is anyone successful downgrade under Linux?

### ISSUE THREAD

**Issue by abroter** [LukeZGD/iOS-OTA-Downgrader#132]
I tried about hundreds, truly hundreds,  still fail.

**Comment by LukeZGD** [comment]
Is this A7?

**Comment by russianshroom** [comment]
I did on A5 mini fmi locked from 9.3.5 to 8.1.4 with arduino for pwndfu

**Comment by LukeZGD** [comment]
OP is probably talking about A7 PwnDFU.

If this is the case, then see #117 #120 #121

Check my comments and the readme.

All downgrades have been tested and working without issues.
