### ISSUE TITLE
unable to use jailbreak option

### ISSUE THREAD

**Issue by Nathanisadumbass** [LukeZGD/iOS-OTA-Downgrader#133]
says this when its on the untether part

[*] Installing untether package
merging �
cannot find �, make sure your slashes are in the right direction

**Comment by Nathanisadumbass** [comment]
nvm ignore the second issue, arduino wasnt putting into pwnDFU properly

**Comment by LukeZGD** [comment]
What platform (macos/linux) and iOS device?

**Comment by Nathanisadumbass** [comment]
pop_OS iPhone 4s arduino pwnDFU, in the long run i just used a Linux mint laptop to restore, worked fine.

**Comment by LukeZGD** [comment]
I guess it might be something with the memory option, was it enabled when the error occurred? I'll try on pop later

**Comment by Nathanisadumbass** [comment]
21.04. i was using memory option, im pretty sure it happened without too.

**Comment by LukeZGD** [comment]
I think I have now fixed this issue in the latest commit 4b9a11d, please try again on Pop 21.04 if you can

**Comment by Nathanisadumbass** [comment]
Ok! I will try it later

**Comment by Nathanisadumbass** [comment]
it works now, thank you!
