### ISSUE TITLE
Additional issue with Jailbreak option on iPhone 5

### ISSUE THREAD

**Issue by lavavex** [LukeZGD/iOS-OTA-Downgrader#134]
When using the jailbreak option with memory option enabled or disabled, i get errored out on this line

replacing var
symlink: var (0777) -> private/var/
[*] Installing Cydia package
./resources/ipsw.sh: line 3:  4771 Segmentation fault: 11  $ipsw ./../$IPSW.ipsw ./../$IPSWCustom.ipsw $ExtraArgs ${JBFiles[@]}

[Error] Failed to find custom IPSW. Please run the script again 
* You may try selecting N for memory option 

have tried running script multiple times, with memory option enabled and disabled. device restores fine without jailbreak option

**Comment by LukeZGD** [comment]
I think I have now fixed this issue in commit 7101870, please try again on the latest commit 4b9a11d
