### ISSUE TITLE
Failes when loading iBEC

### ISSUE THREAD

**Issue by Savefade** [LukeZGD/iOS-OTA-Downgrader#137]
Every time that i try to downgrade my 4s to ios 8 or 6 it failes when loading iBEC at 60 %

**Comment by LukeZGD** [comment]
Is your device in kDFU/pwnDFU mode?

**Comment by Savefade** [comment]
> ppens when you device is only in normal DFU. Is your device in kDFU/pw

its in kdfu

**Comment by LukeZGD** [comment]
Then try force restarting and re enter kDFU again. You may also use kDFUApp

**Comment by Savefade** [comment]
a small detail im tring to downgrade my iphone 4s thats locked with icloud

**Comment by LukeZGD** [comment]
> a small detail im tring to downgrade my iphone 4s thats locked with icloud

Restoring might be a bad idea if that's the case, make sure to backup your activation records if possible: https://reddit.com/r/jailbreak/comments/7mjc5s/news_activation_records_from_ios_10_can_activate/

**Comment by Savefade** [comment]
but i have one thats restored and the other is disabled

**Comment by LukeZGD** [comment]
Anways since this is a known issue and duplicate, I will be closing this now


The solution to sending iBEC is to make sure your device is in kDFU/pwnDFU mode
