### ISSUE TITLE
GIve People a option to use a7 because ipwndfu doesn't work on windows, but it does on linux

### ISSUE THREAD

**Issue by Nathanisadumbass** [LukeZGD/iOS-OTA-Downgrader#139]
I'm wondering if you can give people a option for a7 if it's already pwned with a Linux system, or is it because of idevicerestore constraints?

**Comment by Nathanisadumbass** [comment]
what i'm getting at is did you disable pwndfu for this because idevicerestore issues, or ipwndfu not working on windows

**Comment by LukeZGD** [comment]
Yea I can add this later, pwndfu may not work but creating and restoring custom 10.3.3 IPSW should still work with futurerestore on Windows

**Comment by Nathanisadumbass** [comment]
also, cryptic is close to building the futurerestore test build on windows

**Comment by LukeZGD** [comment]
the latest commit cf0c9e4 now allows a7 restores, but I have not tested this, and I do not really plan on supporting it in any way for now, not until checkm8 works on windows
