### ISSUE TITLE
ChromeOS Support

### ISSUE THREAD

**Issue by Grandboy46** [LukeZGD/iOS-OTA-Downgrader#140]
Hello,

I noticed that ios-ota-downgrader supports windows, macOS and Linux and I wanted to do if it is possible to do the same on chromeos. Is it possible to add chromeos support?

**Comment by Nathanisadumbass** [comment]
bruh

**Comment by LukeZGD** [comment]
I have no plans to add support for ChromeOS. You may use Linux, I think that there is USB support for that. Note that OTA Downgrader supports x86_64 only on Linux, it is not compiled for arm64.
