### ISSUE TITLE
[iPhone 4S] 6.1.3 downgrade issue with cydia

### ISSUE THREAD

**Issue by qfoxb** [LukeZGD/iOS-OTA-Downgrader#147]
I recently downgraded my iPhone 4S to 6.1.3 and when prompted to jailbreak the install, I did as such. First, the Photos app icon was missing but that was fixed by a reboot, Then whenever I attempt to add a source in cydia it never actually adds it. When attempting to install a package (OpenSSH to be specific) I get an error along the lines of "post-installation script killed by signal (Trace/BPT trap" and I cannot SSH into my phone. Was this a bad restore or is it something wrong with patching an ipsw with cydia?

**Comment by LukeZGD** [comment]
Probably a bad IPSW.. What OS are you using, and are you using the latest commit c15e3c7?

**Comment by qfoxb** [comment]
I was most likely on da9d926, i was on Ubuntu 20.04

**Comment by LukeZGD** [comment]
Please try again on the latest commit, also delete the custom IPSW before doing so since it is no longer compatible with the latest

**Comment by qfoxb** [comment]
Would the custom IPSW be in the directory with restore.sh or would it be in another directory?
Also, would i have to upgrade to a later firmware to downgrade back to 6.1.3 again?

**Comment by LukeZGD** [comment]
The custom IPSW is in the directory with restore.sh

If OpenSSH is not working, then you have to update to downgrade again

**Comment by qfoxb** [comment]
Got it, thank you!

**Comment by qfoxb** [comment]
Yep this was a bad restore, just restored on c15e3c7 and it works fine.
