### ISSUE TITLE
[Error] No device detected. Please put the device in normal mode before proceeding.

### ISSUE THREAD

**Issue by XP-Luna** [LukeZGD/iOS-OTA-Downgrader#148]
Hi!

I always get this error when running the script. I also tried the steps in the Troubleshooting Wiki and reinstalled OpenSSH and rejailbroken my iPhone 4s several times. I also tried the kDFUApp, but nothing worked. I always get this error:
`[Error] No device detected. Please put the device in normal mode before proceeding.`

Like I said I have an iPhone 4s running iOS 9.3.5 and a M1 MacBook running Big Sur.
The iPhone is detected by macOS.

I hope you can help me!

**Comment by LukeZGD** [comment]
Sorry about that; please try again with latest commit 94e4779

**Comment by XP-Luna** [comment]
Sadly it still doesn´t work for me...

**Comment by LukeZGD** [comment]
double check if you're using the latest 94e4779, it is fixed

**Comment by XP-Luna** [comment]
I do, I replaced the old one and also tried using an Intel Mac

**Comment by LukeZGD** [comment]
Then for now, try this: https://github.com/LukeZGD/iOS-OTA-Downgrader/archive/920af4bdaf16c735853af97a7cef60b3caac6dca.zip

**Comment by XP-Luna** [comment]
I will try it, thank you

**Comment by XP-Luna** [comment]
Also doesn´t work

**Comment by LukeZGD** [comment]
I have figured out the issues, please try again with the latest commit 89d4e13

**Comment by XP-Luna** [comment]
Seems to work know!

**Comment by XP-Luna** [comment]
It is downgraded successfully, but I had to deny the latest baseband option and it only worked in kDFU, maybe you should look into that as well or just require it. But this script is excellent!

**Comment by LukeZGD** [comment]
I'll look into the latest baseband thing, thanks for letting me know

**Comment by LukeZGD** [comment]
Just to clarify in the latest baseband, what error does it show? Is it the "Downloading/verifying baseband failed" one?

**Comment by XP-Luna** [comment]
The errors begin here:
`Did set SEP+baseband path and firmware
ERROR: Unable to connect to device?!
ERROR: Unable to get FirmwarePreflightInfo
[WARNING] failed to read BasebandGoldCertID from device! Is it already in recovery?
[WARNING] using tsschecker's fallback to get BasebandGoldCertID. This might result in invalid baseband signing status information
[TSSC] opening saved/iPhone4,1/BuildManifest.plist
[TSSR] Checking BuildIdentity 0
[TSSR] Selected BuildIdentity for request
[TSSR] User specified to request only a Baseband ticket.
Request URL set to https://gs.apple.com/TSS/controller?action=2
TSS server returned: STATUS=94&MESSAGE=This device isn't eligible for the requested build.
ERROR: TSS request failed (status=94, message=This device isn't eligible for the requested build.)
Sending TSS request attempt 1... futurerestore: failed with exception:
[exception]:
what=baseband firmware is NOT being signed!`

**Comment by LukeZGD** [comment]
Fixed now as of ccd6803, thanks again

**Comment by XP-Luna** [comment]
No problem
