### ISSUE TITLE
./restore.sh freezing after "connection to [IP] closed by remote host"

### ISSUE THREAD

**Issue by arandomusernam** [LukeZGD/iOS-OTA-Downgrader#150]
All the previous steps completed successfully, but when it finishes putting my iPad2,1 into kDFU mode, it freezes after the step listed in the title. Any help would be much appreciated :).

**Comment by LukeZGD** [comment]
This happens sometimes. You can just [force restart](https://support.apple.com/guide/iphone/iph8903c3ee6/ios), rejailbreak and try again

**Comment by arandomusernam** [comment]
Thanks! Will Do.
