### ISSUE TITLE
Tsschecker not working correctly on iPad2,3

### ISSUE THREAD

**Issue by Grandboy46** [LukeZGD/iOS-OTA-Downgrader#153]
******* iOS-OTA-Downgrader ******* 
   Downgrader script by LukeZGD    

[Log] Running on platform: macos (12.0.1) 
[Log] Checking Internet connection... 
[Log] Apple Silicon Mac detected. Support may be limited, proceed at your own risk. 
[Log] Finding device in Normal mode... 
[Log] Finding device in DFU/recovery mode... 
[Log] iPad2,3 connected in DFU mode. 
[Log] ECID: (removed for safety reasons) 
*** Main Menu *** 
[Input] Select an option: 
1) Downgrade Device	      4) (Re-)Install Dependencies
2) Save OTA Blobs	      5) (Any other key to exit)
3) Create Custom IPSW
#? 1

[Input] Select iOS version: 
1) iOS 8.4.1		    3) Other (use SHSH blobs)
2) iOS 6.1.3		    4) (Any other key to exit)
#? 2

* DFU Advanced Menu 
* This menu is for ADVANCED USERS ONLY. 
* If you do not know what you are doing, EXIT NOW by pressing Ctrl+C and restart your device in normal mode. 
[Input] Select the mode that your device is currently in: 
1) kDFU mode
2) pwnDFU mode (A5)
3) Any other key to exit
#? 1
[Log] Downgrading iPad2,3 in kDFU/pwnDFU mode... 
[Log] Select your options when asked. If unsure, go for the defaults (press Enter/Return). 

[Input] Jailbreak Option 
* When this option is enabled, your device will be jailbroken on restore. 
* This option is enabled by default (Y). 
[Input] Enable this option? (Y/n): Y
[Log] Jailbreak option enabled. Using p0sixspwn for the jailbreak 

[Input] Memory Option for creating custom IPSW 
* This option makes creating the custom IPSW faster, but it requires at least 8GB of RAM. 
* If you do not have enough RAM, disable this option and make sure that you have enough storage space. 
* This option is enabled by default (Y). 
[Input] Enable this option? (Y/n): 
[Log] Memory option enabled. 

[Log] Checking signing status of iOS 9.3.6... 
Version: b9d193aa6e6d24421094873c830692d02d8b32f5 - 304
libfragmentzip version: 0.59-542a470d7be248681dba71d0f04e7dc8c2718b73
[TSSC] manually specified ECID to use, parsed "(removed for safety reasons)" to dec:(removed) hex:(removed)
[TSSC] opening firmware.json
[DOWN] downloading file https://api.ipsw.me/v2.1/firmwares.json/condensed
[JSON] counting elements
[JSON] parsing elements
[TSSC] got firmwareurl for iOS 9.3.6 build 13G37
[TSSC] opening Buildmanifest for iPad2,3_9.3.6_13G37
[LFZP] downloading BuildManifest.plist from http://updates-http.cdn-apple.com/2019/ios/041-80042-20190722-68F07B91-8EA1-4A3B-A930-35314A006ECB/iPad2,3_9.3.6_13G37_Restore.ipsw
100 [===========================================================================100 [===================================================================================================>]
[TSSR] Request URL set to https://gs.apple.com/TSS/controller?action=2
[TSSR] Sending TSS request attempt 1... failure
[Error] ERROR: TSS request failed (status=94, message=This device isn't eligible for the requested build.)
Firmware version 9.3.6 13G37 IS NOT signed!

iOS 9.3.6 for device iPad2,3 IS NOT being signed!
ls: *_iPad2,3_k95ap_9.3.6*.shsh*: No such file or directory

[Error] For some reason, the latest version for your device (iOS 9.3.6) is not signed. Cannot continue.

**Comment by Grandboy46** [comment]
Using an older version of tsschecker such as [this one](https://github.com/tihmstar/tsschecker/releases/tag/v212) may fix the issue. 

V304 output:

<img width="564" alt="Screen Shot 2021-12-05 at 20 39 05" src="https://user-images.githubusercontent.com/77637465/144757205-84b3bca1-e358-4fe1-9f86-3d680a38c68d.png">

V212 output:

<img width="563" alt="Screen Shot 2021-12-05 at 20 37 47" src="https://user-images.githubusercontent.com/77637465/144757170-cb558812-504d-4b80-873a-da55029d0b16.png">

**Comment by LukeZGD** [comment]
This is intentional, for some reason there are no signed basebands for the iPad2,3 right now, not even 9.3.5 or 9.3.6, so I won't allow it in the script since iOS-OTA-Downgrader will always restore with the latest baseband in futurerestore

https://twitter.com/_m1sta/status/1451053312476856320

The old tsschecker doesn't check for baseband signing properly

**Comment by jmkd3v** [comment]
Is there any way to downgrade an iPad2,3 that avoids this issue? Does using older tsschecker versions actually make a downgrade possible? I'm not sure what else to do here.
