### ISSUE TITLE
Custom ipsw cannot be found

### ISSUE THREAD

**Issue by Grandboy46** [LukeZGD/iOS-OTA-Downgrader#154]
******* iOS-OTA-Downgrader ******* 
   Downgrader script by LukeZGD    

[Log] Running on platform: macos (12.0.1) 
[Log] Checking Internet connection... 
[Log] Apple Silicon Mac detected. Support may be limited, proceed at your own risk. 
[Log] Finding device in Normal mode... 
[Log] Finding device in DFU/recovery mode... 
[Log] iPad3,3 connected in DFU mode. 
[Log] ECID: (removed for safety reasons)
*** Main Menu *** 
[Input] Select an option: 
1) Downgrade Device	      4) (Re-)Install Dependencies
2) Save OTA Blobs	      5) (Any other key to exit)
3) Create Custom IPSW
#? 1

[Input] Select iOS version: 
1) iOS 8.4.1		    3) (Any other key to exit)
2) Other (use SHSH blobs)
#? 1

* DFU Advanced Menu 
* This menu is for ADVANCED USERS ONLY. 
* If you do not know what you are doing, EXIT NOW by pressing Ctrl+C and restart your device in normal mode. 
[Input] Select the mode that your device is currently in: 
1) kDFU mode
2) pwnDFU mode (A5)
3) Any other key to exit
#? 1
[Log] Downgrading iPad3,3 in kDFU/pwnDFU mode... 
[Log] Select your options when asked. If unsure, go for the defaults (press Enter/Return). 

[Input] Jailbreak Option 
* When this option is enabled, your device will be jailbroken on restore. 
* This option is enabled by default (Y). 
[Input] Enable this option? (Y/n): y
[Log] Jailbreak option enabled. Using daibutsu for the jailbreak 

[Input] Memory Option for creating custom IPSW 
* This option makes creating the custom IPSW faster, but it requires at least 8GB of RAM. 
* If you do not have enough RAM, disable this option and make sure that you have enough storage space. 
* This option is enabled by default (Y). 
[Input] Enable this option? (Y/n): y
[Log] Memory option enabled. 

[Log] Checking signing status of iOS 9.3.6... 
Version: b9d193aa6e6d24421094873c830692d02d8b32f5 - 304
libfragmentzip version: 0.59-542a470d7be248681dba71d0f04e7dc8c2718b73
[TSSC] manually specified ECID to use, parsed "(removed for safety reasons)" to dec:(removed) hex:(removed)
[TSSC] opening firmware.json
[JSON] counting elements
[JSON] parsing elements
[TSSC] got firmwareurl for iOS 9.3.6 build 13G37
[TSSC] opening Buildmanifest for iPad3,3_9.3.6_13G37
[TSSR] Request URL set to https://gs.apple.com/TSS/controller?action=2
[TSSR] Sending TSS request attempt 1... success
also requesting APTicket for installType=Update
[TSSR] Request URL set to https://gs.apple.com/TSS/controller?action=2
[TSSR] Sending TSS request attempt 1... success
[TSSR] User specified doesn't to request a baseband ticket.
[TSSR] Request URL set to https://gs.apple.com/TSS/controller?action=2
[TSSR] Sending TSS request attempt 1... success
Saved shsh blobs!
Firmware version 9.3.6 13G37 IS signed!

iOS 9.3.6 for device iPad3,3 IS being signed!
[Log] Latest version for iPad3,3 (iOS 9.3.6) is signed. 
[Log] Saving iOS 8.4.1 blobs with tsschecker... 
Version: b9d193aa6e6d24421094873c830692d02d8b32f5 - 304
libfragmentzip version: 0.59-542a470d7be248681dba71d0f04e7dc8c2718b73
[TSSC] manually specified generator "0x1111111111111111"
[TSSC] manually specified ECID to use, parsed "(removed for safety reasons)" to dec:(removed) hex:(removed)
[TSSC] opening resources/manifests/BuildManifest_iPad3,3_8.4.1.plist
[WARNING] [TSSC] could not get id0 for installType=Erase. Using fallback installType=Update since user did not specify installType manually
[TSSR] User specified doesn't to request a baseband ticket.
[TSSR] Request URL set to https://gs.apple.com/TSS/controller?action=2
[TSSR] Sending TSS request attempt 1... success
[Error] [TSSR] Error: could not get id0 for installType=Erase
Saved shsh blobs!

iOS 8.4.1 for device iPad3,3 IS being signed!
[Log] Successfully saved 8.4.1 blobs. 
[Log] Verifying IPSW... 
[Log] Expected SHA1sum: bb1e741245266dbd276a7a79c1e83dbb875a5996 
[Log] Actual SHA1sum:   bb1e741245266dbd276a7a79c1e83dbb875a5996 
[Log] IPSW SHA1sum matches. 
[Log] Preparing custom IPSW... 
Hashing IPSW...
Matching IPSW in FirmwareBundles/... (bb1e7412...)
checking: FirmwareBundles//Down_iPod5,1_8.4.1_12H321.bundle/Info.plist
checking: FirmwareBundles//Down_iPhone4,1_8.4.1_12H321.bundle/Info.plist
checking: FirmwareBundles//Down_iPad2,5_8.4.1_12H321.bundle/Info.plist
checking: FirmwareBundles//Down_iPad2,4_8.4.1_12H321.bundle/Info.plist
checking: FirmwareBundles//Down_iPad2,7_8.4.1_12H321.bundle/Info.plist
checking: FirmwareBundles//Down_iPad2,6_8.4.1_12H321.bundle/Info.plist
checking: FirmwareBundles//Down_iPhone5,2_8.4.1_12H321.bundle/Info.plist
checking: FirmwareBundles//Down_iPad3,2_8.4.1_12H321.bundle/Info.plist
checking: FirmwareBundles//Down_iPad3,3_8.4.1_12H321.bundle/Info.plist
loading: 058-23917-023.dmg (17424652)
loading: 058-23954-023.dmg (16621836)
loading: 058-24073-023.dmg (1756166144)
loading: BuildManifest.plist (82918)
loading: Firmware/ (0)
loading: Firmware/all_flash/ (0)
loading: Firmware/all_flash/all_flash.j2aap.production/ (0)
loading: Firmware/all_flash/all_flash.j2aap.production/applelogo@2x~ipad.s5l8945x.img3 (17868)
loading: Firmware/all_flash/all_flash.j2aap.production/batterycharging0@2x~ipad.s5l8945x.img3 (9740)
loading: Firmware/all_flash/all_flash.j2aap.production/batterycharging1@2x~ipad.s5l8945x.img3 (35020)
loading: Firmware/all_flash/all_flash.j2aap.production/batteryfull@2x~ipad.s5l8945x.img3 (107724)
loading: Firmware/all_flash/all_flash.j2aap.production/batterylow0@2x~ipad.s5l8945x.img3 (119884)
loading: Firmware/all_flash/all_flash.j2aap.production/batterylow1@2x~ipad.s5l8945x.img3 (5260)
loading: Firmware/all_flash/all_flash.j2aap.production/DeviceTree.j2aap.img3 (86412)
loading: Firmware/all_flash/all_flash.j2aap.production/glyphplugin@2x~ipad-30pin.s5l8945x.img3 (14988)
loading: Firmware/all_flash/all_flash.j2aap.production/iBoot.j2a.RELEASE.img3 (295308)
loading: Firmware/all_flash/all_flash.j2aap.production/LLB.j2a.RELEASE.img3 (151948)
loading: Firmware/all_flash/all_flash.j2aap.production/manifest (359)
loading: Firmware/all_flash/all_flash.j2aap.production/recoverymode@2x~ipad-30pin.s5l8945x.img3 (140812)
loading: Firmware/dfu/ (0)
loading: Firmware/dfu/iBEC.j2a.RELEASE.dfu (295308)
loading: Firmware/dfu/iBSS.j2a.RELEASE.dfu (78220)
loading: Firmware/Mav4-5.4.00.Release.bbfw (41669194)
loading: Firmware/Mav4-5.4.00.Release.plist (649)
loading: Firmware/usr/ (0)
loading: Firmware/usr/local/ (0)
loading: Firmware/usr/local/standalone/ (0)
loading: kernelcache.release.j2a (9338828)
loading: Restore.plist (2280)
[+] needPref ? 1...
Restore Ramdisk: /Users/lukee/xpwn/ipsw-patch/img3.c:createAbstractFileFromImg3:643: 3f80a38172bd2fadd328acfcd5bdd64598bbfda20313552e6c4be91cecd1480ded116846331d511242adaeaf1b8a8e23
/Users/lukee/xpwn/ipsw-patch/img3.c:createAbstractFileFromImg3:643: 3f80a38172bd2fadd328acfcd5bdd64598bbfda20313552e6c4be91cecd1480ded116846331d511242adaeaf1b8a8e23
/Users/lukee/xpwn/ipsw-patch/img3.c:createAbstractFileFromImg3:643: 3f80a38172bd2fadd328acfcd5bdd64598bbfda20313552e6c4be91cecd1480ded116846331d511242adaeaf1b8a8e23
writing... success
[*] Found: RamdiskPackage
[*] Found: Hooker
[*] Found: Cydia
[*] Found: Untether
Writing out data..
run 0: start=0 sectors=512, length=12199, fileOffset=0x134
run 100: start=26214400 sectors=512, length=213106, fileOffset=0xa680e0
run 200: start=52428800 sectors=512, length=216990, fileOffset=0x1d853c8
run 300: start=78643200 sectors=312, length=141983, fileOffset=0x232765f
run 400: start=107618304 sectors=512, length=241052, fileOffset=0x318ebd5
run 500: start=133832704 sectors=512, length=202320, fileOffset=0x47fa746
run 600: start=160047104 sectors=512, length=88520, fileOffset=0x5442518
run 700: start=186261504 sectors=512, length=112169, fileOffset=0x5fd3ff9
run 800: start=212475904 sectors=512, length=233099, fileOffset=0x6e83a35
run 900: start=238690304 sectors=512, length=246201, fileOffset=0x8062f1b
run 1000: start=264904704 sectors=512, length=158652, fileOffset=0x8eed25e
run 1100: start=291119104 sectors=512, length=262144, fileOffset=0xa4c942e
run 1200: start=317333504 sectors=512, length=262144, fileOffset=0xbdc1f13
run 1300: start=343547904 sectors=512, length=262144, fileOffset=0xd6700f6
run 1400: start=369762304 sectors=512, length=262144, fileOffset=0xef5a6f3
run 1500: start=395976704 sectors=512, length=262144, fileOffset=0x10851647
run 1600: start=422191104 sectors=512, length=220333, fileOffset=0x12151647
run 1700: start=448405504 sectors=512, length=262144, fileOffset=0x13a08d13
run 1800: start=474619904 sectors=512, length=262144, fileOffset=0x15308d13
run 1900: start=500834304 sectors=512, length=262144, fileOffset=0x16beb5a5
run 2000: start=527048704 sectors=512, length=262144, fileOffset=0x184eb5a5
run 2100: start=553263104 sectors=512, length=262144, fileOffset=0x19ddf303
run 2200: start=579477504 sectors=512, length=262144, fileOffset=0x1b6d8f8a
run 2300: start=605691904 sectors=512, length=262144, fileOffset=0x1cfcfc4f
run 2400: start=631906304 sectors=512, length=196573, fileOffset=0x1e51553e
run 2500: start=658120704 sectors=512, length=183171, fileOffset=0x1f68f349
run 2600: start=684335104 sectors=512, length=190186, fileOffset=0x207ec561
run 2700: start=710549504 sectors=512, length=150312, fileOffset=0x21909887
run 2800: start=736763904 sectors=512, length=174777, fileOffset=0x22930dd9
run 2900: start=762978304 sectors=512, length=191148, fileOffset=0x23af4f64
run 3000: start=789192704 sectors=512, length=28339, fileOffset=0x24b2237e
run 3100: start=815407104 sectors=512, length=243159, fileOffset=0x25ea3b52
run 3200: start=841621504 sectors=512, length=250701, fileOffset=0x2768df3b
run 3300: start=867835904 sectors=512, length=91755, fileOffset=0x288ff63d
run 3400: start=894050304 sectors=512, length=262144, fileOffset=0x297a65a7
run 3500: start=920264704 sectors=512, length=91954, fileOffset=0x2acd856e
run 3600: start=946479104 sectors=512, length=262144, fileOffset=0x2bfa3410
run 3700: start=972693504 sectors=512, length=254069, fileOffset=0x2d6dd3da
run 3800: start=998907904 sectors=512, length=262144, fileOffset=0x2ef6b8d7
run 3900: start=1025122304 sectors=512, length=203283, fileOffset=0x30648734
run 4000: start=1051336704 sectors=512, length=239574, fileOffset=0x31dd2818
run 4100: start=1077551104 sectors=512, length=223199, fileOffset=0x331852e4
run 4200: start=1103765504 sectors=512, length=262144, fileOffset=0x34889ca4
run 4300: start=1129979904 sectors=512, length=262144, fileOffset=0x35f4b698
run 4400: start=1156194304 sectors=512, length=248455, fileOffset=0x3747d55a
run 4500: start=1182408704 sectors=512, length=262144, fileOffset=0x38d6c89d
run 4600: start=1208623104 sectors=512, length=175117, fileOffset=0x3a15cbe9
run 4700: start=1234837504 sectors=512, length=119630, fileOffset=0x3b11e1c1
run 4800: start=1261051904 sectors=512, length=181344, fileOffset=0x3c16cdf5
run 4900: start=1287266304 sectors=512, length=77854, fileOffset=0x3cd866d6
run 5000: start=1313480704 sectors=512, length=262144, fileOffset=0x3e10bec1
run 5100: start=1339695104 sectors=512, length=250072, fileOffset=0x3f727ded
run 5200: start=1365909504 sectors=512, length=262144, fileOffset=0x40f4e8b7
run 5300: start=1392123904 sectors=512, length=18221, fileOffset=0x41f1b3e8
run 5400: start=1418338304 sectors=512, length=115107, fileOffset=0x42a45490
run 5500: start=1444552704 sectors=512, length=225320, fileOffset=0x4391c0b5
run 5600: start=1470767104 sectors=512, length=211217, fileOffset=0x44ff4a92
run 5700: start=1496981504 sectors=512, length=262144, fileOffset=0x46865332
run 5800: start=1523195904 sectors=512, length=251050, fileOffset=0x47deed1d
run 5900: start=1549410304 sectors=512, length=262144, fileOffset=0x494d3826
run 6000: start=1575624704 sectors=512, length=262144, fileOffset=0x4a8447b8
run 6100: start=1601839104 sectors=512, length=262144, fileOffset=0x4c1375b0
run 6200: start=1628053504 sectors=512, length=262144, fileOffset=0x4d96ae39
run 6300: start=1654267904 sectors=512, length=191283, fileOffset=0x4f0e9927
run 6400: start=1680482304 sectors=512, length=170264, fileOffset=0x5069ad34
run 6500: start=1706696704 sectors=512, length=262144, fileOffset=0x51c5437e
run 6600: start=1732911104 sectors=512, length=262144, fileOffset=0x5351b68b
run 6700: start=1759125504 sectors=512, length=195543, fileOffset=0x54b1d2c9
run 6800: start=1785339904 sectors=512, length=176645, fileOffset=0x55a9f004
run 6900: start=1811554304 sectors=512, length=179764, fileOffset=0x567e6267
run 7000: start=1837768704 sectors=512, length=242649, fileOffset=0x57bb09f8
run 7100: start=1863983104 sectors=512, length=242105, fileOffset=0x58c91e6f
run 7200: start=1890197504 sectors=512, length=241875, fileOffset=0x59e3f0c6
run 7300: start=1916411904 sectors=512, length=225112, fileOffset=0x5b4c44a6
run 7400: start=1942626304 sectors=512, length=262144, fileOffset=0x5c783909
run 7500: start=1968840704 sectors=512, length=125199, fileOffset=0x5d76a2dc
run 7600: start=1995055104 sectors=512, length=135349, fileOffset=0x5e70765a
run 7700: start=2021269504 sectors=512, length=134356, fileOffset=0x5f6157a2
run 7800: start=2047483904 sectors=512, length=156781, fileOffset=0x604083a9
run 7900: start=2073698304 sectors=512, length=159125, fileOffset=0x6116b4db
run 8000: start=2099912704 sectors=512, length=157513, fileOffset=0x61fd9b21
run 8100: start=2126127104 sectors=512, length=120972, fileOffset=0x62d6633b
run 8200: start=2152341504 sectors=512, length=136360, fileOffset=0x63a40e81
run 8300: start=2178555904 sectors=512, length=122720, fileOffset=0x645d9700
run 8400: start=2204770304 sectors=512, length=156669, fileOffset=0x652d92e2
run 8500: start=2230984704 sectors=512, length=227698, fileOffset=0x65f1db74
run 8600: start=2257199104 sectors=512, length=88577, fileOffset=0x6696216e
run 8700: start=2283413504 sectors=512, length=127865, fileOffset=0x672ec27e
run 8800: start=2309627904 sectors=512, length=56637, fileOffset=0x67aea0e9
run 8900: start=2335842304 sectors=512, length=104075, fileOffset=0x6825372b
run 9000: start=2362056704 sectors=512, length=53386, fileOffset=0x68888a50
Growing root to minimum: 2281
patching etc/fstab (FirmwareBundles//Down_iPad3,3_8.4.1_12H321.bundle/fstab.patch)... retrieving...patching...writing... inline data
success
merging 
cannot find , make sure your slashes are in the right direction

[Error] Failed to find custom IPSW. Please run the script again 
* You may try selecting N for memory option

**Comment by LukeZGD** [comment]
Please try again with the [test branch](https://github.com/LukeZGD/iOS-OTA-Downgrader/archive/refs/heads/test.zip)

**Comment by LukeZGD** [comment]
I just tested it myself, it's fixed now
