### ISSUE TITLE
Error on executing script / Manjaro Linux

### ISSUE THREAD

**Issue by PawelGu** [LukeZGD/iOS-OTA-Downgrader#155]
On Manjaro I get

`iOS-OTA-Downgrader/restore.sh: line 78: ping: command not found
[Error] Please check your Internet connection before proceeding.'`

Anyone any idea? Ipad is connected, internet access available.

**Comment by LukeZGD** [comment]
You have an Arch system and you do not have `iputils` installed? Does Manjaro not provide the `base` package?

Install `iputils` by running this command: `sudo pacman -S iputils`

**Comment by PawelGu** [comment]
This worked =) Thank you so much. I never would have had any idea about these. There are some other things why I'm slowly thinking about to switch. Manjaro just makes it so easy to recognize hardware and install proper drivers...

**Comment by PawelGu** [comment]
Thanks for converting me to Endeavour OS =)
Sorry for spamming.
