### ISSUE TITLE
Sending iBEC issue

### ISSUE THREAD

**Issue by thienntm** [LukeZGD/iOS-OTA-Downgrader#160]
Hi, I tried downgrading my iPhone 5s to 10.3.3 on Mac Pro M1 Monterey and stuck at Sending iBEC step. Please help me check.
I tried 3 different USB ports (2.0, 3.0) and 2 cables but nothing change.
--------------------------------

[Log] Device in pwnDFU mode detected. 
[Log] Select your options when asked. If unsure, go for the defaults (press Enter/Return). 

[Log] Saving iOS 10.3.3 blobs with tsschecker... 
Version: b9d193aa6e6d24421094873c830692d02d8b32f5 - 304
libfragmentzip version: 0.59-542a470d7be248681dba71d0f04e7dc8c2718b73
[TSSC] manually specified generator "0x1111111111111111"
[TSSC] manually specified ECID to use, parsed "6562469285680" to dec:6562469285680 hex:5f7f1a68f30
[TSSC] opening resources/manifests/BuildManifest_iPhone6,2_10.3.3.plist
[TSSR] User specified doesn't to request a baseband ticket.
[TSSR] Request URL set to https://gs.apple.com/TSS/controller?action=2
[TSSR] Sending TSS request attempt 1... success
also requesting APTicket for installType=Update
[Error] [TSSR] Error: could not get id0 for installType=Update
[WARNING] [TSSR] failed to build tssrequest for alternative installType
[TSSR] User specified doesn't to request a baseband ticket.
[TSSR] Request URL set to https://gs.apple.com/TSS/controller?action=2
[TSSR] Sending TSS request attempt 1... failure
[Error] ERROR: TSS request failed (status=128, message=An internal error occurred.)
Saved shsh blobs!

iOS 10.3.3 for device iPhone6,2 IS being signed!
[Log] Successfully saved 10.3.3 blobs. 
[Log] Verifying IPSW... 
[Log] Expected SHA1sum: 46067e863e47f93bc867e865063bd8848cd80e9e 
[Log] Actual SHA1sum:   46067e863e47f93bc867e865063bd8848cd80e9e 
[Log] IPSW SHA1sum matches. 
[Log] Extracting IPSW: iPhone_4.0_64bit_10.3.3_14G60_Restore.ipsw 
[Log] Setting restore IPSW to: iPhone_4.0_64bit_10.3.3_14G60_Restore.ipsw 
[Log] Proceeding to futurerestore... 
Serving HTTP on 0.0.0.0 port 8888 ...
Version: v2.0.0-test(a58821b95f6417ad649ed7a5460337dcd82e200e-259)
img4tool version: 0.197+git20210129-aca6cf005c94caf135023263cbb5c61a0081804f-RELEASE
libipatcher version: 0.86+git20210810-6a3b358b673e74c2be9f9b8a74a63b80dd94abf1-RELEASE
Odysseus for 32-bit support: yes
Odysseus for 64-bit support: yes
[INFO] 64-bit device detected
futurerestore init done
reading signing ticket 6562469285680_iPhone6,2_n53ap_10.3.3-14G60_3a88b7c3802f2f0510abc432104a15ebd8bd7154.shsh2 is done
[TSSC] opening resources/manifests/BuildManifest_iPhone6,2_10.3.3.plist
[TSSR] Checking BuildIdentity 0
[TSSR] Selected BuildIdentity for request
[TSSR] User specified to not request a baseband ticket.
Request URL set to https://gs.apple.com/TSS/controller?action=2
Sending TSS request attempt 1... response successfully received
Did set SEP+baseband path and firmware
ERROR: Unable to connect to device?!
ERROR: Unable to get FirmwarePreflightInfo
[WARNING] failed to read BasebandGoldCertID from device! Is it already in recovery?
[WARNING] using tsschecker's fallback to get BasebandGoldCertID. This might result in invalid baseband signing status information
[TSSC] opening resources/manifests/BuildManifest_iPhone6,2_10.3.3.plist
[TSSR] Checking BuildIdentity 0
[TSSR] Selected BuildIdentity for request
[TSSR] User specified to request only a Baseband ticket.
Request URL set to https://gs.apple.com/TSS/controller?action=2
Sending TSS request attempt 1... response successfully received
Downloading the latest firmware components...
[TSSC] opening firmwares.json
[DOWN] downloading file https://api.ipsw.me/v2.1/firmwares.json/condensed
[TSSC] selecting latest firmware version: 12.5.5
[TSSC] got firmwareurl for iOS 12.5.5 build 16H62
[TSSC] opening Buildmanifest for iPhone6,2_12.5.5
[DOWN] downloading file https://updates.cdn-apple.com/2021WinterFCS/fullrestores/002-05523/A1FB133D-E3C8-44C7-946E-D7C5FEDDE663/BuildManifest.plist
[TSSR] Checking BuildIdentity 0
[TSSR] Checking BuildIdentity 1
[TSSR] Selected BuildIdentity for request
[TSSR] Checking BuildIdentity 0
[TSSR] Checking BuildIdentity 1
[TSSR] Selected BuildIdentity for request
[TSSR] Checking BuildIdentity 0
[TSSR] Checking BuildIdentity 1
[TSSR] Selected BuildIdentity for request
[TSSR] Checking BuildIdentity 0
[TSSR] Checking BuildIdentity 1
[TSSR] Selected BuildIdentity for request
[TSSR] Checking BuildIdentity 0
[TSSR] Checking BuildIdentity 1
[TSSR] Selected BuildIdentity for request
Finished downloading the latest firmware components!
Found device in DFU mode
requesting to get into pwnRecovery later
Found device in DFU mode
Identified device as n53ap, iPhone6,2
Extracting BuildManifest from iPSW
Product version: 10.3.3
Product build: 14G60 Major: 14
Device supports Image4: true
[TSSR] Checking BuildIdentity 0
[TSSR] Checking BuildIdentity 1
[TSSR] Checking BuildIdentity 2
[TSSR] Selected BuildIdentity for request
[TSSR] Checking BuildIdentity 0
[TSSR] Selected BuildIdentity for request
checking APTicket to be valid for this restore...
Verified ECID in APTicket matches device ECID
checking APTicket to be valid for this restore...
Verified ECID in APTicket matches device ECID
[IMG4TOOL] checking buildidentity 0:
[IMG4TOOL] checking buildidentity matches board ... NO
[IMG4TOOL] checking buildidentity 1:
[IMG4TOOL] checking buildidentity matches board ... NO
[IMG4TOOL] checking buildidentity 2:
[IMG4TOOL] checking buildidentity matches board ... YES
[IMG4TOOL] checking buildidentity has all required hashes:
[IMG4TOOL] checking hash for "AppleLogo"               OK (found "logo" with matching hash)
[IMG4TOOL] checking hash for "BasebandFirmware"        IGN (no digest in BuildManifest)
[IMG4TOOL] checking hash for "BatteryCharging0"        OK (found "chg0" with matching hash)
[IMG4TOOL] checking hash for "BatteryCharging1"        OK (found "chg1" with matching hash)
[IMG4TOOL] checking hash for "BatteryFull"             OK (found "batF" with matching hash)
[IMG4TOOL] checking hash for "BatteryLow0"             OK (found "bat0" with matching hash)
[IMG4TOOL] checking hash for "BatteryLow1"             OK (found "bat1" with matching hash)
[IMG4TOOL] checking hash for "BatteryPlugin"           OK (found "glyP" with matching hash)
[IMG4TOOL] checking hash for "DeviceTree"              OK (found "dtre" with matching hash)
[IMG4TOOL] checking hash for "KernelCache"             OK (found "krnl" with matching hash)
[IMG4TOOL] checking hash for "LLB"                     OK (found "illb" with matching hash)
[IMG4TOOL] checking hash for "OS"                      OK (found "rosi" with matching hash)
[IMG4TOOL] checking hash for "RecoveryMode"            OK (found "recm" with matching hash)
[IMG4TOOL] checking hash for "RestoreDeviceTree"       OK (found "rdtr" with matching hash)
[IMG4TOOL] checking hash for "RestoreKernelCache"      OK (found "rkrn" with matching hash)
[IMG4TOOL] checking hash for "RestoreLogo"             OK (found "rlgo" with matching hash)
[IMG4TOOL] checking hash for "RestoreRamDisk"          BAD! (hash not found in im4m)
[IMG4TOOL] checking hash for "RestoreSEP"              OK (found "rsep" with matching hash)
[IMG4TOOL] checking hash for "SEP"                     OK (found "sepi" with matching hash)
[IMG4TOOL] checking hash for "iBEC"                    OK (found "ibec" with matching hash)
[IMG4TOOL] checking hash for "iBSS"                    OK (found "ibss" with matching hash)
[IMG4TOOL] checking hash for "iBoot"                   OK (found "ibot" with matching hash)

failed verification with error:
[exception]:
what=verification failed!
code=84279308
line=1286
file=img4tool.cpp
commit count=197+git20210129:
commit sha  =aca6cf005c94caf135023263cbb5c61a0081804f:
[IMG4TOOL] checking buildidentity 3:
[IMG4TOOL] checking buildidentity matches board ... YES
[IMG4TOOL] checking buildidentity has all required hashes:
[IMG4TOOL] checking hash for "AppleLogo"               OK (found "logo" with matching hash)
[IMG4TOOL] checking hash for "BasebandFirmware"        IGN (no digest in BuildManifest)
[IMG4TOOL] checking hash for "BatteryCharging0"        OK (found "chg0" with matching hash)
[IMG4TOOL] checking hash for "BatteryCharging1"        OK (found "chg1" with matching hash)
[IMG4TOOL] checking hash for "BatteryFull"             OK (found "batF" with matching hash)
[IMG4TOOL] checking hash for "BatteryLow0"             OK (found "bat0" with matching hash)
[IMG4TOOL] checking hash for "BatteryLow1"             OK (found "bat1" with matching hash)
[IMG4TOOL] checking hash for "BatteryPlugin"           OK (found "glyP" with matching hash)
[IMG4TOOL] checking hash for "DeviceTree"              OK (found "dtre" with matching hash)
[IMG4TOOL] checking hash for "KernelCache"             OK (found "krnl" with matching hash)
[IMG4TOOL] checking hash for "LLB"                     OK (found "illb" with matching hash)
[IMG4TOOL] checking hash for "OS"                      OK (found "rosi" with matching hash)
[IMG4TOOL] checking hash for "RecoveryMode"            OK (found "recm" with matching hash)
[IMG4TOOL] checking hash for "RestoreDeviceTree"       OK (found "rdtr" with matching hash)
[IMG4TOOL] checking hash for "RestoreKernelCache"      OK (found "rkrn" with matching hash)
[IMG4TOOL] checking hash for "RestoreLogo"             OK (found "rlgo" with matching hash)
[IMG4TOOL] checking hash for "RestoreRamDisk"          BAD! (hash not found in im4m)
[IMG4TOOL] checking hash for "RestoreSEP"              OK (found "rsep" with matching hash)
[IMG4TOOL] checking hash for "SEP"                     OK (found "sepi" with matching hash)
[IMG4TOOL] checking hash for "iBEC"                    OK (found "ibec" with matching hash)
[IMG4TOOL] checking hash for "iBSS"                    OK (found "ibss" with matching hash)
[IMG4TOOL] checking hash for "iBoot"                   OK (found "ibot" with matching hash)

failed verification with error:
[exception]:
what=verification failed!
code=84279308
line=1286
file=img4tool.cpp
commit count=197+git20210129:
commit sha  =aca6cf005c94caf135023263cbb5c61a0081804f:
[IMG4TOOL] checking buildidentity 4:
[IMG4TOOL] checking buildidentity matches board ... NO
[IMG4TOOL] checking buildidentity 5:
[IMG4TOOL] checking buildidentity matches board ... NO
[IMG4TOOL] checking buildidentity 6:
[IMG4TOOL] checking buildidentity matches board ... NO
[IMG4TOOL] checking buildidentity 7:
[IMG4TOOL] checking buildidentity matches board ... NO
Failed to get exact match for build identity, using fallback to ignore certain values
[IMG4TOOL] checking buildidentity 0:
[IMG4TOOL] checking buildidentity matches board ... NO
[IMG4TOOL] checking buildidentity 1:
[IMG4TOOL] checking buildidentity matches board ... NO
[IMG4TOOL] checking buildidentity 2:
[IMG4TOOL] checking buildidentity matches board ... YES
[IMG4TOOL] checking buildidentity has all required hashes:
[IMG4TOOL] checking hash for "AppleLogo"               OK (found "logo" with matching hash)
[IMG4TOOL] checking hash for "BasebandFirmware"        IGN (no digest in BuildManifest)
[IMG4TOOL] checking hash for "BatteryCharging0"        OK (found "chg0" with matching hash)
[IMG4TOOL] checking hash for "BatteryCharging1"        OK (found "chg1" with matching hash)
[IMG4TOOL] checking hash for "BatteryFull"             OK (found "batF" with matching hash)
[IMG4TOOL] checking hash for "BatteryLow0"             OK (found "bat0" with matching hash)
[IMG4TOOL] checking hash for "BatteryLow1"             OK (found "bat1" with matching hash)
[IMG4TOOL] checking hash for "BatteryPlugin"           OK (found "glyP" with matching hash)
[IMG4TOOL] checking hash for "DeviceTree"              OK (found "dtre" with matching hash)
[IMG4TOOL] checking hash for "KernelCache"             OK (found "krnl" with matching hash)
[IMG4TOOL] checking hash for "LLB"                     OK (found "illb" with matching hash)
[IMG4TOOL] checking hash for "OS"                      OK (found "rosi" with matching hash)
[IMG4TOOL] checking hash for "RecoveryMode"            OK (found "recm" with matching hash)
[IMG4TOOL] checking hash for "RestoreDeviceTree"       OK (found "rdtr" with matching hash)
[IMG4TOOL] checking hash for "RestoreKernelCache"      OK (found "rkrn" with matching hash)
[IMG4TOOL] checking hash for "RestoreLogo"             OK (found "rlgo" with matching hash)
[IMG4TOOL] checking hash for "RestoreRamDisk"          BAD! (but ignoring due to whitelist)
[IMG4TOOL] checking hash for "RestoreSEP"              OK (found "rsep" with matching hash)
[IMG4TOOL] checking hash for "SEP"                     OK (found "sepi" with matching hash)
[IMG4TOOL] checking hash for "iBEC"                    OK (found "ibec" with matching hash)
[IMG4TOOL] checking hash for "iBSS"                    OK (found "ibss" with matching hash)
[IMG4TOOL] checking hash for "iBoot"                   OK (found "ibot" with matching hash)
Verified APTicket to be valid for this restore
[TSSR] Checking BuildIdentity 0
[TSSR] Selected BuildIdentity for request
Variant: Customer Erase Install (IPSW)
This restore will erase your device data.
Device found in DFU Mode.
Getting firmware keys for: n53ap
127.0.0.1 - - [08/Feb/2022 00:44:01] "GET /firmware/iPhone6,2/14G60 HTTP/1.1" 301 -
127.0.0.1 - - [08/Feb/2022 00:44:01] "GET /firmware/iPhone6,2/14G60/ HTTP/1.0" 200 -
127.0.0.1 - - [08/Feb/2022 00:44:01] "GET /firmware/iPhone6,2/14G60 HTTP/1.1" 301 -
127.0.0.1 - - [08/Feb/2022 00:44:01] "GET /firmware/iPhone6,2/14G60/ HTTP/1.0" 200 -
Repacking patched bootloaders as IMG4
Sending iBSS (164898 bytes)...
[==================================================] 100.0%
Booting iBSS, waiting for device to disconnect...
Booting iBSS, waiting for device to reconnect...
Sending iBEC (648226 bytes)...
[=========================================         ]  80.9%Cleaning up...
[exception]:
what=ERROR: Unable to send iBEC component: Unable to upload data to device

code=39845905
line=608
file=futurerestore.cpp
commit count=259:
commit sha  =a58821b95f6417ad649ed7a5460337dcd82e200e:
Done: restoring failed!

[Log] Restoring done! 
[Log] Downgrade script done!

**Comment by LukeZGD** [comment]
iOS-OTA-Downgrader only supports M1 Macs for versions 11.0 to 11.2.3 only. 11.3 and higher are not supported

**Comment by OwnerCM** [comment]
Encounter the same problem, now can only brush the Mac system?

**Comment by thienntm** [comment]
Hi, thank for your reply. After tried many times, I decided to install ubuntu using Wubiuefi and it worked perfectly at the first try. Thank a lot :)

**Comment by thienntm** [comment]
> > Hi, thank for your reply. After tried many times, I decided to install ubuntu using Wubiuefi and your tool worked perfectly at the first try. Thank a lot :)
> 
> Which version of Ubuntu are you using?

I used 20.04

**Comment by OwnerCM** [comment]
> > > Hi, thank for your reply. After tried many times, I decided to install ubuntu using Wubiuefi and your tool worked perfectly at the first try. Thank a lot :)
> > 
> > 
> > Which version of Ubuntu are you using?
> 
> I used 20.04

I also use 20.04, but mine has been rebooted in checkM8 phase, could you please provide the Ubuntu link or special configuration you use, thank you!

**Comment by thienntm** [comment]
> > > > Hi, thank for your reply. After tried many times, I decided to install ubuntu using Wubiuefi and your tool worked perfectly at the first try. Thank a lot :)
> > > 
> > > 
> > > Which version of Ubuntu are you using?
> > 
> > 
> > I used 20.04
> 
> I also use 20.04, but mine has been rebooted in checkM8 phase, could you please provide the Ubuntu link or special configuration you use, thank you!

I downloaded the latest version on ubuntu website and install it using Wubiuefi. 
I read a topic on reddit about using live usb to downgrade, but you will easily got error "The device has no langid" if using live usb (I also got this case too). There is a comment on that topic about using wubiuefi to downgrade and many people confirm that it worked too. I followed them succeed on the first try 😂 so you can give a try.

**Comment by thienntm** [comment]
> > > > > Hi, thank for your reply. After tried many times, I decided to install ubuntu using Wubiuefi and your tool worked perfectly at the first try. Thank a lot :)
> > > > 
> > > > 
> > > > Which version of Ubuntu are you using?
> > > 
> > > 
> > > I used 20.04
> > 
> > 
> > I also use 20.04, but mine has been rebooted in checkM8 phase, could you please provide the Ubuntu link or special configuration you use, thank you!
> 
> I downloaded the latest version on ubuntu website and install it using Wubiuefi. I read a topic on reddit about using live usb to downgrade, but you will easily got error "The device has no langid" if using live usb (I also got this case too). There is a comment on that topic about using wubiuefi to downgrade and many people confirm that it worked. I followed them succeed on the first try 😂 so you can give a try.

**Comment by OwnerCM** [comment]
> 



> > > > > Hi, thank for your reply. After tried many times, I decided to install ubuntu using Wubiuefi and your tool worked perfectly at the first try. Thank a lot :)
> > > > 
> > > > 
> > > > Which version of Ubuntu are you using?
> > > 
> > > 
> > > I used 20.04
> > 
> > 
> > I also use 20.04, but mine has been rebooted in checkM8 phase, could you please provide the Ubuntu link or special configuration you use, thank you!
> 
> I downloaded the latest version on ubuntu website and install it using Wubiuefi. I read a topic on reddit about using live usb to downgrade, but you will easily got error "The device has no langid" if using live usb (I also got this case too). There is a comment on that topic about using wubiuefi to install ubuntu and many people confirm that it worked too. I followed them succeed at the first try 😂 so you can give a try.

Sorry, I checked some articles on Reddit and searched for the same problem, but didn't find an obvious solution. Could you please help to provide the link? Thank you!

**Comment by elpepe1024** [comment]
i have the same problem on an intel mac
