### ISSUE TITLE
iPhone 4S on iOS 8.4.1 Boot Loop after first boot

### ISSUE THREAD

**Issue by SwiftMove** [LukeZGD/iOS-OTA-Downgrader#164]
I successfully restored an iPhone 4S using the latest commit. After iOS-OTA-Downgrader finishes the restore, the device boots up to the Setup app. I was able to activate and get to the Home Screen without a problem. The Cydia icon appears on the Home Screen as well. But as soon as I reboot the device, it will show the Apple logo for about 13 seconds and then turn off, then the Apple logo appears again going thru this cycle indefinitely. I tried restoring another iPhone 4S that I have and the same thing happened as well. This only happens if I select the "Jailbreak" option. If I restore the device without "Jailbreak" enabled, then the device boots up and can be rebooted no problem. I was also able to successfully downgrade the device to iOS 6.1.3 with no issues. So I'm assuming this has something to do with daibutsu.

iPhone 4S (iPhone4,1, CPU 8490)
macOS 10.4.6
iOS-OTA-Downloader [ea5df0c]
Downgrading to iOS 8.4.1 via pwnedDFU using an Arduino Uno

**Comment by LukeZGD** [comment]
uohhhh 😭

**Comment by LukeZGD** [comment]
https://github.com/LukeZGD/iOS-OTA-Downgrader/wiki/Troubleshooting#jailbreak-option-for-32-bit-devices

**Comment by SwiftMove** [comment]
Works fine? Have you tested with your latest commit? Like I said before, it boots up just fine on first boot right after the restore. But as soon as I reboot the device, it goes into a boot loop. Is there something that needs to be done after the first boot like applying a patch or something?

**Comment by LukeZGD** [comment]
Yes, it boots just fine on my 4S
