### ISSUE TITLE
iPhone 4S on iOS 8.4.1 Cydia won't open with latest commit

### ISSUE THREAD

**Issue by SwiftMove** [LukeZGD/iOS-OTA-Downgrader#170]
I successfully restored my iPhone 4S using the latest commit. However, Cydia refuses to open. I tap on the icon and it flashes white like it's gonna open and then just goes back to the SpringBoard. Same thing that happens when you try to open any Cydia app when you're not in Jailbreak mode. This is only happening if I restore/jailbreak iOS 8.4.1. If I restore/jailbreak 6.1.3 then Cydia works fine. 

iPhone 4S (iPhone4,1, CPID 8490)
macOS 10.4.6
iOS-OTA-Downloader (0d1baac)
Downgrading to iOS 8.4.1 via pwnedDFU using an Arduino Uno

**Comment by LukeZGD** [comment]
The jailbreak option has varying results (for some reason), it works for me and some users but also fails on others. It is something that I can't figure out and fix, sorry

I have also updated the message in the ["Troubleshooting" wiki page](https://github.com/LukeZGD/iOS-OTA-Downgrader/wiki/Troubleshooting#jailbreak-option-for-32-bit-devices) about this issue

**Comment by SwiftMove** [comment]
How about adding an option to allow the user to choose whether EtasonJB or daibutsu is used for the jailbreak? As you said yourself, sometimes things work for some users that don't work for others. This way the user can choose between two options instead of having one, which in my case doesn't work.

**Comment by LukeZGD** [comment]
Sure, added in b6d450a

**Comment by SwiftMove** [comment]
Ok, I tested the latest commit and now everything is working fine when I selected etasonJB instead of daibutsu. However, I did run into a bug when attempting to use the new commit. 

When I first tested the new commit, I went thru the menu and selected "etasonJB" from the options. After iOS-OTA-Downgrader finished restoring my device, I went thru the Setup app and then from the Homescreen I attempted to open Cydia. It crashed, the same way it did before when using daibutsu. I thought that was very odd so it got me to thinking, how can I verify that iOS-OTA-Downgrader actually installed etasonJB instead of daibutsu? 

After checking the logs, I realized that iOS-OTA-Downgrader didn't actually rebuild the Custom IPSW since it already found a previous one sitting in the folder. So I deleted the Custom IPSW, re-ran iOS-OTA-Downgrader again, selecting the etasonJB option of course, and voila, everything works fine now.

So iOS-OTA-Downgrader won't rebuild a new Custom IPSW if it finds one currently in the folder, even if you're choosing a different Jailbreak option. So I think an easy fix to this would be to rename the Custom IPSW files to include "daibutsu" or "etasonJB" in them and then modify iOS-OTA-Downgrader to check for each type when deciding whether a Custom IPSW needs to be created or not.

But other than that, everything is working great now! Thanks for adding that option to allow the user to choose between the two Jailbreaks. I'm sure other users will find this extremely useful, I know I did. 😀

**Comment by LukeZGD** [comment]
Thanks for letting me know, custom IPSW file naming is now done in 0aba782

**Comment by ivanushka123amongus** [comment]
Interestingly, I have an issue where Cydia will only load if I lock the iPhone screen. Can't figure out whats happening
same device same iOS, if that helps I live in Russia

**Comment by deeptypeflow** [comment]
в россии сидия недоступна благодаря ркн, поставь прокси через настройки вайфая. древнюю ишью ты выбрал конечно я херею именно

**Comment by ivanushka123amongus** [comment]
> в россии сидия недоступна благодаря ркн, поставь прокси через настройки вайфая. древнюю ишью ты выбрал конечно я херею именно

Серьезно?? Она работала еще неделю назад у меня на iOS 9 пока я не сделал даунгрейд

**Comment by deeptypeflow** [comment]
да уже больше года так-то, именно сайт саурика заблочен потому что на амазоне лежит, без прокси ниче не сделать, но прокси я тебе дать не могу потому что меня скорее всего Люк снесет
если ты один раз прогрузил ее то она будет работать потому что домашная страница в кеше
