### ISSUE TITLE
Downgrade iPad Air 1

### ISSUE THREAD

**Issue by Tom0u51** [LukeZGD/iOS-OTA-Downgrader#172]
Hello, 
Thanks for your tools.
I try to downgrade iPad Air 1 (iPad 4,1) from iOS 12.5.5 to 10.3.3. 
I use a Debian 11 livecd for that, but i have a lot of problem for entering in pwnDFU, i saw that there is a low success rate with Linux.
One time i got this error : no langid after entering in pwnDFU mode.

Can you tell me if your tools is compatible with my hardware / version please? 

Thanks!

**Comment by LukeZGD** [comment]
Your device and distro are compatible. It's just the low success rate on Linux

For more details, go to the [Troubleshooting wiki page](https://github.com/LukeZGD/iOS-OTA-Downgrader/wiki/Troubleshooting)

**Comment by Tom0u51** [comment]
Thanks for your answer, 

I installed a virtual machine with MacOS 11.6.5 (VMware Workstation), but I have a problem when I choose the pwnDFU tool, none of the 2 work, here attached screenshots : 

![error_01](https://user-images.githubusercontent.com/104263475/164980553-7fc713f6-0b7f-41a3-aad9-2e3eaf5f5a71.png)
![error_02](https://user-images.githubusercontent.com/104263475/164980558-abfa651d-8e25-44aa-9efb-8f12305d2316.png)

All requirements are met, I checked your troubleshooting guide.
Is the problem due to the fact that I go through a virtual machine?
