### ISSUE TITLE
Error pwnDFU tool 

### ISSUE THREAD

**Issue by Tom0u51** [LukeZGD/iOS-OTA-Downgrader#173]
Hello, 

Downgrade : iPad Air 1, iOS 12.5.5 to 10.3.3

I installed a virtual machine with MacOS 11.6.5 (VMware Workstation), but I have a problem when I choose the pwnDFU tool, none of the 2 tools work, here attached screenshots : 

ipwnder_lite : 

![error_01](https://user-images.githubusercontent.com/104263475/164980553-7fc713f6-0b7f-41a3-aad9-2e3eaf5f5a71.png)

iPwnder32 : 

![error_02](https://user-images.githubusercontent.com/104263475/164980558-abfa651d-8e25-44aa-9efb-8f12305d2316.png)

All requirements are met, I checked your troubleshooting guide.
Is the problem due to the fact that I go through a virtual machine?

**Comment by LukeZGD** [comment]
Yes, virtual machine will not work

It needs to run on a Mac, Hackintosh, or KVM with USB passthrough
