### ISSUE TITLE
./resources/libimobiledevice_linux/ideviceinfo: error while loading shared libraries: libssl.so.1.1: cannot open shared object file: No such file or directory(Ubuntu 22.04 LTS)

### ISSUE THREAD

**Issue by Kubamach** [LukeZGD/iOS-OTA-Downgrader#174]
I have noticed this error when starting the script. Reinstalling and following the instructions given in the troubleshooting guide does nothing. ![Screenshot from 2022-04-28 18-20-58](https://user-images.githubusercontent.com/69034405/165799658-0a3b9560-5db6-4f5f-a9cb-209dab74b187.png)

**Comment by LukeZGD** [comment]
Please try again in the latest commit 9d3ab0f, I updated the tools

**Comment by Kubamach** [comment]
Works perfectly now. Thank you.
