### ISSUE TITLE
I have issue, with download firmwares.json

### ISSUE THREAD

**Issue by Bartixxx32** [LukeZGD/iOS-OTA-Downgrader#175]
Hello, tbh i dont know any reason for that, this screenshot is all i know about it ...
Device: Iphone 5
OS: Kubuntu 22.04
![obraz](https://user-images.githubusercontent.com/16412925/166118212-ba1cba51-d4fb-4bc5-aa7e-b96e22673af6.png)

**Comment by Bartixxx32** [comment]
Ok, after manually downloaded firmwares.json to this patch, its doing somentig, anyway, its an issue

**Comment by LukeZGD** [comment]
Should now be fixed in 7ab1b79
