### ISSUE TITLE
Any way this could work for appleTV 4k?

### ISSUE THREAD

**Issue by darbysauter** [LukeZGD/iOS-OTA-Downgrader#176]
I jailbroke my AppleTV 4k a while ago. and for some reason the updates fail after the "preparing update" step. I've tried factory resetting the device, jailbreaking and restoring file system. I even reversed Nitos tool for disabling/enabling software updates and ran the commands to enable myself.

Unfortunately since theres no way you can normally restore. apple doesnt provide ipsw for atv4k. but since I have the breakout board i could restore, but there is only the OTAs and theyre still signed according to ipsw.me. Is there any way this could work on it?

**Comment by LukeZGD** [comment]
iOS-OTA-Downgrader will only support A5(X), A6(X), and A7 devices. No other device support will be added
