### ISSUE TITLE
Daibutsu doesn't actually support the iPhone5,2

### ISSUE THREAD

**Issue by TheMasterOfMike** [LukeZGD/iOS-OTA-Downgrader#177]
(Sorry if this isn't the right place, couldn't find better though)

https://github.com/LukeZGD/iOS-OTA-Downgrader/wiki/Troubleshooting#jailbreak-option-for-32-bit-devices says that Daibutsu is used for the iPhone5,2, but https://dora2ios.web.app/daibutsu.html says that it only supports (most) A5(X) devices, which does not include the iPhone5,2.

**Comment by LukeZGD** [comment]
daibutsu doesn't, but [daibutsuCFW does](https://github.com/LukeZGD/daibutsuCFW#list-of-flags-and-devices-supported-by-haxx_overwrite-dyld-haxx)
