### ISSUE TITLE
Daibutsu: cydia crashing on launch

### ISSUE THREAD

**Issue by Savefade** [LukeZGD/iOS-OTA-Downgrader#178]
Downgraded my iPhone 4s blah blah 100% unheard off
When i open cydia it crashes immediately
3uTools tells me the device is NOT jailbroken
Device info:
Capacity:32GB
black

**Comment by LukeZGD** [comment]
Please see the [Troubleshooting wiki page](https://github.com/LukeZGD/iOS-OTA-Downgrader/wiki/Troubleshooting#jailbreak-option-for-32-bit-devices):

> - iPhone4,1 and iPhone5,2 users can choose between daibutsu and EtasonJB. If one does not work, you may try again with the other.

OP in issue #170 has a similar issue where daibutsu didn't work but EtasonJB did
