### ISSUE TITLE
iPhone 5s select iOS version

### ISSUE THREAD

**Issue by nagydomi** [LukeZGD/iOS-OTA-Downgrader#179]
cannot select iOS 10.3.3, the only option given is 8.4.1, which oc cannot be restored.
thanks for help.

[Log] Running on platform: macos (12.4) 
[Log] Checking Internet connection... 
[Log] Finding device in Normal mode... 
[Log] iPhone6,2 (iOS 12.5.5) connected in Normal mode. 
[Log] ECID: 6663840117040 
*** Main Menu *** 
[Input] Select an option: 
1) Downgrade Device	      3) (Re-)Install Dependencies
2) Save OTA Blobs	      4) (Any other key to exit)
#? 1

[Input] Select iOS version: 
1) iOS 8.4.1		    3) (Any other key to exit)
2) Other (use SHSH blobs)

**Comment by LukeZGD** [comment]
Thanks for reporting the issue, looks like I had the if conditions in the wrong order. It should be fixed now
