### ISSUE TITLE
Can’t activate phone after downgrade

### ISSUE THREAD

**Issue by Laughogram** [LukeZGD/iOS-OTA-Downgrader#180]
The phone fails to activate after downgrade to iOS 6 without jailbreak. Anything you could do about this? I would appreciate any help.
![image](https://user-images.githubusercontent.com/100899838/171319250-6f0f8099-7c10-4181-a1ba-1b9204d95c2a.jpg)

**Comment by LukeZGD** [comment]
I need more details, like the full log of the downgrade process

**Comment by LukeZGD** [comment]
Please give more details about this issue, like providing the FULL log of the downgrade process

**Comment by LukeZGD** [comment]
You may try [this process of clearing NVRAM](https://github.com/LukeZGD/iOS-OTA-Downgrader/wiki/Troubleshooting/_edit#clearing-nvram). You may also read other sections of the "Troubleshooting" wiki page as it can be very helpful

**Comment by LukeZGD** [comment]
You may try [this process of clearing NVRAM](https://github.com/LukeZGD/iOS-OTA-Downgrader/wiki/Troubleshooting/_edit#clearing-nvram). You may also read other sections of the "Troubleshooting" wiki page as it can be very helpful

**Comment by JustAnEdiot** [comment]
I'm having the exact same issue even down to the "Searching..." where a "No SIM" message should be. 

I've tried resetting nvram, but it seemed  to not make a difference.

I'm sorry I can't provide a log, but I'm not entirely sure how I would get a log. 

I'm honestly thinking of bypassing/deleting Setup.app entirely, but I'm not completely sure on how I would do that either.

(A photo of the same error)
![image](https://user-images.githubusercontent.com/102286635/172193772-b9f2986d-1fb5-4d40-966d-483bbdce3451.jpeg)

(That same error but through iTunes)
![image](https://user-images.githubusercontent.com/102286635/172194020-c63d1c71-46f6-4872-b624-48cbf5a7677d.jpeg)

**Comment by LukeZGD** [comment]
What platform are you using iOS-OTA-Downgrader on? If using Windows, I recommend using it on Linux/macOS instead. As mentioned in the readme, usage on Windows is not recommended.

**Comment by JustAnEdiot** [comment]
I'm using Arco B linux (basically just arch with built in awesomewm and xfce apps)

**Comment by LukeZGD** [comment]
You can get the log in xfce4-terminal by right-clicking the Terminal window then Save Contents. On Konsole, I press Ctrl+Shift+S to save the output

Make sure to capture the entire log including the IPSW creation process and futurerestore. To do this, you have to delete the existing custom IPSW and try again from the beginning

**Comment by JustAnEdiot** [comment]
I have returned with a log file!

https://pastebin.com/Vks3fVWc
(The Password is "iPhone4S")

Hopefully that is enough information to help you!

Also I've done some digging and it could be related to the IMEI or the Antenna, and when I press the "i" info button on the lockscreen of the setup it doesn't give me any information at all.
