### ISSUE TITLE
Still can't activate phone

### ISSUE THREAD

**Issue by Laughogram** [LukeZGD/iOS-OTA-Downgrader#181]
Even after clearing the NVRAM The phone still fails to activate after downgrading to iOS 6. I have the log this time so maybe that will help
[Log.txt](https://github.com/LukeZGD/iOS-OTA-Downgrader/files/8819201/Log.txt)

**Comment by LukeZGD** [comment]
That rules out the NVRAM issue then. You can try to delete the custom IPSW and try again from the beginning, this time capture the entire log including the IPSW creation process and futurerestore. That may provide enough information in case

Or it might just be a connection problem to Apple activation servers, so you might want to try using another Internet connection first

**Comment by Laughogram** [comment]
I tried 3utools on a different iPhone 4s and it worked, I’ll try it with the white one and let you know what happens.
