### ISSUE TITLE
chmod: невозможно получить доступ к './resources/libimobiledevice_win/*': No such file or directory

### ISSUE THREAD

**Issue by SwellLobster338** [LukeZGD/iOS-OTA-Downgrader#183]
the file './resources/libimobiledevice_win/*' was not found
![image](https://user-images.githubusercontent.com/77489285/172659254-8f57d578-47c7-44a5-8cab-4e8e844164a9.png)
. It's not in the program folder

**Comment by SwellLobster338** [comment]
![image](https://user-images.githubusercontent.com/77489285/172659321-9c560d64-ba13-4265-ba17-3ec17982a1ec.png)

**Comment by LukeZGD** [comment]
It's likely having problems with Cyrillic characters on the folder path

Try moving it on a root directory (for example C:\ or D:\) then try again

**Comment by JustAnEdiot** [comment]
Hey again!
I'm having the same exact issue as this

**Comment by SwellLobster338** [comment]
> It's likely having problems with Cyrillic characters on the folder path
> 
> Try moving it on a root directory (for example C:\ or D:) then try again

![image](https://user-images.githubusercontent.com/77489285/172663923-13e01830-144c-478a-b531-5db5b56f5265.png)
I moved to C:\

**Comment by LukeZGD** [comment]
Ah sorry about that, I see a problem in the script, I'll be updating it in a bit

**Comment by SwellLobster338** [comment]
> Ah sorry about that, I see a problem in the script, I'll be updating it in a bit

okay, thanks for answer

**Comment by LukeZGD** [comment]
Should now be fixed at 91fee95, please test

**Comment by SwellLobster338** [comment]
![image](https://user-images.githubusercontent.com/77489285/172667509-1c14befe-fbc9-4742-b710-d474478227b8.png)
it works!) thank you
