### ISSUE TITLE
Restoring to 4.x on A5 fails with "unable to read ticket"

### ISSUE THREAD

**Issue by eatingurtoes** [LukeZGD/iOS-OTA-Downgrader#186]
On iPad 2 with saved iOS 4.3.3 blobs, the restore fails on "unable to read ticket."

**Comment by LukeZGD** [comment]
Restoring with SHSH blobs (futurerestore) supports iOS 5 and newer only

**Comment by eatingurtoes** [comment]
How come? I currently have no way to go to 4.3.3.. seems like it should work for 4.x unless it's something with the APTicket. Could you point me in the direction of utilizing dumped 4.3.3 blobs?

**Comment by LukeZGD** [comment]
I'm not sure on the details, but the restore process on iOS 4 and below is a bit different from iOS 5 and newer (iOS 4 doesn't have iBEC)

As for using the blobs, you can try using idevicerestore. 

- Get idevicerestore from `resources/tools` of iOS-OTA-Downgrader
- Name your blob to `(ECID)-(ProductType)-(Version).shsh` (example: `123123123123-iPad2,1-4.3.3.shsh`)
- Place the blob in a folder named `shsh`
- Run `./idevicerestore -ey (IPSW firmware).ipsw` (add `sudo` on Linux)

You can check this [part of the script](https://github.com/LukeZGD/iOS-OTA-Downgrader/blob/cdff02e852b395f1fa6ae78373d1da13ce29c182/resources/downgrade.sh#L164) that uses idevicerestore

**Comment by eatingurtoes** [comment]
Thank you! Will try
