### ISSUE TITLE
Can't download some dependencies

### ISSUE THREAD

**Issue by BakaMamizou** [LukeZGD/iOS-OTA-Downgrader#192]
try to run the script again and again, still can't download
Here's  some output

[Log] Found device in DFU mode.
[Log] Downloading bin.tar...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:00:19 --:--:--     0
curl: (56) OpenSSL SSL_read: Connection reset by peer, errno 104
shasum: bin.tar: No such file or directory

[Error] Verifying bin.tar failed. The downloaded file may be corrupted or incomplete. Please run the script again
* SHA1sum mismatch. Expected 98034227c68610f4c7dd48ca9e622314a1e649e7, got

[Input] Press Enter/Return to exit.

**Comment by LukeZGD** [comment]
What OS/distro?

**Comment by LukeZGD** [comment]
This is most likely just a network issue on your end, not much I can do about it

If on Linux, try using another distro. If on macOS, maybe try updating to a later version or something
