### ISSUE TITLE
Error:AppleImage3NORAccess returned an error when writing image3 object

### ISSUE THREAD

**Issue by piaomiaoguhong10** [LukeZGD/iOS-OTA-Downgrader#193]
[Uploading error.txt…]()

I restore iPad Mini 1st Gen with saved shsh, but failed with error, please take a look at it, thanks.

**Comment by piaomiaoguhong10** [comment]
[](url
[error.txt](https://github.com/LukeZGD/iOS-OTA-Downgrader/files/9078497/error.txt)
)

**Comment by LukeZGD** [comment]
You may try again with the latest ba25391

**Comment by piaomiaoguhong10** [comment]
![Screenshot 2022-07-10 at 6 08 05 PM](https://user-images.githubusercontent.com/3627382/178140493-5e53d951-5c2f-40c7-b5fe-45c8b5305759.png)
try again with the latest, still failed with same error. I ever replaced 16g flash with 64g flash on this ipad, but I can update it to ios9.3.5 without any error. Is it related with this error?

**Comment by LukeZGD** [comment]
Yeah figures, it's a pretty unusual futurerestore error. I don't know much about this one, sorry

What I can suggest to try is to use an [older version futurerestore](http://api.tihmstar.net/builds/futurerestore/futurerestore-latest.zip) and use it manually on command line, but I'm also not sure if this will work: `./futurerestore_macos -t blob.shsh2 --no-baseband firmware.ipsw`

You can get the 8.4.1 shsh blob at the `saved` folder
