### ISSUE TITLE
"No signing tickets" on iPhone5,2

### ISSUE THREAD

**Issue by StudioNorth13** [LukeZGD/iOS-OTA-Downgrader#196]
### Terminal output:
******* iOS-OTA-Downgrader *******
 - Downgrader script by LukeZGD -

[Log] Running on platform: win (
Microsoft Windows [Version 10.0.19044.1288])
[Log] Checking Internet connection...
[Log] Finding device in Normal mode...
[Log] iPhone5,2 (iOS 10.3.3) connected in Normal mode.
[Log] ECID: 3031644909042
*** Main Menu ***
[Input] Select an option:
1) Downgrade Device           4) Put Device in kDFU Mode
2) Save OTA Blobs             5) (Re-)Install Dependencies
3) Create Custom IPSW         6) (Any other key to exit)
#? 1

[Input] Select iOS version:
1) iOS 8.4.1
2) (Any other key to exit)
#? 1
[Log] Select your options when asked. If unsure, go for the defaults (press Enter/Return).

[Input] Jailbreak Option
* When this option is enabled, your device will be jailbroken on restore.
* This option is enabled by default (Y).
[Input] Enable this option? (Y/n): n
[Log] Jailbreak option disabled by user.

[Log] Found existing saved 8.4.1 blobs.
[Log] Verifying iPhone5,2_8.4.1_12H321_Restore.ipsw...
[Log] Expected SHA1sum: da4e50bf721d91bbd0b4a90ba9df9cdf2e8b9f53
[Log] Actual SHA1sum:   da4e50bf721d91bbd0b4a90ba9df9cdf2e8b9f53
[Log] IPSW SHA1sum matches.
[Log] Extracting iBSS from IPSW...
Archive:  iPhone5,2_8.4.1_12H321_Restore.ipsw
  inflating: saved/iPhone5,2/iBSS.n42.RELEASE.dfu
[Log] Patching iBSS...
[Log] Running iproxy for SSH...

[Log] Copying stuff to device via SSH...
* Make sure OpenSSH/Dropbear is installed on the device and running!
* Dropbear is only needed for devices on iOS 10
* To make sure that SSH is successful, try these steps:
* Reinstall OpenSSH/Dropbear, reboot and rejailbreak, then reinstall them again

[Input] Enter the root password of your iOS device when prompted.
* Note that you will be prompted twice. Do not worry that your input is not visible, it is still being entered.
* The default password is "alpine"
Warning: Permanently added '[127.0.0.1]:2222' (RSA) to the list of known hosts.
root@127.0.0.1's password:
kloader_hgsp                                  100%   52KB   4.1MB/s   00:00
pwnediBSS                                     100%   76KB   6.2MB/s   00:00
[Log] Entering kDFU mode...
* Press TOP or HOME button when the device disconnects and its screen goes black
* You may also try to unplug and replug your device
[Log] Finding device in DFU mode...
Warning: Permanently added '[127.0.0.1]:2222' (RSA) to the list of known hosts.
root@127.0.0.1's password:
Connection to 127.0.0.1 closed by remote host.
[Log] Found device in DFU mode.
[Log] Preparing custom IPSW...
Hashing IPSW...
Matching IPSW in FirmwareBundles/... (da4e50bf...)
checking: FirmwareBundles//Down_iPad2,1_6.1.3_10B329.bundle/Info.plist
checking: FirmwareBundles//Down_iPad2,1_8.4.1_12H321.bundle/Info.plist
checking: FirmwareBundles//Down_iPad2,2_6.1.3_10B329.bundle/Info.plist
checking: FirmwareBundles//Down_iPad2,2_8.4.1_12H321.bundle/Info.plist
checking: FirmwareBundles//Down_iPad2,3_6.1.3_10B329.bundle/Info.plist
checking: FirmwareBundles//Down_iPad2,3_8.4.1_12H321.bundle/Info.plist
checking: FirmwareBundles//Down_iPad2,4_8.4.1_12H321.bundle/Info.plist
checking: FirmwareBundles//Down_iPad2,5_8.4.1_12H321.bundle/Info.plist
checking: FirmwareBundles//Down_iPad2,6_8.4.1_12H321.bundle/Info.plist
checking: FirmwareBundles//Down_iPad2,7_8.4.1_12H321.bundle/Info.plist
checking: FirmwareBundles//Down_iPad3,1_8.4.1_12H321.bundle/Info.plist
checking: FirmwareBundles//Down_iPad3,2_8.4.1_12H321.bundle/Info.plist
checking: FirmwareBundles//Down_iPad3,3_8.4.1_12H321.bundle/Info.plist
checking: FirmwareBundles//Down_iPad3,4_8.4.1_12H321.bundle/Info.plist
checking: FirmwareBundles//Down_iPad3,5_8.4.1_12H321.bundle/Info.plist
checking: FirmwareBundles//Down_iPad3,6_8.4.1_12H321.bundle/Info.plist
checking: FirmwareBundles//Down_iPhone4,1_6.1.3_10B329.bundle/Info.plist
checking: FirmwareBundles//Down_iPhone4,1_8.4.1_12H321.bundle/Info.plist
checking: FirmwareBundles//Down_iPhone5,1_8.4.1_12H321.bundle/Info.plist
checking: FirmwareBundles//Down_iPhone5,2_8.4.1_12H321.bundle/Info.plist
loading: 058-23947-023.dmg (16535820)
loading: 058-24024-023.dmg (17334540)
loading: 058-24110-023.dmg (1592536064)
loading: BuildManifest.plist (83310)
loading: Firmware/ (0)
loading: Firmware/all_flash/ (0)
loading: Firmware/all_flash/all_flash.n42ap.production/ (0)
loading: Firmware/all_flash/all_flash.n42ap.production/applelogo@2x~iphone.s5l8950x.img3 (6796)
loading: Firmware/all_flash/all_flash.n42ap.production/batterycharging0@2x~iphone.s5l8950x.img3 (9740)
loading: Firmware/all_flash/all_flash.n42ap.production/batterycharging1@2x~iphone.s5l8950x.img3 (35020)
loading: Firmware/all_flash/all_flash.n42ap.production/batteryfull@2x~iphone.s5l8950x.img3 (84044)
loading: Firmware/all_flash/all_flash.n42ap.production/batterylow0@2x~iphone.s5l8950x.img3 (43596)
loading: Firmware/all_flash/all_flash.n42ap.production/batterylow1@2x~iphone.s5l8950x.img3 (2060)
loading: Firmware/all_flash/all_flash.n42ap.production/DeviceTree.n42ap.img3 (88524)
loading: Firmware/all_flash/all_flash.n42ap.production/glyphplugin@1136~iphone-lightning.s5l8950x.img3 (3980)
loading: Firmware/all_flash/all_flash.n42ap.production/iBoot.n42.RELEASE.img3 (287116)
loading: Firmware/all_flash/all_flash.n42ap.production/LLB.n42.RELEASE.img3 (151948)
loading: Firmware/all_flash/all_flash.n42ap.production/manifest (387)
loading: Firmware/all_flash/all_flash.n42ap.production/recoverymode@1136~iphone-lightning.s5l8950x.img3 (74060)
loading: Firmware/dfu/ (0)
loading: Firmware/dfu/iBEC.n42.RELEASE.dfu (287116)
loading: Firmware/dfu/iBSS.n42.RELEASE.dfu (78220)
loading: Firmware/Mav5-8.02.00.Release.bbfw (19225909)
loading: Firmware/Mav5-8.02.00.Release.plist (744)
loading: Firmware/usr/ (0)
loading: Firmware/usr/local/ (0)
loading: Firmware/usr/local/standalone/ (0)
loading: kernelcache.release.n42 (9415692)
loading: Restore.plist (2286)
Restore Ramdisk: /home/lukee/xpwn/ipsw-patch/img3.c:createAbstractFileFromImg3:643: 98153539961328495cbaf32034d2c58bbea83308e14a81a5c5925c4b57273a7201d9220ca782808db7df654a86ac01ff
/home/lukee/xpwn/ipsw-patch/img3.c:createAbstractFileFromImg3:643: 98153539961328495cbaf32034d2c58bbea83308e14a81a5c5925c4b57273a7201d9220ca782808db7df654a86ac01ff
/home/lukee/xpwn/ipsw-patch/img3.c:createAbstractFileFromImg3:643: 98153539961328495cbaf32034d2c58bbea83308e14a81a5c5925c4b57273a7201d9220ca782808db7df654a86ac01ff
writing... success
iBSS: Firmware/dfu/iBSS.n42.RELEASE.dfu (FirmwareBundles//Down_iPhone5,2_8.4.1_12H321.bundle/iBSS.n42.RELEASE.patch)... encrypted input... /home/lukee/xpwn/ipsw-patch/img3.c:createAbstractFileFromImg3:643: 997ef353c128ea273399bd25c12d2d61608c1226b5457bd39821ab38d41cecfbda216fcac181f1207fbf76823a125a10
/home/lukee/xpwn/ipsw-patch/img3.c:createAbstractFileFromImg3:643: 997ef353c128ea273399bd25c12d2d61608c1226b5457bd39821ab38d41cecfbda216fcac181f1207fbf76823a125a10
encrypted output... /home/lukee/xpwn/ipsw-patch/img3.c:createAbstractFileFromImg3:643: 997ef353c128ea273399bd25c12d2d61608c1226b5457bd39821ab38d41cecfbda216fcac181f1207fbf76823a125a10
writing... success
iBSS: /home/lukee/xpwn/ipsw-patch/img3.c:createAbstractFileFromImg3:643: 997ef353c128ea273399bd25c12d2d61608c1226b5457bd39821ab38d41cecfbda216fcac181f1207fbf76823a125a10
/home/lukee/xpwn/ipsw-patch/img3.c:createAbstractFileFromImg3:643: 997ef353c128ea273399bd25c12d2d61608c1226b5457bd39821ab38d41cecfbda216fcac181f1207fbf76823a125a10
/home/lukee/xpwn/ipsw-patch/img3.c:createAbstractFileFromImg3:643: 997ef353c128ea273399bd25c12d2d61608c1226b5457bd39821ab38d41cecfbda216fcac181f1207fbf76823a125a10
writing... success
iBEC: Firmware/dfu/iBEC.n42.RELEASE.dfu (FirmwareBundles//Down_iPhone5,2_8.4.1_12H321.bundle/iBEC.n42.RELEASE.patch)... encrypted input... /home/lukee/xpwn/ipsw-patch/img3.c:createAbstractFileFromImg3:643: ba72b6fb5c5d068d103455b25aebcb125d0ceefe85fb3483f97c0cf0b584774a249613176fe25c1884478d8d1b20d92f
/home/lukee/xpwn/ipsw-patch/img3.c:createAbstractFileFromImg3:643: ba72b6fb5c5d068d103455b25aebcb125d0ceefe85fb3483f97c0cf0b584774a249613176fe25c1884478d8d1b20d92f
encrypted output... /home/lukee/xpwn/ipsw-patch/img3.c:createAbstractFileFromImg3:643: ba72b6fb5c5d068d103455b25aebcb125d0ceefe85fb3483f97c0cf0b584774a249613176fe25c1884478d8d1b20d92f
writing... success
iBEC: /home/lukee/xpwn/ipsw-patch/img3.c:createAbstractFileFromImg3:643: ba72b6fb5c5d068d103455b25aebcb125d0ceefe85fb3483f97c0cf0b584774a249613176fe25c1884478d8d1b20d92f
/home/lukee/xpwn/ipsw-patch/img3.c:createAbstractFileFromImg3:643: ba72b6fb5c5d068d103455b25aebcb125d0ceefe85fb3483f97c0cf0b584774a249613176fe25c1884478d8d1b20d92f
/home/lukee/xpwn/ipsw-patch/img3.c:createAbstractFileFromImg3:643: ba72b6fb5c5d068d103455b25aebcb125d0ceefe85fb3483f97c0cf0b584774a249613176fe25c1884478d8d1b20d92f
writing... success
RestoreDeviceTree: /home/lukee/xpwn/ipsw-patch/img3.c:createAbstractFileFromImg3:643: 4f542e8bd12274fd69b7da5e593f7f024d4cd1ca51a47b2fa2de7d8fd69ce72f78277ce422afb4215650c35ec27ea7c1
/home/lukee/xpwn/ipsw-patch/img3.c:createAbstractFileFromImg3:643: 4f542e8bd12274fd69b7da5e593f7f024d4cd1ca51a47b2fa2de7d8fd69ce72f78277ce422afb4215650c35ec27ea7c1
/home/lukee/xpwn/ipsw-patch/img3.c:createAbstractFileFromImg3:643: 4f542e8bd12274fd69b7da5e593f7f024d4cd1ca51a47b2fa2de7d8fd69ce72f78277ce422afb4215650c35ec27ea7c1
writing... success
RestoreLogo: /home/lukee/xpwn/ipsw-patch/img3.c:createAbstractFileFromImg3:643: 445fc096153af34a39d235cce433b8fc0799df966621c056cc923a63aa08e5f7df094b4147c464dd746a1af8180353ea
/home/lukee/xpwn/ipsw-patch/img3.c:createAbstractFileFromImg3:643: 445fc096153af34a39d235cce433b8fc0799df966621c056cc923a63aa08e5f7df094b4147c464dd746a1af8180353ea
/home/lukee/xpwn/ipsw-patch/img3.c:createAbstractFileFromImg3:643: 445fc096153af34a39d235cce433b8fc0799df966621c056cc923a63aa08e5f7df094b4147c464dd746a1af8180353ea
writing... success
RestoreKernelCache: /home/lukee/xpwn/ipsw-patch/img3.c:createAbstractFileFromImg3:643: 12d19891a9fc39018fe76ac11ce218127df30bdea042adcf0b1f2add4f99791d3945f93e8585afe7286bffcf09fded83
/home/lukee/xpwn/ipsw-patch/img3.c:createAbstractFileFromImg3:643: 12d19891a9fc39018fe76ac11ce218127df30bdea042adcf0b1f2add4f99791d3945f93e8585afe7286bffcf09fded83
/home/lukee/xpwn/ipsw-patch/img3.c:createAbstractFileFromImg3:643: 12d19891a9fc39018fe76ac11ce218127df30bdea042adcf0b1f2add4f99791d3945f93e8585afe7286bffcf09fded83
writing... success
replacing key=UniqueBuildID
+ key=Manifest
+ key=RestoreRamDisk
replacing key=Digest
- key=RestoreRamDisk
- key=Manifest

replacing key=UniqueBuildID
+ key=Manifest
+ key=RestoreRamDisk
replacing key=Digest
- key=RestoreRamDisk
- key=Manifest

/home/lukee/xpwn/ipsw-patch/main.c:main:530: using filesystem backed temporary storage
Writing out data..
run 0: start=0 sectors=512, length=14122, fileOffset=0x132
run 100: start=26214400 sectors=512, length=209914, fileOffset=0xa59ddc
run 200: start=52428800 sectors=512, length=193710, fileOffset=0x1d80254
run 300: start=78643200 sectors=312, length=140423, fileOffset=0x25dea10
run 400: start=107618304 sectors=512, length=262144, fileOffset=0x34f5e95
run 500: start=133832704 sectors=512, length=205303, fileOffset=0x4b45afc
run 600: start=160047104 sectors=512, length=262144, fileOffset=0x558238e
run 700: start=186261504 sectors=512, length=1888, fileOffset=0x6bc8acd
run 800: start=212475904 sectors=512, length=204009, fileOffset=0x81f69c1
run 900: start=238690304 sectors=512, length=250699, fileOffset=0x97f1dc8
run 1000: start=264904704 sectors=512, length=29189, fileOffset=0xac5b419
run 1100: start=291119104 sectors=512, length=262144, fileOffset=0xc253546
run 1200: start=317333504 sectors=512, length=262144, fileOffset=0xdb2c777
run 1300: start=343547904 sectors=512, length=29273, fileOffset=0xf313164
run 1400: start=369762304 sectors=512, length=262144, fileOffset=0x10b894bc
run 1500: start=395976704 sectors=512, length=194346, fileOffset=0x123b02e7
run 1600: start=422191104 sectors=512, length=190845, fileOffset=0x13530f64
run 1700: start=448405504 sectors=512, length=180689, fileOffset=0x1468a6ad
run 1800: start=474619904 sectors=512, length=153646, fileOffset=0x156ce38c
run 1900: start=500834304 sectors=512, length=180789, fileOffset=0x1679d3ba
run 2000: start=527048704 sectors=512, length=179427, fileOffset=0x179875a4
run 2100: start=553263104 sectors=512, length=249327, fileOffset=0x18caff76
run 2200: start=579477504 sectors=512, length=239318, fileOffset=0x1a472420
run 2300: start=605691904 sectors=512, length=262144, fileOffset=0x1bc717d3
run 2400: start=631906304 sectors=512, length=83526, fileOffset=0x1c846d20
run 2500: start=658120704 sectors=512, length=262144, fileOffset=0x1dfd1599
run 2600: start=684335104 sectors=512, length=262144, fileOffset=0x1f33d175
run 2700: start=710549504 sectors=512, length=248104, fileOffset=0x20a8dcc6
run 2800: start=736763904 sectors=512, length=262144, fileOffset=0x222f631c
run 2900: start=762978304 sectors=512, length=250882, fileOffset=0x23a4eddf
run 3000: start=789192704 sectors=512, length=237990, fileOffset=0x2514cbd3
run 3100: start=815407104 sectors=512, length=262144, fileOffset=0x26769c43
run 3200: start=841621504 sectors=512, length=241965, fileOffset=0x279d8d81
run 3300: start=867835904 sectors=512, length=195314, fileOffset=0x290922d9
run 3400: start=894050304 sectors=512, length=262144, fileOffset=0x2a5de74c
run 3500: start=920264704 sectors=512, length=262144, fileOffset=0x2bea8377
run 3600: start=946479104 sectors=512, length=190665, fileOffset=0x2d584254
run 3700: start=972693504 sectors=512, length=185926, fileOffset=0x2e508182
run 3800: start=998907904 sectors=512, length=184486, fileOffset=0x2f50d0a9
run 3900: start=1025122304 sectors=512, length=179018, fileOffset=0x3065f7e4
run 4000: start=1051336704 sectors=512, length=216490, fileOffset=0x31a9f84f
run 4100: start=1077551104 sectors=512, length=225679, fileOffset=0x32e93664
run 4200: start=1103765504 sectors=512, length=262144, fileOffset=0x34394687
run 4300: start=1129979904 sectors=512, length=26055, fileOffset=0x3567ffeb
run 4400: start=1156194304 sectors=512, length=232453, fileOffset=0x36c59111
run 4500: start=1182408704 sectors=512, length=166699, fileOffset=0x37d0b9d8
run 4600: start=1208623104 sectors=512, length=133243, fileOffset=0x3883e289
run 4700: start=1234837504 sectors=512, length=262144, fileOffset=0x3999dc7a
run 4800: start=1261051904 sectors=512, length=217508, fileOffset=0x3b040560
run 4900: start=1287266304 sectors=512, length=262144, fileOffset=0x3c8ed1a2
run 5000: start=1313480704 sectors=512, length=252988, fileOffset=0x3de26674
run 5100: start=1339695104 sectors=512, length=262144, fileOffset=0x3f561a80
run 5200: start=1365909504 sectors=512, length=262144, fileOffset=0x40e61a80
run 5300: start=1392123904 sectors=512, length=262144, fileOffset=0x42757323
run 5400: start=1418338304 sectors=512, length=262144, fileOffset=0x43f57906
run 5500: start=1444552704 sectors=512, length=251734, fileOffset=0x456b1efa
run 5600: start=1470767104 sectors=512, length=231657, fileOffset=0x4699b452
run 5700: start=1496981504 sectors=512, length=212184, fileOffset=0x47baa6fc
run 5800: start=1523195904 sectors=512, length=262144, fileOffset=0x49440e6a
run 5900: start=1549410304 sectors=512, length=262144, fileOffset=0x4ac1b63c
run 6000: start=1575624704 sectors=512, length=152243, fileOffset=0x4beae42c
run 6100: start=1601839104 sectors=512, length=176623, fileOffset=0x4cca94b1
run 6200: start=1628053504 sectors=512, length=239039, fileOffset=0x4dd36def
run 6300: start=1654267904 sectors=512, length=213489, fileOffset=0x4f07af6e
run 6400: start=1680482304 sectors=512, length=115072, fileOffset=0x50138247
run 6500: start=1706696704 sectors=512, length=262144, fileOffset=0x5156abe4
run 6600: start=1732911104 sectors=512, length=247686, fileOffset=0x5297f89c
run 6700: start=1759125504 sectors=512, length=138074, fileOffset=0x53f642f3
run 6800: start=1785339904 sectors=512, length=109550, fileOffset=0x54dbdb80
run 6900: start=1811554304 sectors=512, length=137969, fileOffset=0x55da4021
run 7000: start=1837768704 sectors=512, length=145493, fileOffset=0x56afc85d
run 7100: start=1863983104 sectors=512, length=144407, fileOffset=0x57869d29
run 7200: start=1890197504 sectors=512, length=151055, fileOffset=0x5874e114
run 7300: start=1916411904 sectors=512, length=144152, fileOffset=0x5945b0d8
run 7400: start=1942626304 sectors=512, length=156929, fileOffset=0x5a13a219
run 7500: start=1968840704 sectors=512, length=186185, fileOffset=0x5ad3b646
run 7600: start=1995055104 sectors=512, length=89911, fileOffset=0x5b9ed4c9
run 7700: start=2021269504 sectors=512, length=85550, fileOffset=0x5c6a3d3f
run 7800: start=2047483904 sectors=512, length=1167, fileOffset=0x5d0c392a
run 7900: start=2073698304 sectors=512, length=74270, fileOffset=0x5d9676d5
run 8000: start=2099912704 sectors=512, length=54274, fileOffset=0x5e0a96ea
run 8100: start=2126127104 sectors=512, length=50455, fileOffset=0x5e81d053
run 8200: start=2152341504 sectors=512, length=58298, fileOffset=0x5ecfbc97
Growing root to minimum: 2058
Cannot shrink volume
unencrypted ramdisk
growing ramdisk: 16535552 -> 16535552
Cannot shrink volume
patching usr/sbin/asr (FirmwareBundles//Down_iPhone5,2_8.4.1_12H321.bundle/asr.patch)... retrieving...patching...writing... success
got /usr/local/share/restore/options.n42.plist from ramdisk
start create restore options
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
        <key>SystemPartitionPadding</key>
        <dict>
                <key>1024</key>
                <integer>1280</integer>
                <key>128</key>
                <integer>1280</integer>
                <key>16</key>
                <integer>260</integer>
                <key>256</key>
                <integer>1280</integer>
                <key>32</key>
                <integer>320</integer>
                <key>512</key>
                <integer>1280</integer>
                <key>64</key>
                <integer>640</integer>
                <key>768</key>
                <integer>1280</integer>
                <key>8</key>
                <integer>180</integer>
        </dict>
        <key>MinimumSystemPartition</key>
        <integer>2058</integer>
        <key>CreateFilesystemPartitions</key>
        <true/>
        <key>SystemPartitionSize</key>
        <integer>2058</integer>
        <key>UpdateBaseband</key>
        <false/>
</dict>
</plist>
Creating and writing DDM and partition map...
run 0: sectors=1, left=1
run 0: sectors=60, left=60
malloc: 0x800068880 4096
run 0: sectors=4, left=4
Writing main data blkx...
run 100: sectors=512, left=4165912
run 200: sectors=512, left=4114712
run 300: sectors=512, left=4063512
run 400: sectors=512, left=4012312
run 500: sectors=512, left=3961112
run 600: sectors=512, left=3909912
run 700: sectors=512, left=3858712
run 800: sectors=512, left=3807512
run 900: sectors=512, left=3756312
run 1000: sectors=512, left=3705112
run 1100: sectors=512, left=3653912
run 1200: sectors=512, left=3602712
run 1300: sectors=512, left=3551512
run 1400: sectors=512, left=3500312
run 1500: sectors=512, left=3449112
run 1600: sectors=512, left=3397912
run 1700: sectors=512, left=3346712
run 1800: sectors=512, left=3295512
run 1900: sectors=512, left=3244312
run 2000: sectors=512, left=3193112
run 2100: sectors=512, left=3141912
run 2200: sectors=512, left=3090712
run 2300: sectors=512, left=3039512
run 2400: sectors=512, left=2988312
run 2500: sectors=512, left=2937112
run 2600: sectors=512, left=2885912
run 2700: sectors=512, left=2834712
run 2800: sectors=512, left=2783512
run 2900: sectors=512, left=2732312
run 3000: sectors=512, left=2681112
run 3100: sectors=512, left=2629912
run 3200: sectors=512, left=2578712
run 3300: sectors=512, left=2527512
run 3400: sectors=512, left=2476312
run 3500: sectors=512, left=2425112
run 3600: sectors=512, left=2373912
run 3700: sectors=512, left=2322712
run 3800: sectors=512, left=2271512
run 3900: sectors=512, left=2220312
run 4000: sectors=512, left=2169112
run 4100: sectors=512, left=2117912
run 4200: sectors=512, left=2066712
run 4300: sectors=512, left=2015512
run 4400: sectors=512, left=1964312
run 4500: sectors=512, left=1913112
run 4600: sectors=512, left=1861912
run 4700: sectors=512, left=1810712
run 4800: sectors=512, left=1759512
run 4900: sectors=512, left=1708312
run 5000: sectors=512, left=1657112
run 5100: sectors=512, left=1605912
run 5200: sectors=512, left=1554712
run 5300: sectors=512, left=1503512
run 5400: sectors=512, left=1452312
run 5500: sectors=512, left=1401112
run 5600: sectors=512, left=1349912
run 5700: sectors=512, left=1298712
run 5800: sectors=512, left=1247512
run 5900: sectors=512, left=1196312
run 6000: sectors=512, left=1145112
run 6100: sectors=512, left=1093912
run 6200: sectors=512, left=1042712
run 6300: sectors=512, left=991512
run 6400: sectors=512, left=940312
run 6500: sectors=512, left=889112
run 6600: sectors=512, left=837912
run 6700: sectors=512, left=786712
run 6800: sectors=512, left=735512
run 6900: sectors=512, left=684312
run 7000: sectors=512, left=633112
run 7100: sectors=512, left=581912
run 7200: sectors=512, left=530712
run 7300: sectors=512, left=479512
run 7400: sectors=512, left=428312
run 7500: sectors=512, left=377112
run 7600: sectors=512, left=325912
run 7700: sectors=512, left=274712
run 7800: sectors=512, left=223512
run 7900: sectors=512, left=172312
run 8000: sectors=512, left=121112
run 8100: sectors=512, left=69912
run 8200: sectors=512, left=18712
Inserting main blkx...
Inserting cSum data...
Inserting nsiz data
Writing free partition...
Writing XML data...
making size data
we know to flip this size resource
Generating UDIF metadata...
Master checksum: 44138dfe
Writing out UDIF resource file...
Cleaning up...
Done.
packing: 058-23947-023.dmg (16535644)
packing: 058-24024-023.dmg (17334540)
packing: 058-24110-023.dmg (1592536064)
packing: BuildManifest.plist (83310)
packing: Downgrade/ (0)
packing: Downgrade/DeviceTree.n42ap.img3 (88368)
packing: Downgrade/applelogo@2x~iphone.s5l8950x.img3 (6632)
packing: Downgrade/kernelcache.release.n42 (9415484)
packing: Firmware/ (0)
packing: Firmware/Mav5-8.02.00.Release.bbfw (19225909)
packing: Firmware/Mav5-8.02.00.Release.plist (744)
packing: Firmware/all_flash/ (0)
packing: Firmware/all_flash/all_flash.n42ap.production/ (0)
packing: Firmware/all_flash/all_flash.n42ap.production/DeviceTree.n42ap.img3 (88524)
packing: Firmware/all_flash/all_flash.n42ap.production/LLB.n42.RELEASE.img3 (151948)
packing: Firmware/all_flash/all_flash.n42ap.production/applelogo@2x~iphone.s5l8950x.img3 (6796)
packing: Firmware/all_flash/all_flash.n42ap.production/batterycharging0@2x~iphone.s5l8950x.img3 (9740)
packing: Firmware/all_flash/all_flash.n42ap.production/batterycharging1@2x~iphone.s5l8950x.img3 (35020)
packing: Firmware/all_flash/all_flash.n42ap.production/batteryfull@2x~iphone.s5l8950x.img3 (84044)
packing: Firmware/all_flash/all_flash.n42ap.production/batterylow0@2x~iphone.s5l8950x.img3 (43596)
packing: Firmware/all_flash/all_flash.n42ap.production/batterylow1@2x~iphone.s5l8950x.img3 (2060)
packing: Firmware/all_flash/all_flash.n42ap.production/glyphplugin@1136~iphone-lightning.s5l8950x.img3 (3980)
packing: Firmware/all_flash/all_flash.n42ap.production/iBoot.n42.RELEASE.img3 (287116)
packing: Firmware/all_flash/all_flash.n42ap.production/manifest (387)
packing: Firmware/all_flash/all_flash.n42ap.production/recoverymode@1136~iphone-lightning.s5l8950x.img3 (74060)
packing: Firmware/dfu/ (0)
packing: Firmware/dfu/iBEC.n42.RELEASE.dfu (286940)
packing: Firmware/dfu/iBSS.n42.RELEASE.dfu (78044)
packing: Firmware/usr/ (0)
packing: Firmware/usr/local/ (0)
packing: Firmware/usr/local/standalone/ (0)
packing: Restore.plist (2286)
packing: kernelcache.release.n42 (9415692)
[Log] Setting restore IPSW to: iPhone5,2_8.4.1_12H321_CustomWin.ipsw
[Log] Extracting IPSW: iPhone5,2_8.4.1_12H321_CustomWin.ipsw
cp: missing destination file operand after 'shsh/3031644909042-iPhone5,2-8.4.1.shsh'
Try 'cp --help' for more information.
[Log] Proceeding to idevicerestore...
Found device in DFU mode
Identified device as n42ap, iPhone5,2
Extracting BuildManifest from IPSW
Product Version: 8.4.1
Product Build: 12H321 Major: 12
Device supports Image4: false
Variant: Customer Erase Install (IPSW)
This restore will erase your device data.
Checking IPSW for required components...
All required components found in IPSW
Using cached filesystem from 'iPhone5,2_8.4.1_12H321_CustomWin/058-24110-023.dmg'
Found ECID 3031644909042
Getting ApNonce in DFU mode... db bc 81 48 08 50 f2 6f 9e 71 36 6c c8 bc e9 f8 fb 02 7e e7
checking for local signing tickets
no local signing tickets file shsh/3031644909042-iPhone5,2-8.4.1.shsh
Refusing to proceed without saved ticket
ERROR: Unable to get signing tickets for this device

[Log] Restoring done! Read the message below if any error has occurred:
* Windows users may encounter errors like "Unable to send APTicket" or "Unable to send iBEC" in the restore process.
* To fix this, follow troubleshooting steps from here: https://github.com/LukeZGD/iOS-OTA-Downgrader/wiki/Troubleshooting#windows
* Please read the "Troubleshooting" wiki page in GitHub before opening any issue!
* Your problem may have already been addressed within the wiki page.
* If opening an issue in GitHub, please provide a FULL log. Otherwise, your issue may be dismissed.

[Log] Downgrade script done!

[Input] Press Enter/Return to exit.

**Comment by LukeZGD** [comment]
Please try again with the latest 9933d6e

**Comment by TheRealHyped** [comment]
Works now
