### ISSUE TITLE
Restoring to iOS 8.4.1 for iPhone4,1 does not allow device to open Cydia with daibutsu

### ISSUE THREAD

**Issue by Merculous** [LukeZGD/iOS-OTA-Downgrader#198]
I have previously downgraded to 6.1.3 without jailbreaking (later on jailbreaking with p0sixspwn anyway). I needed a tool on my device which requires iOS >=7, so I installed 8.4.1 and selected daibutsu as I wanted to try it out. After a successful restore, Cydia does show on the device, however I cannot open it. I have yet to try the etasonjb one, so I'll try that out and see if it would work.

**Comment by LukeZGD** [comment]
Yeah it's a very common issue: https://github.com/LukeZGD/iOS-OTA-Downgrader/wiki/Troubleshooting#jailbreak-option-for-32-bit-devices

I don't really have plans on fixing it (I don't know if I can), #178 and #170 are identical issues. In #170 EtasonJB worked for them
