### ISSUE TITLE
iPhone3,1 SHA1sum's don't match

### ISSUE THREAD

**Issue by CodeyMoore** [LukeZGD/iOS-OTA-Downgrader#199]
I've tried 6.1.3, 5.0.1 and 5.0. All the SHA1sum's don't match, I've tried manually changing them and that just lead to the same issue.

**Comment by LukeZGD** [comment]
Without a log or any context at all, I can't help you

BTW someone had a similar issue on Reddit. You need target version and 7.1.2 IPSWs, make sure to have both in the folder. Also I have checked all shasums and they are all verified and correct
