### ISSUE TITLE
iPhone 3,1 to iOS 6.1.3 throws error unable to send ibss to device

### ISSUE THREAD

**Issue by Cyrexiaa** [LukeZGD/iOS-OTA-Downgrader#200]
[Log] Using powdersn0w for the jailbreak
[Log] Jailbreak option enabled.

[Log] Found existing Custom IPSW. Skipping 6.1.3 IPSW verification.
[Log] Found existing saved 7.1.2 blobs: saved/shsh/635657076086-iPhone3,1-7.1.2.shsh
[Log] Found existing Custom IPSW. Skipping 7.1.2 IPSW verification.
[Log] Found existing Custom IPSW. Skipping IPSW creation.
[Log] Setting restore IPSW to: iPhone3,1_6.1.3_10B329_Custom.ipsw
[Log] Extracting IPSW: iPhone3,1_6.1.3_10B329_Custom.ipsw
[Log] Proceeding to idevicerestore...
NOTE: Updated version data.
Found device in DFU mode
Identified device as n90ap, iPhone3,1
Extracting BuildManifest from IPSW
Product Version: 6.1.3
Product Build: 10B329 Major: 10
Device supports Image4: false
Variant: Customer Erase Install (IPSW)
This restore will erase your device data.
Found ECID 635657076086
Getting ApNonce in dfu mode...
Using cached SHSH
Using cached filesystem from 'iPhone3,1_6.1.3_10B329_Custom/048-2748-005.dmg'
Extracting iBSS.n90ap.RELEASE.dfu...
Personalizing IMG3 component iBSS...
reconstructed size: 67853
Sending iBSS (67853 bytes)...
Nonce:
Using cached SHSH
Extracting iBEC.n90ap.RELEASE.dfu...
Personalizing IMG3 component iBEC...
reconstructed size: 280845
Sending iBEC (280845 bytes)...
checking for local shsh
checking for local shsh
ERROR: Unable to send iBEC component: Unable to upload data to device
ERROR: Unable to send iBEC to device
ERROR: Unable to place device into recovery mode from DFU mode

That shows up everytime, i have tried deleting it from device manager and enabling the script but nothing works.
On windows i get further than linux so thats why im using windows to downgrade

**Comment by LukeZGD** [comment]
This is why I recommend not using Windows, use iOS-OTA-Downgrader on Linux/macOS
