### ISSUE TITLE
iPhone5,2,Downgrading to841(from1034) futurerestore problem 

### ISSUE THREAD

**Issue by LiveinQE** [LukeZGD/iOS-OTA-Downgrader#202]
Hmmm... I've met a problem when I tried to back to 841(whether it is the problem of jailbreak tool?)

**Comment by LiveinQE** [comment]
Here is the log
******* iOS-OTA-Downgrader ******* 
 - Downgrader script by LukeZGD -  

Version: 7a660bd67addce9e5f06087dfb211484f35473f3 
[Log] Running on platform: linux (Ubuntu 22.04.1 LTS) 
[Log] Checking Internet connection... 
[Log] Finding device in Normal mode... 
[Log] iPhone5,2 (iOS 10.3.4) connected in Normal mode. 
[Log] ECID: 1821940561290 
*** Main Menu *** 
[Input] Select an option: 
1) Downgrade Device	      4) Put Device in kDFU Mode
2) Save OTA Blobs	      5) (Re-)Install Dependencies
3) Create Custom IPSW	      6) (Any other key to exit)
#? 1

[Input] Select iOS version: 
1) iOS 8.4.1		    3) (Any other key to exit)
2) Other (use SHSH blobs)
#? 1
[Log] Select your options when asked. If unsure, go for the defaults (press Enter/Return). 


[Input] Jailbreak Option 
* When this option is enabled, your device will be jailbroken on restore. 
* Based on some reported issues, Jailbreak Option might not work properly for iOS 8.4.1. 
* I recommend to disable the option for these devices and sideload EtasonJB, HomeDepot, or daibutsu manually. 
* This option is enabled by default (Y). 
[Input] Enable this option? (Y/n): n
[Log] Jailbreak option disabled by user. 

[Log] Found existing saved 8.4.1 blobs: saved/shsh/1821940561290_iPhone5,2_n42ap_8.4.1-12H321_3a88b7c3802f2f0510abc432104a15ebd8bd7154.shsh2 
[Log] Verifying iPhone5,2_8.4.1_12H321_Restore.ipsw... 
[Log] Expected SHA1sum: da4e50bf721d91bbd0b4a90ba9df9cdf2e8b9f53 
[Log] Actual SHA1sum:   da4e50bf721d91bbd0b4a90ba9df9cdf2e8b9f53 
[Log] IPSW SHA1sum matches. 
[Log] Extracting iBSS from IPSW... 
Archive:  iPhone5,2_8.4.1_12H321_Restore.ipsw
  inflating: saved/iPhone5,2/iBSS.n42.RELEASE.dfu  
[Log] Patching iBSS... 
[Log] Running iproxy for SSH... 
Creating listening port 2222 for device port 22
waiting for connection

[Log] Copying stuff to device via SSH... 
* Make sure OpenSSH/Dropbear is installed on the device and running! 
* Dropbear is only needed for devices on iOS 10 
* To make sure that SSH is successful, try these steps: 
* Reinstall OpenSSH/Dropbear, reboot and rejailbreak, then reinstall them again 

[Input] Enter the root password of your iOS device when prompted. 
* Note that you will be prompted twice. Do not worry that your input is not visible, it is still being entered. 
* The default password is "alpine" 
New connection for 2222->22, fd = 5
waiting for connection
Requesting connecion to USB device handle 1 (serial: 67b855a8ec8f4dc014476207c2bba1afffad6a63), port 22
Warning: Permanently added '[127.0.0.1]:2222' (RSA) to the list of known hosts.
root@127.0.0.1's password: 
kloader_hgsp                                  100%   52KB   2.2MB/s   00:00    
pwnediBSS                                     100%   76KB   1.3MB/s   00:00    
[Log] Entering kDFU mode... 
* Press TOP or HOME button when the device disconnects and its screen goes black 
* You may also try to unplug and replug your device 
[Log] Finding device in DFU mode... 
New connection for 2222->22, fd = 5
waiting for connection
Requesting connecion to USB device handle 1 (serial: 67b855a8ec8f4dc014476207c2bba1afffad6a63), port 22
Warning: Permanently added '[127.0.0.1]:2222' (RSA) to the list of known hosts.
root@127.0.0.1's password: 
Connection to 127.0.0.1 closed by remote host.
[Log] Found device in DFU mode. 
[Log] Setting restore IPSW to: iPhone5,2_8.4.1_12H321_Restore.ipsw 
[Log] Extracting IPSW: iPhone5,2_8.4.1_12H321_Restore.ipsw 
[Log] Proceeding to futurerestore... 
[Log] Running futurerestore with command: ./resources/tools/futurerestore_linux -t "saved/shsh/1821940561290_iPhone5,2_n42ap_8.4.1-12H321_3a88b7c3802f2f0510abc432104a15ebd8bd7154.shsh2" --use-pwndfu --no-ibss -b saved/baseband/Mav5-11.80.00.Release.bbfw -p saved/iPhone5,2/BuildManifest.plist "iPhone5,2_8.4.1_12H321_Restore.ipsw" 
Serving HTTP on 0.0.0.0 port 8888 ...
Version: v2.0.0-test(a58821b95f6417ad649ed7a5460337dcd82e200e-259)
img4tool version: 0.197-aca6cf005c94caf135023263cbb5c61a0081804f-RELEASE
libipatcher version: 0.86-6a3b358b673e74c2be9f9b8a74a63b80dd94abf1-RELEASE
Odysseus for 32-bit support: yes
Odysseus for 64-bit support: yes
futurerestore: failed with exception:
[exception]:
what=can't init, no device found

code=17104904
line=261
file=main.cpp
commit count=259:
commit sha  =a58821b95f6417ad649ed7a5460337dcd82e200e:

[Log] Restoring done! Read the message below if any error has occurred: 
* Please read the "Troubleshooting" wiki page in GitHub before opening any issue! 
* Your problem may have already been addressed within the wiki page. 
* If opening an issue in GitHub, please provide a FULL log. Otherwise, your issue may be dismissed. 

[Log] Downgrade script done!

**Comment by LukeZGD** [comment]
This is a bit of an unusual issue, irecovery detects your device but not futurerestore. You can try to delete `first_run` file in resources, run the script again and let the install script run to re-apply linux_fix. If that doesn't work, I can suggest trying an older Ubuntu version (20.04) or try another distro
