### ISSUE TITLE
[Error] No device detected. Please put the device in normal mode before proceeding. 

### ISSUE THREAD

**Issue by triggerediPhone** [LukeZGD/iOS-OTA-Downgrader#203]
Tried with two seperate iPhone 4Ss, both in pwned DFU mode using an arduino with USB Host Sheild. Neither are detected in iOS OTA Downgrader but show up in system report (though not in iTunes so might not be an issue that's fixable). I've tried using 3 different 30-pin cables, 2 phones, 2 USB ports and 2 versions of MacOS (High Sierra and Catalina (Dosdude Patcher).
Log:

******* iOS-OTA-Downgrader ******* 
 - Downgrader script by LukeZGD -  

Version: 8d753981fac1b4a5a33e07bc7226648975b55ed8 
[Log] Detected libimobiledevice and libirecovery installed from Homebrew (Intel Mac) 
[Log] Running on platform: macos (10.13.6) 
[Log] Checking Internet connection... 
[Log] Finding device in Normal mode... 
[Log] Finding device in DFU/recovery mode... 

[Error] No device detected. Please put the device in normal mode before proceeding. 
* Make sure to also trust this computer by selecting "Trust" at the pop-up. 
* For Windows/macOS users, double-check if the device is being detected by iTunes/Finder. 
* Recovery or DFU mode is also applicable. 
* To perform operations without an iOS device connected, add NoDevice as an argument. 
* For more details, read the "Troubleshooting" wiki page in GitHub

**Comment by LukeZGD** [comment]
iTunes/Finder must also be able to find your device to use iOS-OTA-Downgrader. I'm not sure on what's wrong with your setup so idk

The only things that I can suggest are to try another PC/Mac, or try it on Linux

**Comment by triggerediPhone** [comment]
Hey sorry it was my bad. I didn't realise that when I uploaded checkm8 to my arduino that the CPID had to match the one on my device. Thank you for responding to my issue though :)
