### ISSUE TITLE
cant connect with ssh

### ISSUE THREAD

**Issue by swayea** [LukeZGD/iOS-OTA-Downgrader#210]
![image](https://user-images.githubusercontent.com/107136465/187258664-e1787acb-3ccc-49e6-b14b-6d3bd24bf124.png)

![image](https://user-images.githubusercontent.com/107136465/187258769-d7c75971-03f4-48cc-850d-bf71dffb9159.png)

i re install openssl or smth but same

**Comment by LukeZGD** [comment]
Assuming that your device is in 10.3.4, have you tried (re-)installing both Dropbear from my repo and OpenSSH, reboot, and rejailbreak?

**Comment by swayea** [comment]
> Assuming that your device is in 10.3.4, have you tried (re-)installing both Dropbear from my repo and OpenSSH, reboot, and rejailbreak?

just retried like 100 times and worked anyways ty
