### ISSUE TITLE
iPad 2,3 can be restored with the latest baseband

### ISSUE THREAD

**Issue by K4sum1** [LukeZGD/iOS-OTA-Downgrader#217]
I was able to do it just now, I have restored my iPad 2,3 to 6.1.3 with the latest baseband by replacing the model in device.sh with another.

Also a but unrelated to the issue, but could you allow saving blobs for 9.3.5 and 9.3.6? Both are signed but I dunno how to get blobs without using this program.

**Comment by LukeZGD** [comment]
Doesn't work for most people, failing with error:

    futurerestore: failed with exception:
    [exception]:
    what=baseband firmware is NOT being signed!

So I will keep it disabled. For 9.3.5 and 9.3.6 blobs, use https://tsssaver.1conan.com or https://shsh.host
