### ISSUE TITLE
error in checking updates

### ISSUE THREAD

**Issue by mnyet** [LukeZGD/iOS-OTA-Downgrader#220]
i don't know if i am the only one having this but i might just share it here

here's the log of the terminal. i downloaded the latest versions and of course i tried it in a linux live usb (linux mint) and they share the same result.

******* iOS-OTA-Downgrader *******
 - Downgrader script by LukeZGD -

Version: 2022-10-11-32d0987
[Log] WARNING - Using iOS-OTA-Downgrader on Windows is highly discouraged.
* Please use it on Linux or macOS instead.
* You may still continue, but you might encounter problems with restoring the device.
[Input] Press Enter/Return to continue anyway (or press Ctrl+C to cancel)
[Log] Running on platform: win (
Microsoft Windows [Version 10.0.19044.2006])
[Log] Checking Internet connection...
[Log] Checking for updates...
./restore.sh: line 130: ((: > 20221011 : syntax error: operand expected (error token is "> 20221011 ")
* A newer version of iOS-OTA-Downgrader is available.
* Current version:
* Latest version:  2022-10-11-32d0987
* Please download the latest version before continuing.

[Input] Press Enter/Return to exit.

**Comment by Anxietytimmy** [comment]
I have the same issue on mac os currently

**Comment by BlueBoi-OS** [comment]
same issue on mac
