### ISSUE TITLE
iPad2,3 Baseband Not Signed iOS 8.1.2

### ISSUE THREAD

**Issue by Visualwit** [LukeZGD/iOS-OTA-Downgrader#221]
Full Log:
 ******* iOS-OTA-Downgrader ******* 
 - Downgrader script by LukeZGD -  

[Log] Detected libimobiledevice and libirecovery installed from Homebrew (Intel Mac) 
[Log] Running on platform: macos (11.6.8) 
* Version: 2022-10-15-e8e4cab 
[Log] Checking Internet connection... 
[Log] Checking for updates... 
[Log] Finding device in Normal mode... 
[Log] Finding device in DFU/recovery mode... 
[Log] iPad2,3 connected in DFU mode. 
[Log] ECID: 2651606680463 
*** Main Menu *** 
[Input] Select an option: 
1) Downgrade Device	      4) (Re-)Install Dependencies
2) Save OTA Blobs	      5) (Any other key to exit)
3) Create Custom IPSW
#? 1

[Input] Select iOS version: 
1) iOS 8.4.1		    3) Other (use SHSH blobs)
2) iOS 6.1.3		    4) (Any other key to exit)
#? 3

* DFU Advanced Menu 
* This menu is for ADVANCED USERS ONLY. 
* If you do not know what you are doing, EXIT NOW by pressing Ctrl+C and restart your device in normal mode. 
[Input] Select the mode that your device is currently in: 
1) kDFU mode
2) pwnDFU mode (A5)
3) Any other key to exit
#? 1
[Log] Downgrading iPad2,3 in kDFU/pwnDFU mode... 
[Log] Select your options when asked. If unsure, go for the defaults (press Enter/Return). 

[Input] Select your IPSW file in the file selection window. 
[Log] Selected IPSW file: /Users/jacobwhitney/Downloads/iPad2,3_8.1.2_12B440_Restore.ipsw 
[Input] Select your SHSH file in the file selection window. 
[Log] Selected SHSH file: /Users/jacobwhitney/Desktop/2651606680463-iPad2,3-8.1.2.shsh 
[Log] Getting build version from IPSW 
Archive:  /Users/jacobwhitney/Downloads/iPad2,3_8.1.2_12B440_Restore.ipsw
  inflating: tmp/Restore.plist       
[Log] Checking firmware keys in ./resources/firmware/iPad2,3/12B440 
[Log] Device is already in DFU mode 
[Log] Setting restore IPSW to: /Users/jacobwhitney/Downloads/iPad2,3_8.1.2_12B440_Restore.ipsw 
[Log] Extracting IPSW: /Users/jacobwhitney/Downloads/iPad2,3_8.1.2_12B440_Restore.ipsw 
[Log] Proceeding to futurerestore... 
[Log] Running futurerestore with command: ./resources/tools/futurerestore_macos_x86_64 -t "/Users/jacobwhitney/Desktop/2651606680463-iPad2,3-8.1.2.shsh" --use-pwndfu --no-ibss -b saved/baseband/Phoenix-3.6.03.Release.bbfw -p saved/iPad2,3/BuildManifest.plist "/Users/jacobwhitney/Downloads/iPad2,3_8.1.2_12B440_Restore.ipsw" 
Version: v2.0.0-test(a58821b95f6417ad649ed7a5460337dcd82e200e-259)
img4tool version: 0.197+git20210129-aca6cf005c94caf135023263cbb5c61a0081804f-RELEASE
libipatcher version: 0.86+git20210810-6a3b358b673e74c2be9f9b8a74a63b80dd94abf1-RELEASE
Odysseus for 32-bit support: yes
Odysseus for 64-bit support: yes
[INFO] 32-bit device detected
futurerestore init done
reading signing ticket /Users/jacobwhitney/Desktop/2651606680463-iPad2,3-8.1.2.shsh is done
Did set SEP+baseband path and firmware
ERROR: Unable to connect to device?!
ERROR: Unable to get FirmwarePreflightInfo
[WARNING] failed to read BasebandGoldCertID from device! Is it already in recovery?
[WARNING] using tsschecker's fallback to get BasebandGoldCertID. This might result in invalid baseband signing status information
[TSSC] opening saved/iPad2,3/BuildManifest.plist
[TSSR] Checking BuildIdentity 0
[TSSR] Selected BuildIdentity for request
[TSSR] User specified to request only a Baseband ticket.
Request URL set to https://gs.apple.com/TSS/controller?action=2
TSS server returned: STATUS=94&MESSAGE=This device isn't eligible for the requested build.
ERROR: TSS request failed (status=94, message=This device isn't eligible for the requested build.)
Sending TSS request attempt 1... futurerestore: failed with exception:
[exception]:
what=baseband firmware is NOT being signed!

code=24248328
line=370
file=main.cpp
commit count=259:
commit sha  =a58821b95f6417ad649ed7a5460337dcd82e200e:

[Log] Restoring done! Read the message below if any error has occurred: 
* Please read the "Troubleshooting" wiki page in GitHub before opening any issue! 
* Your problem may have already been addressed within the wiki page. 
* If opening an issue in GitHub, please provide a FULL log/output. Otherwise, your issue may be dismissed. 

[Log] Downgrade script done!

**Comment by LukeZGD** [comment]
Unfortunately that's just how it is now, Apple doesn't seem to sign any baseband for iPad2,3 which causes this error. OTA Downgrader gets around this by creating an IPSW with baseband update disabled, but this is only applied to 8.4.1 and 6.1.3 for now, not with "Other" downgrades.

You may also do this yourself by creating a firmware bundle for your device and creating a custom IPSW with the ipsw tool from xpwn without the `-bbupdate` flag to disable baseband update, then restoring that IPSW using `idevicerestore` or `futurerestore` depending on how the firmware bundle is made. I might be able to add this, but I don't have the time for it. 

For now, you can just restore to 8.4.1 or 6.1.3 using OTA Downgrader since they already do have the disabled baseband update.

**Comment by Visualwit** [comment]
I worked around this error by using a different version of futurerestore. Now I'm on a clean 8.1.2!
