### ISSUE TITLE
Kali not detected by the install script.

### ISSUE THREAD

**Issue by DG0134og** [LukeZGD/iOS-OTA-Downgrader#222]
When running the restore.sh in Kali Linux it shows this:

![Screenshot_2022-10-28_10-01-17](https://user-images.githubusercontent.com/66286303/198629858-aefd0f40-51cc-4171-987a-368c86d106c7.png)

**Comment by LukeZGD** [comment]
Stop using Kali if you're not doing penetration testing. I don't see the point of using Kali unless you're a cybersecurity researcher, engineer, professional. At that point you should at least know how to modify the script to get it to work.

**Comment by DG0134og** [comment]
I’m a beginner, and I do use it for penetration testing, it’s just I don’t know that much yet.
