### ISSUE TITLE
Issue checking version after using git pull to download latest

### ISSUE THREAD

**Issue by CubeBag** [LukeZGD/iOS-OTA-Downgrader#225]
<img width="561" alt="image" src="https://user-images.githubusercontent.com/17459634/200254916-97914e82-200d-4159-9d2a-4c0b5a86c68e.png">

I have the latest version (evidenced by the commit shorthash), but it refuses to run because it thinks it's a day old. Could it be due to timezones?

Edit: this also occurs after using git clone to download a fresh copy, not just git pull for an out-of-date copy

**Comment by LukeZGD** [comment]
Yeah this is totally a timezone thing, thanks for reporting the issue.. I will be fixing this shortly

**Comment by CocoTheMii** [comment]
Still appears to be happening for me.

![image](https://user-images.githubusercontent.com/44563370/204125236-dbe092bd-8ab7-4d84-afa7-61c94989ba4e.png)
