### ISSUE TITLE
Disable verbose when booting.

### ISSUE THREAD

**Issue by xuvistudent** [LukeZGD/iOS-OTA-Downgrader#226]
Hi, can I ask you how to disable verbose on booting? Is there any bootargs -v to remove? Thanks, 'cause I want to add some bootlogo instead of verbose.

**Comment by LukeZGD** [comment]
This is for the iPhone 4 I assume? You can disable it by selecting N for the Verbose Boot Option for creating the IPSW, you need to delete/rename the existing custom IPSW though
