### ISSUE TITLE
Incompatible with Nobara

### ISSUE THREAD

**Issue by Clygro** [LukeZGD/iOS-OTA-Downgrader#228]
Nobara is fork of Fedora with gaming tweaks, it gives an error saying that the Distro isn't supported, even though it's basically Fedora.

**Comment by LukeZGD** [comment]
What's the output of `cat /etc/os-release` on Nobara?

I'm pretty sure that `ID=nobara` but I'd like to know the value of `VERSION_ID` as well. I would have tested this myself but I can't download Nobara since I'm data limited atm.
