### ISSUE TITLE
device not detected from kdfu

### ISSUE THREAD

**Issue by justdie386** [LukeZGD/iOS-OTA-Downgrader#229]
im on macos monterey 12.3.1 intel and the script stays stuck on
127.0.0.1 remote connection closed (or smt) and no matter if i unplug the device or not it won't detect it

**Comment by LukeZGD** [comment]
Force restart the device and try again

Also check the macOS section of the Troubleshooting page (try installing limd/irecovery from Homebrew/MacPorts)

**Comment by justdie386** [comment]
The regular ssh the script is using, isn't working, i have to use this to ssh into my device
ssh -oHostKeyAlgorithms=+ssh-dss root@ip
I tried to modify the script with this but it just wouldn't work, would keep on throwing some other errors

**Comment by LukeZGD** [comment]
> The regular ssh the script is using, isn't working, i have to use this to ssh into my device
> 
> ssh -oHostKeyAlgorithms=+ssh-dss root@ip
> 
> I tried to modify the script with this but it just wouldn't work, would keep on throwing some other errors

The script already uses that. See resources/ssh_config
