### ISSUE TITLE
iBEC 80.9% stuck Windows

### ISSUE THREAD

**Issue by GH228** [LukeZGD/iOS-OTA-Downgrader#230]
Here is the log:

******* iOS-OTA-Downgrader *******
 - Downgrader script by LukeZGD -

[Log] WARNING - Using iOS-OTA-Downgrader on Windows is HIGHLY DISCOURAGED.
* Please use it on Linux or macOS instead.
* You may still continue, but you might encounter problems with restoring the device.
* You have been warned.
[Input] Press Enter/Return to continue anyway (or press Ctrl+C to cancel)
[Log] Running on platform: win (
Microsoft Windows [Version 10.0.17763.1879])
* Version: 2022-11-28-0f23767
[Log] Checking Internet connection...
[Log] Checking for updates...
[Log] Finding device in Normal mode...
[Log] Finding device in DFU/recovery mode...
[Log] iPhone6,1 connected in DFU mode.
[Log] ECID: 8746849042192
*** Main Menu ***
[Input] Select an option:
1) Downgrade Device           3) (Re-)Install Dependencies
2) Save OTA Blobs             4) (Any other key to exit)
#? 1
[Log] A7 device detected in DFU mode.
* Make sure that your device is already in pwnDFU mode with signature checks disabled.
* If your device is not in pwnDFU mode, the restore will not proceed!
* Entering pwnDFU mode is not supported on Windows. You need to use a Mac/Linux machine or another iOS device to do so.
[Input] Press Enter/Return to continue (or press Ctrl+C to cancel)
[Log] Select your options when asked. If unsure, go for the defaults (press Enter/Return).

[Log] Found existing Custom IPSW. Skipping 10.3.3 IPSW verification.
[Log] Setting restore IPSW to: iPhone_4.0_64bit_10.3.3_14G60_CustomW.ipsw
[Log] Extracting IPSW: iPhone_4.0_64bit_10.3.3_14G60_CustomW.ipsw
[Log] Found existing Custom IPSW. Skipping IPSW creation.
[Log] Entering pwnREC mode... (Attempt 1)
[Log] Sending iBSS...
[==================================================] 100.0%
[Log] Sending iBEC...
[=========================================         ] 80.9%[Log] Finding device in Recovery mode...
* You may also try to unplug and replug your device
[Log] Entering pwnREC mode... (Attempt 2)
[Log] Sending iBSS...
[==================================================] 100.0%
[Log] Sending iBEC...
[=========================================         ] 80.9%[Log] Finding device in Recovery mode...
* You may also try to unplug and replug your device
[Log] Entering pwnREC mode... (Attempt 3)
[Log] Sending iBSS...
[==================================================] 100.0%
[Log] Sending iBEC...
[=========================================         ] 80.9%[Log] Finding device in Recovery mode...
* You may also try to unplug and replug your device

[Error] Failed to enter pwnREC mode. You may have to force restart your device and start over entering pwnDFU mode again

[Input] Press Enter/Return to exit.

**Comment by LukeZGD** [comment]
> Windows

This is the problem

Please use it on Linux or macOS instead
