### ISSUE TITLE
32 bit device detected in dfu mode error after selecting ios version to downgrade to on iphone 4s 4,1

### ISSUE THREAD

**Issue by evankerendi** [LukeZGD/iOS-OTA-Downgrader#232]
I have tried both usb ports, the phone is in KDFU mode, and finder is detecting it in recovery mode. After I select the software version, the script tells me error 32 bit device detected in dfu mode. I tried restarting the phone and redoing kdfu mode, but it did not do anything. I'm using a 2015 macbook air running 10.15 catalina and I'm trying to downgrade a 4s to 6.1.3. How do I fix this?

Last login: Tue Dec 13 21:40:24 on ttys000

The default interactive shell is now zsh.
To update your account to use zsh, please run `chsh -s /bin/zsh`.
For more details, please visit https://support.apple.com/kb/HT208050.
air-2015:~ evankerendi$ /Users/evankerendi/Downloads/iOS-OTA-Downgrader_macos_2022-11-28-0f23767/restore.sh 

******* iOS-OTA-Downgrader ******* 
 - Downgrader script by LukeZGD -  

[Log] Running on platform: macos (10.15.7) 
* Version: 2022-11-28-0f23767 
[Log] Checking Internet connection... 
[Log] Checking for updates... 
[Log] Finding device in Normal mode... 
dyld: Library not loaded: @loader_path/libimobiledevice-1.0.dylib
  Referenced from: /Users/evankerendi/Downloads/iOS-OTA-Downgrader_macos_2022-11-28-0f23767/./resources/libimobiledevice_macos/ideviceinfo
  Reason: image not found
[Log] Finding device in DFU/recovery mode... 
[Log] iPhone4,1 connected in DFU mode. 
[Log] ECID: 4356708797711 
*** Main Menu *** 
[Input] Select an option: 
1) Downgrade Device	      4) (Re-)Install Dependencies
2) Save OTA Blobs	      5) (Any other key to exit)
3) Create Custom IPSW
#? 1

[Input] Select iOS version: 
1) iOS 8.4.1		    3) Other (use SHSH blobs)
2) iOS 6.1.3		    4) (Any other key to exit)
#? 2

[Error] 32-bit A5 device detected in DFU mode. 
* Please put the device in normal mode and jailbroken before proceeding. 
* Exit DFU mode by holding the TOP and HOME buttons for 15 seconds. 
* For usage of the DFU Advanced Menu, add PwnedDevice as an argument. 
* For more details, read the "Troubleshooting" wiki page in GitHub 
air-2015:~ evankerendi$ /Users/evankerendi/Downloads/iOS-OTA-Downgrader_macos_2022-11-28-0f23767/restore.sh

**Comment by LukeZGD** [comment]
Follow the step with `PwnedDevice`: https://github.com/LukeZGD/iOS-OTA-Downgrader/wiki/Downgrade-my-32-bit-device-(macOS-Linux,-PwnedDevice)
