### ISSUE TITLE
Question about Jailbreaking iOS 6.1.3 with p0sixpwn.

### ISSUE THREAD

**Issue by TheBalkanDev** [LukeZGD/iOS-OTA-Downgrader#236]
Hi,

how do you accomplished to run p0sixpwn on Linux?
I saw the Creator of it stating that libimobiledevice on Linux would be to slow.
Wich method do you used? And can it be used to jailbreak Devices that are already on iOS 6.2.3 without deleting & re-installing the entire OS?

**Comment by LukeZGD** [comment]
The method used here is to create a custom IPSW with p0sixspwn and Cydia bundled, then using that IPSW when restoring the device using futurerestore. AFAIK this method does not allow keeping data unfortunately, a full restore/re-install is needed

**Comment by TheBalkanDev** [comment]
Thank you. Some friends and I work currently on a 3utoools alternative using Open-Source Software. Like 3uTools Open-Source without Spyware & with the possibility to Get Device Info, Backup, Jailbreak, Load IPAs etz.

**Comment by TheBalkanDev** [comment]
I will have a look at p0sixpwn source maybe I'll find a method.

**Comment by TheBalkanDev** [comment]
Can you send me maybe the decompiled version of p0sixpwn tar file?
Would be nice.
