### ISSUE TITLE
"[Error] Failed to find custom IPSW. Please run the script again" - IPSW is in there as normal?

### ISSUE THREAD

**Issue by venturahighway72** [LukeZGD/iOS-OTA-Downgrader#241]
This is a problem on windows, not sure how it would work out on macOS or linux, as I do have a macbook and a linux distro on USB but it says something about iBEC component on those. I'm gonna do another post (if that's what they're called) soon on my macbook, because that's also broken, and I can't include it in this one because I'm on my old HP and it may be better for them to be separate. I'm not sure. (I used the HP especially so I could send screenshots but then terminal closed, didn't think that control c would do that)
Sorry if I come off as rude, or snarky, I'm just stressed out, it's not intentional lol
I was able to fix it on windows, but now I have an issue on windows (which is NOT what I want to use), by installing itunes 12.4.3 the one for old video cards. But now on windows it says
"symlink: var (0777) -> private/var/
[*] Installing untether package
merging (null)
cannot find (null), make sure your slashes are in the right direction

[Error] Failed to find custom IPSW. Please run the script again
* You may try selecting N for memory option

[Input] Press Enter/Return to exit."

Unfortunately I can't screenshot because when I tried to copy and paste that text above it closed the app but I could redo it, if it was really necessary. 
I never enabled the N memory option, I don't get that as an option on windows 10. I do have it as an option on mac os, though. This problem doesn't happen on macOS. I don't know what other information to include, but I'll try my best to answer any questions. Please help, i've literally spent like 12 hours and one more this morning trying to downgrade my iphone 4s on 9.3.6 and it's miserable.
Also by the way, I've tried a lot of things with the custom IPSW, it's there, just sitting there like normal as it always did. I don't know why it can't find it. I've tried everything, i've deleted, redownloaded and completely restarted the process a few times too. Alsoo yeah, I have ran the script probably at least 3-5 times so I don't think retrying would work anymore because something seems to be broken and not just a weird one time thing. I don't know. 
It says it's doing things (sorry for nondescriptive words, i don't remember exactly) with the IPSW throughout the entire script a lot, so I don't see why it would suddenly not be able to find it. I'm confused.
This is near the end of the script, btw.

**Comment by LukeZGD** [comment]
Full log?

**Comment by LukeZGD** [comment]
Windows version will not be fixed anytime soon, use Linux/macOS

**Comment by venturahighway72** [comment]
> Windows version will not be fixed anytime soon, use Linux/macOS
> 
> I'm currently working on a rewrite of iOS-OTA-Downgrader, I'll probably do lots of testing on that, but it will take a while. I'll release that update hopefully by next month 

So hopefully by next month the problem will be fixed? (rewrite)
I'm trying something else right now but if it doesn't work I'm going to just give up after throwing away so much time. Should I check every once in a while if what I'm doing right now fails, to see if this is updated?
