### ISSUE TITLE
Failed To Restore (BaseBand Error)

### ISSUE THREAD

**Issue by PythonScratcher** [LukeZGD/iOS-OTA-Downgrader#242]
My Restore Failed But I Know Why, It's The BaseBand, It Hasn't Been Working For a While. Is There A Way To Bypass The BaseBand Update?

Console Log
[https://pastebin.com/P1cxadad](https://pastebin.com/P1cxadad)

**Comment by LukeZGD** [comment]
Do you have a full log with the futurerestore command included? The log you sent is cut off and incomplete

Also try deleting the `saved` folder before retrying

**Comment by LukeZGD** [comment]
If your device's baseband is dead as you mentioned, you may try disabling baseband update by editing `restore.sh`, in line 3, replace `iPad2,3` with `iPhone6,2`

**Comment by PythonScratcher** [comment]
https://pastebin.com/2jWG1T03 -  Still Saying About The Device Not Taking  BaseBand Data

**Comment by LukeZGD** [comment]
You may try another tool then like LeetDown, I don't really have an A7 device with baseband to test

**Comment by LukeZGD** [comment]
Looks like disabling baseband will not work at all..Do you have a full log where baseband update is not disabled? Also, have your tried other tools like LeetDown?

**Comment by PythonScratcher** [comment]
> Looks like disabling baseband will not work at all for A7 devices. Do you have a full log where baseband update is not disabled? Also, have your tried other tools like LeetDown or manually using futurerestore? If even other tools can't restore it (to 10.3.3 or iOS 12), then I think your device is pretty much dead, sorry.

Oh ok I'll try them, I dont think it will work though

**Comment by LukeZGD** [comment]
2023-01-21-da68ba6 should finally fix this issue

**Comment by PythonScratcher** [comment]
oh ok i ended up trading the iphone 5s for a toaster

**Comment by PythonScratcher** [comment]
also does downgrading an iPad mini1 require jailbreaking?

**Comment by LukeZGD** [comment]
> also does downgrading an iPad mini1 require jailbreaking?

Depends, if you have Arduino+USB Host Shield, you can use that to downgrade without jailbreaking. If not, jailbreaking is needed

**Comment by PythonScratcher** [comment]
Ok thx
