### ISSUE TITLE
iBSS.iphone6.RELEASE.orig: command not found

### ISSUE THREAD

**Issue by rivciks** [LukeZGD/iOS-OTA-Downgrader#246]
[Log] Verifying ../iPhone_4.0_64bit_10.3.3_14G60_Restore.ipsw...
[Log] IPSW SHA1sum matches
[Log] Patching iBSS and iBEC...
Archive:  ../iPhone_4.0_64bit_10.3.3_14G60_Restore.ipsw
  inflating: iBSS.iphone6.RELEASE.im4p  
Archive:  ../iPhone_4.0_64bit_10.3.3_14G60_Restore.ipsw
  inflating: iBEC.iphone6.RELEASE.im4p  
./restore.sh: line 1464: iBSS.iphone6.RELEASE.orig: command not found
./restore.sh: line 1465: iBEC.iphone6.RELEASE.orig: command not found
cp: cannot stat 'iBSS.iphone6.RELEASE.im4p': No such file or directory
cp: cannot stat 'iBEC.iphone6.RELEASE.im4p': No such file or directory
[Log] Pwned iBSS and iBEC saved at: saved/iPhone6,2
* Get ready to enter DFU mode.
[Input] Select Y to continue, N to exit recovery mode (Y/n) 

On Arch Linux 5.15.88-2-lts

**Comment by LukeZGD** [comment]
Installing bsdiff from pacman will fix this issue. Pretty weird that it didn't install dependencies though, you can force re-installing dependencies by selecting `(Re-)Install Dependencies` in the main menu, or deleting the `firstrun` file in the `resources` folder

**Comment by LukeZGD** [comment]
I realized just now that bsdiff has been removed from [community] so I have added bspatch bins in 2023-01-28-096ab4f to fix this
