### ISSUE TITLE
timeouts are too short

### ISSUE THREAD

**Issue by rivciks** [LukeZGD/iOS-OTA-Downgrader#254]
Impressive! I successfully  downgraded my iPhone 4 on Linux. The only issue is that the timeouts are too short. 
For example timeout for  DFU mode (the iPhone entered the DFU mode shortly after a timeout error was already issued and the script terminated); as a result I had to run the script again.
And this timeout also set too short:
Starting FDR listener thread
ERROR: Unable to connect to FDR client (-2)
ERROR: Failed to start FDR Ctrl channel

**Comment by LukeZGD** [comment]
I see, I'll be increasing the default timeout in the next update

Also it's safe to ignore the FDR errors, they do not really affect anything
