### ISSUE TITLE
I've tried everything. I can't get iOS 6.1.3 to restore to an iPad 2.

### ISSUE THREAD

**Issue by jadenquinn** [LukeZGD/iOS-OTA-Downgrader#256]
This is really frustrating. I've tried every tool on every computer I own, none of them do it. I tried this tool, and the thing keeping me from using it is that the Cydia repos are all down now. I cannot find the kDFU thing anywhere, your repos are down and all the repos I see as alternatives are also all down. It also won't let me NOT use it, so I simply have to find one that works and I can't.

What do I do?

**Comment by LukeZGD** [comment]
You don't need to add any repos. Install OpenSSH from Cydia, plug in your device, run the script, follow instructions. Also do not use Windows.

**Comment by jadenquinn** [comment]
I followed the instructions. It said to install kDFU and when I didn't it wouldn't work.
