### ISSUE TITLE
Help .. Getting Error of Cannot Retrive Device Serial Number on iPhone 3,1 (Downgrading to ios 4.1) Then My iPhone Flashes White 

### ISSUE THREAD

**Issue by BlackAirdrop** [LukeZGD/iOS-OTA-Downgrader#257]

**Comment by BlackAirdrop** [comment]
Here is the Log 
![image](https://user-images.githubusercontent.com/123386533/216812626-95cf4552-f378-4b1f-99e8-535d46032440.png)

**Comment by LukeZGD** [comment]
That error means that your device is not compatible with iOS 4: https://github.com/LukeZGD/iOS-OTA-Downgrader/wiki/Troubleshooting#notes-for-iphone4down

**Comment by BlackAirdrop** [comment]
Still Present 
![Screenshot from 2023-02-06 13-11-17](https://user-images.githubusercontent.com/123386533/216980005-394f5288-3d40-466e-a9c8-952a0192cd56.png)

**Comment by LukeZGD** [comment]
That error means that your device is not compatible with iOS 5: https://github.com/LukeZGD/iOS-OTA-Downgrader/wiki/Troubleshooting#notes-for-iphone4down

**Comment by BlackAirdrop** [comment]
i Tried with ios 6 too

**Comment by BlackAirdrop** [comment]
Thank You So Much .. it works... the only problem is that when booting it up, it shows ios 7 boot logo ... any fix?
