### ISSUE TITLE
Putting a jailbreaked iPhone4,1 into the pwned DFU mode automatically

### ISSUE THREAD

**Issue by rivciks** [LukeZGD/iOS-OTA-Downgrader#259]
I successfully downgraded my iPhone4,1 to iOS 6.1.3 on Arch Linux. However, your script was not able to put my device in pwned DFU mode by himself.  So I had to  do the following steps manually:
1) copy the files pwnediBSS and kloader via scp to my device,
2) make kloader an executable,
3) run kloader pwnediBSS via ssh on my device.
Maybe you can include those commands in your script, so that it does it all automatically by himself.

**Comment by LukeZGD** [comment]
That is exactly what the script does though: https://github.com/LukeZGD/iOS-OTA-Downgrader/blob/main/restore.sh#L683

**Comment by rivciks** [comment]
That's odd, It didn't work for me. Unfortunately, I didn't make a log. I only remember to options popping up while processing the script: "Is device in pawned DFU mode y/N". Neither of those options worked: "Yes" didn't work obviously since my device wasn't in  pawned DFU mode and "no" didn't either work and the script terminated. So I had to put my device in pawned DFU mode  manually in the way mentioned above.

**Comment by LukeZGD** [comment]
You need to put `Y`, not `Yes`

**Comment by rivciks** [comment]
Hmm, perhaps that was it. When I have time, I'll check out it again.
