### ISSUE TITLE
Failed to enter pwnDFU mode/Ipad 4 32 bit

### ISSUE THREAD

**Issue by Boulseye** [LukeZGD/iOS-OTA-Downgrader#260]
I was trying to downgrade my jailbroken ipad through this script, I’ve installed the ipsw of the ios 8.4.1 within the script on my mac and everything was working fine until I kept getting the same error after:running heap_occupation() , I start getting red lines ERROR:Failed to reconnect to device.
[Error] Failed to enter pwnDFU mode. Please run the script again. Can someone help me please?
P.S: If I start the script while my ipad is in pwned dfu using Ipwnder32 I get an error while processing which is “An error occurred copying manifest. Please run the script again”

**Comment by LukeZGD** [comment]
Are you using kok3shiX or h3lix? If using h3lix, switch to kok3shiX and turn on "use legacy patches."

As for pwned DFU, success rates vary depending on the device. On majority of Macs including my Hackintosh, it works fine, but for some others, it doesn't work.
