### ISSUE TITLE
Too many error messages during the downgrade of A7 to  iOS 10.3.3 

### ISSUE THREAD

**Issue by rivciks** [LukeZGD/iOS-OTA-Downgrader#262]
However, during the downgrade process of A7 device to iOS 10.3.3 on Linux I received too many error messages. The downgrade itself, as far as I can tell, was successful. I wonder if those error messages can be safely ignored. Here is the log.
[A7_to_10-3-3.log](https://github.com/LukeZGD/iOS-OTA-Downgrader/files/10707170/A7_to_10-3-3.log)

**Comment by LukeZGD** [comment]
Yes the errors from tsschecker and futurerestore can be ignored as long as the restore succeeds
