### ISSUE TITLE
iPwnder Lite missing from Sileo repo

### ISSUE THREAD

**Issue by Luigialberto04** [LukeZGD/iOS-OTA-Downgrader#263]
Hi! I was trying to downgrade my A7 iPhone 5S on Linux (with obviously poor results) so I just decided to go the “iOS iPwnder Lite” route, but my other device is a Chimera iPad Mini 2 so I have Sileo, not Cydia, and your Sileo repo is empty, so could you please add iPwnder lite to your sileo repo? Thanks so much! Also sorry if I’m asking in the wrong section but it’s my first time making a comment on github.

**Comment by Luigialberto04** [comment]
Also, another question, how can I install iPwnder Lite? I‘m new in the jailbreak scene, I tried downloading it on my Cydia device from your repo and I installed it but it isn’t appearing neither in my home screen and in settings. Am I doing something wrong or is it just a bug? Thank you so much

**Comment by LukeZGD** [comment]
https://github.com/LukeZGD/iOS-OTA-Downgrader/issues/245#issuecomment-1399364184
