### ISSUE TITLE
need vpn?ping 208.67.222.222?

### ISSUE THREAD

**Issue by lzyccybadu** [LukeZGD/iOS-OTA-Downgrader#265]
need vpn?ping 208.67.222.222?
[Error] Please check your Internet connection before proceeding.
can you help? thk

**Comment by LukeZGD** [comment]
VPN is not needed.

**Comment by lzyccybadu** [comment]
这是来自QQ邮箱的自动回复邮件，已确认收到您的电子邮件，我将尽快回复，谢谢！（This is an automatic reply, confirming that your email was received.I will reply as soon as possible.Thank you!）

**Comment by lzyccybadu** [comment]
[Log] Verifying ../iPad_64bit_10.3.3_14G60_Restore.ipsw...
[Log] IPSW SHA1sum matches
[Log] Patching iBSS and iBEC...
Archive:&nbsp; ../iPad_64bit_10.3.3_14G60_Restore.ipsw
&nbsp; inflating: iBSS.ipad4.RELEASE.im4p
Archive:&nbsp; ../iPad_64bit_10.3.3_14G60_Restore.ipsw
&nbsp; inflating: iBEC.ipad4.RELEASE.im4p
Archive:&nbsp; ../iPad_64bit_10.3.3_14G60_Restore.ipsw
&nbsp; inflating: iBSS.ipad4b.RELEASE.im4p
Archive:&nbsp; ../iPad_64bit_10.3.3_14G60_Restore.ipsw
&nbsp; inflating: iBEC.ipad4b.RELEASE.im4p
[Log] Pwned iBSS and iBEC saved at: saved/iPad4,4
* Make sure that your device is in PWNED DFU or kDFU mode.
* For 32-bit devices, pwned iBSS/kDFU must be already booted.
* For A7 devices, signature checks must be already disabled.
[Input] Press Enter/Return to continue (or press Ctrl+C to cancel)
[Log] Running tsschecker with command: ../bin/windows/tsschecker -d iPad4,4 -i 10.3.3 -e 4902861526344 -m ../resources/manifest/BuildManifest_iPad4,4_10.3.3.plist -o -s -B j85ap -b -g 0x1111111111111111
tsschecker version: 0.359-fcf8536b0143a94a82b15a661ea3f770ff491998
libfragmentzip version: 0.64-aaf6fae83a0aa6f7aae1c94721857076d04a14e8-RELEASE
[TSSC] manually specified generator "0x1111111111111111"
[TSSC] manually specified ECID to use, parsed "4902861526344" to dec:4902861526344 hex:4758951d548
[TSSC] opening ../resources/manifest/BuildManifest_iPad4,4_10.3.3.plist
[TSSR] Checking BuildIdentity 0
[TSSR] Selected BuildIdentity for request
[TSSR] User specified to not request a baseband ticket.
[TSSR] Request URL set to https://gs.apple.com/TSS/controller?action=2
[TSSR] Sending TSS request attempt 1... success
also requesting APTicket for installType=Update
[TSSR] Checking BuildIdentity 0
[Error] [TSSR] Error: could not get BuildIdentity for installType=Update
[WARNING] [TSSR] failed to build tssrequest for alternative installType
[TSSR] Checking BuildIdentity 0
[TSSR] Selected BuildIdentity for request
[TSSR] User specified to not request a baseband ticket.
[TSSR] Request URL set to https://gs.apple.com/TSS/controller?action=2
[TSSR] Sending TSS request attempt 1... failure
[Error] ERROR: TSS request failed (status=128, message=An internal error occurred.)
Saved shsh blobs!


iOS 10.3.3 for device iPad4,4 IS being signed!
[Log] Successfully saved 10.3.3 blobs: 4902861526344_iPad4,4_j85ap_10.3.3-14G60_3a88b7c3802f2f0510abc432104a15ebd8bd7154.shsh2
[==================================================] 100.0%
[Log] Entering pwnREC mode... (Attempt 1)
[Log] Sending iBSS...
[==================================================] 100.0%
[Log] Sending iBEC...
[========================================&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; ] 78.9%[Log] Finding device in Recovery mode...
* You may also try to unplug and replug your device
[Log] Entering pwnREC mode... (Attempt 2)
[Log] Sending iBSS...
[Log] Sending iBEC...
[========================================&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; ] 78.9%[Log] Finding device in Recovery mode...
* You may also try to unplug and replug your device
[Log] Entering pwnREC mode... (Attempt 3)
[Log] Sending iBSS...
[Log] Sending iBEC...
[========================================&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; ] 78.9%[Log] Finding device in Recovery mode...
* You may also try to unplug and replug your device
[Log] Entering pwnREC mode... (Attempt 4)
[Log] Sending iBSS...
[Log] Sending iBEC...
[========================================&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; ] 78.9%[Log] Finding device in Recovery mode...
* You may also try to unplug and replug your device
[Error] Failed to enter pwnREC mode. You may have to force restart your device and start over entering pwnDFU mode again


[Input] Press Enter/Return to exit.

**Comment by LukeZGD** [comment]
Did you put your device in pwned DFU mode using ipwndfu/ipwnder/gaster? This is required or else it will fail

**Comment by lzyccybadu** [comment]
Yes, the device is in UDF mode。

**Comment by LukeZGD** [comment]
DFU mode is not enough. It needs to be pwned DFU using ipwndfu, ipwnder, or gaster

**Comment by lzyccybadu** [comment]
OK, thanks. I'll try how to&nbsp; pwned dfu mode

**Comment by lzyccybadu** [comment]
这个脚本降级10.3.3后能绕过ID激活锁吗？Can this script bypass the ID activation lock after demoing?
