### ISSUE TITLE
iPad2,2 stuck on recovery mode

### ISSUE THREAD

**Issue by ThisIsntLeo** [LukeZGD/iOS-OTA-Downgrader#267]
iPas2,2 GSM
8.4.1 to 6.1.3
![image](https://user-images.githubusercontent.com/96735005/219208872-bfd5f117-c3c9-4cd4-9300-c0e8bd9d519a.jpg)

**Comment by LukeZGD** [comment]
Full log/output?

**Comment by LukeZGD** [comment]
Oh wait, I think I know what this is, it's similar to #253. I'll disable baseband update for the iPad2,2 then

**Comment by ThisIsntLeo** [comment]
> Full log/output?

It said restore completed
