### ISSUE TITLE
[Feature] Option to bypass Entering PwnDFU / Check if device is Pwned (Linux)

### ISSUE THREAD

**Issue by LuckyHeroes** [LukeZGD/iOS-OTA-Downgrader#274]
Device may already be in PWNDFU mode, have it show the PWNDFU message from the windows build

"* Make sure that your device is in PWNED DFU or kDFU mode."
"* For 32-bit devices, pwned iBSS/kDFU must be already booted."
"* For A7 devices, signature checks must be already disabled."

or show a 3rd option

[Input] PwnDFU Tool Option
* Select tool to be used for entering pwned DFU mode.
* This option is set to ipwnder by default (1).
[Input] Select your option:
1) ipwnder
2) gaster
3) Device is already PWNed

or simply check the device to see if its in PWNDFU then move on to next step.

**Comment by LukeZGD** [comment]
Done in 2023-03-04-c73328d
