### ISSUE TITLE
weird missing dll issue

### ISSUE THREAD

**Issue by casey321123** [LukeZGD/iOS-OTA-Downgrader#275]
installed mysys2, getting this:
[Log] Getting version from IPSW
Archive:  C:\Users\adolf\OneDrive\Desktop\iPhone5,1_6.0_10A405_Restore.ipsw
  inflating: ./Restore.plist
[Log] Downloading iBSS...
C:/Users/adolf/iOS-OTA-Downgrader/bin/windows/partialzip: error while loading shared libraries: msys-curl-4.dll: cannot open shared object file: No such file or directory
          cp: cannot stat 'iBSS': No such file or directory
[Log] Patching iBSS...
bspatch: iBSS: No such file or directory
cp: cannot stat 'pwnediBSS': No such file or directory
[Log] Pwned iBSS saved at: saved/iPhone5,1/pwnediBSS
[Log] Running iproxy for SSH...
[Log] Please read the message below:

**Comment by LukeZGD** [comment]
Try one of the following:

- Select the "(Re-)Install Dependencies" in the main menu
- Delete the `firstrun` file in resources folder
- Uninstall MSYS2 completely, then download and install latest MSYS2 from https://www.msys2.org/#installation
