### ISSUE TITLE
M2 Air stays at one spot for a while then device boots into normal mode 

### ISSUE THREAD

**Issue by JeydenT** [LukeZGD/iOS-OTA-Downgrader#276]
Whenever I try to downgrade my iPhone 5s (6,1) my mac terminal gets stuck on "running set_global_state". ive tried a older version but it would do the same. I just want to know if its for Intel processors only? i also have tried on the linux environment but it hasnt worked.

**Comment by LukeZGD** [comment]
It should work for Apple Silicon too, though binaries in the repo are compiled with Intel Macs in mind.. What you can try though is to compile and run ipwnder_lite yourself while the device is plugged in DFU mode: 

```
git clone --recursive https://github.com/dora2-iOS/ipwnder_lite
cd ipwnder_lite
make
./ipwnder_macosx
```
