### ISSUE TITLE
iPod Touch 5 Restoring Failed 

### ISSUE THREAD

**Issue by Gask0ff** [LukeZGD/iOS-OTA-Downgrader#277]
Hello! I have an iPod Touch 5, with jailbroken 6.1.2 installed, and I want to restore to a clean 6.1.2 version.
Firstly, I'm saving onboard blobs. I am attaching the full log file of saving blobs:
[SavingOnBoardBlobs_Log.txt](https://github.com/LukeZGD/iOS-OTA-Downgrader/files/10986035/SavingOnBoardBlobs_Log.txt)

Secondly, I start the restore, but I get an error, here is the full log of restoring:
[Restoring_Log.txt](https://github.com/LukeZGD/iOS-OTA-Downgrader/files/10986054/Restoring_Log.txt)

And my device is stucking on this screen:
![IMG_0071](https://user-images.githubusercontent.com/109815274/225495075-288bb0d0-8de5-460e-9f97-a310d2005814.jpg)

Tried this much times, and had the same bad result :(

(Also, using the same computer, the same cable, I am successfully restored iPad Mini1 from 6.1.2 to 6.1.2, and 4S from 5.1.1 to 5.1.1, but with iPod Touch 5, I am getting error)

Can you help me, please...?

**Comment by LukeZGD** [comment]
You can try restoring again by:
1. Force restart the device (hold Power+Home until iTunes screen appears)
2. Run the script and select "Downgrade Device" to exit recovery mode
3. Try downgrading again with a different USB port

**Comment by Gask0ff** [comment]
Of course, I am restarted device and exited recovery, and tried again and again 
I am repeatedly downloaded the script, the ipsw, dumped blobs again, tried different ports, different cables, and got the same error everytime
And right now, I took my ipad mini 1 and it restored perfectly. But with this ipod touch 5, restore is stucking on "Sending RestoreKernelCache", and getting error...

Could this be a problem with the script, or something wrong with my device?

**Comment by LukeZGD** [comment]
No it's something wrong with futurerestore on Mac. You can maybe try again on Linux

**Comment by LukeZGD** [comment]
You may also try editing `restore.sh` and set `device_disable_bbupdate` to "iPod5,1"

I know the iPod touch doesn't have baseband, but this will create a custom IPSW then restore with idevicerestore instead of futurerestore

**Comment by LukeZGD** [comment]
It's very strange yeah, I already checked the logs provided and everything seems to check out, it's just that the restore won't proceed at all... I guess something is going wrong with the onboard blob? Try dumping blobs again with this: https://github.com/RossDarker/A5-A6X-Blobs-Dumper, or dumping with Odysseus manually

Other than that, I'm not sure if I can help any further, sorry

**Comment by Gask0ff** [comment]
Anyway, thanks a lot for trying to help me. I will continue to try different methods, and of course I will keep follow script updates. Have a nice day!
