### ISSUE TITLE
AppSync Unified Issues

### ISSUE THREAD

**Issue by fqrums** [LukeZGD/iOS-OTA-Downgrader#281]
After downgrading to ios 6.0 using Iphone4Down on a Iphone3,1 (GSM), it boots fine but after jailbreaking and installing AppSync it ends up in a boot loop and it can never exit, force rebooting does nothing..?

**Comment by LukeZGD** [comment]
Enter no substrate mode: hold volume up while device is booting, then remove the tweak in Cydia
