### ISSUE TITLE
Small problems

### ISSUE THREAD

**Issue by jack980517** [LukeZGD/iOS-OTA-Downgrader#32]
I stumbled upon some small problems in your script.
- The dependency install for Fedora doesn't include git, which is not included in the LiveCD environment of Fedora 32, so `git clone` fails. I manually installed git, and added `--depth 1` because accessing GitHub from China is slow and commit history isn't necessary for this anyway.
- Determining the distro by checking the package manager isn't reliable, as package managers could be installed on different distros than their "home" distros. On the Fedora installation on my hard drive, I have pacman installed for 3DS homebrew development, so I had to comment out the Arch Linux `if` branch.
- *Maybe* add some code so that if the hashsum of the openssl rpm matches the previously downloaded one, the script would not download it again when re-installing dependencies? My ISP is shitty and downloading that file took me 5 minutes lol

**Comment by LukeZGD** [comment]
Thanks for the suggestions! I will be applying them in the dependency install script for all supported distros

**Comment by jack980517** [comment]
I meant checking the hashsum of the file **when re-installing dependencies**, not **immediately after the download**. If the hash is the same, we would know that the file is correct, and thus would not need to be redownloaded. Currently your script deletes the rpm file unconditionally when re-install dependencies is chosen, which causes the file to be downloaded again, and I want to avoid that.

**Comment by LukeZGD** [comment]
I think I get what you mean now, thanks for clarifying! I just updated the dependency install to copy the downloading pkgs to "saved" and only delete when hashes don't match
