### ISSUE TITLE
Program to corroborate checksum doesn't exist

### ISSUE THREAD

**Issue by iWumboUWumbo2** [LukeZGD/iOS-OTA-Downgrader#33]
Line 340 of restore.sh should be `IPSWSHA1L=$(shasum $IPSW.ipsw | awk '{print $1}')` as `sha1sum` doesn't exist, at least on macOS.

**Comment by LukeZGD** [comment]
It think this is already in the dweendency install, where `md5sha1sum` from Homebrew is installed providing `sha1sum` for macOS

**Comment by iWumboUWumbo2** [comment]
I reinstalled dependencies and it still failed on the checksum. However, I just did the one edit mentioned above and the restore succeeded. I'll double-check if `md5sha1sum` is installed and get back to you.
