### ISSUE TITLE
Restore fails at the very end with error code -11

### ISSUE THREAD

**Issue by CSab6482** [LukeZGD/iOS-OTA-Downgrader#38]
I was able to run through most of the script (for iPod 5,1 9.3.5 -> 8.4.1) without any problems, but at the very end as I had the Apple logo and progress bar, I received these errors.

ERROR: Unable to send data to ASR. Sent 0 of 1450 bytes.
ERROR: Unable to send filesystem payload
ERROR: Unable to send payload to ASR
ERROR: Unable to send filesystem
ERROR: Unable to successfully restore device
[Error] ERROR: Unable to restore device
Done: restoring failed.
Failed with errorcode=-11

A few weeks ago, when this was 32 bit OTA Downgrader, I was able to downgrade my iPhone 4S with no problems, but this error pushed my iPod into such an unreachable state that I had to pay $30 for Reiboot Pro to recover it. Any help would be appreciated.

**Comment by LukeZGD** [comment]
What OS and version are you using?

**Comment by CSab6482** [comment]
macOS 10.14.6 and the latest version of the script as of 18 hours ago

**Comment by LukeZGD** [comment]
Please try again with the latest commit

**Comment by CSab6482** [comment]
I couldn't connect over SSH even after reinstalling SSH, deleting my known hosts file and retrusting my iPod, and unjailbreaking/rejailbreaking. And for the iTunes DFU restore, I tried 4 different Windows PCs and 2 macOS machines, and all of them gave me USB restore errors (namely error 9, 14, or 2006). Reiboot Pro was the only way I was able to kick the device out of recovery mode (and I couldn't use the Exit Recovery mode option, I had to use the Deep Repair Operating System option).

**Comment by CSab6482** [comment]
^ I also tried five different lightning cables, three of which were OEM, and every different USB port available on the computers.

**Comment by LukeZGD** [comment]
For SSH, I might change the script to use USB SSH sometime, I will need more testing though so this will take a while
For the other problems, I really don't know, that restore problem really sounds like a hardware problem to me at this point especially when you tried different cables/systems and still get multiple errors
