### ISSUE TITLE
Failed to detect device in PWNREC mode. (iPhone 5s 6,2)

### ISSUE THREAD

**Issue by Kubamach** [LukeZGD/iOS-OTA-Downgrader#41]
[Log] Verifying IPSW...
[Log] Extracting IPSW...
[Log] Preparing custom IPSW...
[Log] Entering PWNREC mode...
[=========================================         ] 80.9%
[Error] Failed to detect device in PWNREC mode. Please try again

**Comment by LukeZGD** [comment]
Hard-reset and try again

I experienced that as well where irecovery just freezes in entering PWNREC, I had to hard-reset and start over for it to work
