### ISSUE TITLE
Still getting PWNREC failed even after multiple hard resets

### ISSUE THREAD

**Issue by Kubamach** [LukeZGD/iOS-OTA-Downgrader#42]
successfully applied patches
Resetting device state
Device is now ready to accept unsigned images
[Log] Downgrading device iPhone6,2 in pwnDFU mode...
[Log] Option: Downgrade
[Log] Extracting IPSW...
[Log] Entering PWNREC mode...
[==================================================] 100.0%
[==================================================] 100.0%

[Error] Failed to detect device in PWNREC mode. Please try again

**Comment by LukeZGD** [comment]
The latest commit gives an option to continue (only do this if the backlight of your device is already on, even then it might still fail)

You may also try to use different USB port/cable (avoid lightning to USB C cables)

**Comment by Kubamach** [comment]
Thanks, I forgot to add that at that point the screen backlight turns on, trying again revealed that it was already in recovery. Thanks for that, I’ll try later today.

**Comment by Samaelxv** [comment]
did you succeed?

**Comment by Kubamach** [comment]
> 
> 
> did you succeed?

Yes, I did.
