### ISSUE TITLE
[Error] Failed to detect device in pwnDFU mode. Please run the script again * ./restore.sh Downgrade

### ISSUE THREAD

**Issue by ApocalypticPsychedelic** [LukeZGD/iOS-OTA-Downgrader#45]
I am attempting to downgrade my iPhone 5s from iOS 12.1.4 to iOS 10.3.3
Here are my logs:

******* iOS-OTA-Downgrader *******
   Downgrader script by LukeZGD   

[Input] Enter ProductType (eg. iPad2,1): iPhone6,1
[Log] Updating firmware...
Already up to date.
[Log] Updating ipwndfu...
Already up to date.
* Platform: macos
* HardwareModel: n51ap
* ProductType: iPhone6,1
* ProductVersion: Unknown
* UniqueChipID (ECID): 0x0000030f8ebd85ec

[Log] Option: Downgrade
[Log] A7 device in recovery mode detected. Get ready to enter DFU mode
[Input] Select Y to continue, N to exit recovery (Y/n) Y
* Hold POWER and HOME button for 10 seconds.
10 9 8 7 6 5 4 3 2 1 
* Release POWER and hold HOME button for 10 seconds.
10 9 8 7 6 
[Log] Device in DFU mode detected.
[Log] Entering pwnDFU mode with ipwndfu...
sudo: python2: command not found

[Error] Failed to detect device in pwnDFU mode. Please run the script again
* ./restore.sh Downgrade

This is probably a very stupid error on my part but I am curious as to how to fix this

Thanks!

**Comment by LukeZGD** [comment]
Re-install dependencies
`./restore.sh Install`

**Comment by LukeZGD** [comment]
Should be fully fixed by latest commit
