### ISSUE TITLE
Prerequisites Suggestion

### ISSUE THREAD

**Issue by SwiftMove** [LukeZGD/iOS-OTA-Downgrader#46]
Just wanted to make a suggestion to add "Homebrew" and "libzip" to the list of "Prerequisites" in the README. On a clean install of Mojave 10.14.6 doing a "Downgrade device > Other" resulted in the error listed below. After installing Homebrew and libzip, it works fine.

```[Log] Downloading iBSS...
dyld: Library not loaded: /usr/local/opt/libzip/lib/libzip.5.dylib
  Referenced from: /Users/SwiftMove/Desktop/iOS-OTA-Downgrader/resources/tools/pzb_macos
  Reason: image not found
./restore.sh: line 213:  5967 Abort trap: 6           $pzb -g Firmware/dfu/$iBSS.dfu -o $iBSS.dfu $(cat $Firmware/$iBSSBuildVer/url)
mv: rename iBSS.n41.RELEASE.dfu to saved/iPhone5,1/iBSS.n41.RELEASE.dfu: No such file or directory

[Error] Failed to save iBSS. Please run the script again```

**Comment by LukeZGD** [comment]
Latest commit now uses partial-zip instead of partialZipBrowser, should solve the error and won't need Homebrew
