### ISSUE TITLE
A7 Device unable to boot into pwndfu mode

### ISSUE THREAD

**Issue by HaydarZaraki** [LukeZGD/iOS-OTA-Downgrader#47]
Trying to downgrade iphone 5s from 12.4.8 to 10.3.3 (with OTA Blobs) [Possible]

but i can't seem to get past the dfu mode as the device refuses to enter ipwndfu

Error detail:

[Error] Failed to detect device in pwnDFU mode. Please run the script again

* ./restore.sh Downgrade

I'm running from Linux Ubuntu 20.04

i think its a common issue with no real fix, so many people talk about it yet no one seems to share something actually helpful

i understand you have to try it 40+ times and i did (100+ times) still not booting to ipwndfu

**Comment by LukeZGD** [comment]
There is really not much that I can do for improved success rates with ipwndfu

Though I recommend trying on live USB as I never had any success on a full install
