### ISSUE TITLE
SSH problem when downgrading iPhone5,1

### ISSUE THREAD

**Issue by DonkeyKongJr1982** [LukeZGD/iOS-OTA-Downgrader#50]
[Error] Cannot connect to device via SSH.
* Please check your ~/.ssh/known_hosts file and try again

**Comment by LukeZGD** [comment]
What iOS version? If on iOS 10, do you have Dropbear installed?

Also please give full terminal output

**Comment by DonkeyKongJr1982** [comment]
iOS 8.4.1 for device iPhone5,1 IS being signed!
[Log] Successfully saved 8.4.1 blobs.
[Log] Verifying IPSW...
[Log] Extracting iBSS from IPSW...
Archive:  iPhone5,1_8.4.1_12H321_Restore.ipsw
  inflating: saved/iPhone5,1/iBSS.n41.RELEASE.dfu  
[Log] Patching iBSS...
bind(): Address already in use
Error creating socket: Address already in use
* Make sure OpenSSH/Dropbear is installed on the device!
[Log] Copying stuff to device via SSH...
* (Enter root password of your iOS device when prompted, default is 'alpine')
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@    WARNING: REMOTE HOST IDENTIFICATION HAS CHANGED!     @
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
IT IS POSSIBLE THAT SOMEONE IS DOING SOMETHING NASTY!
Someone could be eavesdropping on you right now (man-in-the-middle attack)!
It is also possible that a host key has just been changed.
The fingerprint for the RSA key sent by the remote host is
SHA256:an2ViR9NysFK+8YqtdY4TjA1WOjNjOiBhNnPdWyyS2g.
Please contact your system administrator.
Add correct host key in /Users/username/.ssh/known_hosts to get rid of this message.
Offending ECDSA key in /Users/username/.ssh/known_hosts:1
RSA host key for [127.0.0.1]:2222 has changed and you have requested strict checking.
Host key verification failed.
lost connection

[Error] Cannot connect to device via SSH.
* Please check your ~/.ssh/known_hosts file and try again

**Comment by DonkeyKongJr1982** [comment]
Also I installed both OpenSSH and Dropbear (Using Filza, did a respring and full restart & jailbreak after installing)

**Comment by LukeZGD** [comment]
Run `rm ~/.ssh/known_hosts` then try again

**Comment by DonkeyKongJr1982** [comment]
SUCCESS! Honestly can't thank you enough for this tool! It was pretty easy to use too, I just got intimidated by it's Command Line nature and the lack of a YouTube tutorial. Once again, thank you!
