### ISSUE TITLE
iPad Mini 1 SSH error

### ISSUE THREAD

**Issue by vedranmarinovic** [LukeZGD/iOS-OTA-Downgrader#57]
**Issue**
Cannot connect to my iPad Mini 1 (iPad2,5) using SSH, gives the following error:

[Error] Cannot connect to device via SSH. Please check your ~/.ssh/known_hosts file and try again 
You may also run: rm ~/.ssh/known_hosts 

Though, even after running that command, and the command giving me the following output:

Users/username/.ssh/known_hosts: No such file or directory

It still does not work..

**Log**
******* iOS-OTA-Downgrader ******* 
   Downgrader script by LukeZGD    

[Log] Updating firmware... 
Already up to date.
[Log] Updating ipwndfu... 
Already up to date.
[Log] Finding device in normal mode... 
* Platform: macos 
* HardwareModel: p105ap 
* ProductType: iPad2,5 
* ProductVersion: 9.3.5 
* UniqueChipID (ECID): 1368720764171 

*** Main Menu *** 
[Input] Select an option: 
1) Downgrade device		 4) (Re-)Install Dependencies
2) Save OTA blobs		 5) (Any other key to exit)
3) Just put device in kDFU mode
#? 1
[Input] Select iOS version: 
1) iOS 8.4.1		    3) (Any other key to exit)
2) Other
#? 1
[Log] Option: Downgrade 
[Input] Jailbreak the selected iOS version? (y/N):  y
[Log] Saving 8.4.1 blobs with tsschecker... 
Version: b9d193aa6e6d24421094873c830692d02d8b32f5 - 304
libfragmentzip version: 0.59-542a470d7be248681dba71d0f04e7dc8c2718b73
[TSSC] manually specified ECID to use, parsed "1368720764171" to dec:1368720764171 hex:13eae1d6d0b
[TSSC] opening resources/manifests/BuildManifest_iPad2,5_8.4.1.plist
[WARNING] [TSSC] could not get id0 for installType=Erase. Using fallback installType=Update since user did not specify installType manually
[TSSR] LOG: device iPad2,5 doesn't need a baseband ticket, continuing without requesting a Baseband ticket
[TSSR] Request URL set to https://gs.apple.com/TSS/controller?action=2
[TSSR] Sending TSS request attempt 1... success
[Error] [TSSR] Error: could not get id0 for installType=Erase
Saved shsh blobs!

iOS 8.4.1 for device iPad2,5 IS being signed!
[Log] Successfully saved 8.4.1 blobs. 
[Log] Verifying IPSW... 
[Log] Extracting iBSS from IPSW... 
Archive:  iPad2,5_8.4.1_12H321_Restore.ipsw
  inflating: saved/iPad2,5/iBSS.p105.RELEASE.dfu  
[Log] Patching iBSS... 
bind(): Address already in use
Error creating socket: Address already in use
[Log] Copying stuff to device via SSH... 
* Make sure OpenSSH/Dropbear is installed on the device! 
* Enter root password of your iOS device when prompted, default is 'alpine' 
kex_exchange_identification: read: Connection reset by peer
lost connection

[Error] Cannot connect to device via SSH. Please check your ~/.ssh/known_hosts file and try again 
* You may also run: rm ~/.ssh/known_hosts

**Comment by LukeZGD** [comment]
Install/Reinstall OpenSSH
