### ISSUE TITLE
Ipad mini no update after script

### ISSUE THREAD

**Issue by leftkal** [LukeZGD/iOS-OTA-Downgrader#60]
Hello, I try to downgrade my ipad mini. I installed openssh connected my device run the script, it finished. I ha to push power + home button for my device to start. There was no OTA update available. I run ./restore.sh Install, didn't help. I always end up starting my device and no update available. Thats the output from the script. Any ideas?

******* iOS-OTA-Downgrader ******* 
   Downgrader script by LukeZGD    

[Log] Updating firmware... 
Already up to date.
[Log] Updating ipwndfu... 
Already up to date.
[Log] Finding device in normal mode... 
* Platform: linux 
* HardwareModel: p105ap 
* ProductType: iPad2,5 
* ProductVersion: 9.3.5 
* UniqueChipID (ECID): 1823148168584 

*** Main Menu *** 
[Input] Select an option: 
1) Downgrade device		 4) (Re-)Install Dependencies
2) Save OTA blobs		 5) (Any other key to exit)
3) Just put device in kDFU mode
#? 1
[Input] Select iOS version: 
1) iOS 8.4.1		    3) (Any other key to exit)
2) Other
#? 1
[Log] Option: Downgrade 
[Input] Jailbreak the selected iOS version? (y/N):  y
[Log] Saving 8.4.1 blobs with tsschecker... 
Version: 7895a76c8ac57e45b87bb756e6d8a617740aab62 - 317
libfragmentzip version: 0.60-120447d0f410dffb49948fa155467fc5d91ca3c8
[TSSC] manually specified ECID to use, parsed "1823148168584" to dec:1823148168584 hex:1a87c195588
[TSSC] opening resources/manifests/BuildManifest_iPad2,5_8.4.1.plist
[TSSR] Checking BuildIdentity 0
[WARNING] [TSSC] could not get BuildIdentity for installType=Erase. Using fallback installType=Update since user did not specify installType manually
[TSSR] Checking BuildIdentity 0
[TSSR] Selected BuildIdentity for request
[TSSR] LOG: device iPad2,5 doesn't need a baseband ticket, continuing without requesting a Baseband ticket
[TSSR] Request URL set to https://gs.apple.com/TSS/controller?action=2
[TSSR] Sending TSS request attempt 1... success
[TSSR] Checking BuildIdentity 0
[Error] [TSSR] Error: could not get BuildIdentity for installType=Erase
Saved shsh blobs!

iOS 8.4.1 for device iPad2,5 IS being signed!
[Log] Successfully saved 8.4.1 blobs. 
[Log] Extracting iBSS from IPSW... 
Archive:  iPad2,5_8.4.1_12H321_Custom.ipsw
  inflating: saved/iPad2,5/iBSS.p105.RELEASE.dfu  
[Log] Patching iBSS... 
bind(): Address already in use
Error creating socket: Address already in use
[Log] Copying stuff to device via SSH... 
* Make sure OpenSSH/Dropbear is installed on the device! 
* Enter root password of your iOS device when prompted, default is 'alpine' 
accepted connection, fd = 4
waiting for connection
Number of available devices == 1
Requesting connecion to device handle == 1 (serial: 2ca1f1f9b12804812708684b99ed353f3571914c), port 22
run_ctos_loop: fd = 4
run_stoc_loop: fd = 4
root@127.0.0.1's password: 
kloader                                       100%   51KB   3.9MB/s   00:00    
pwnediBSS                                     100%   76KB   1.3MB/s   00:00    
pwn.sh                                        100%   45    18.7KB/s   00:00    
recv failed: Resource temporarily unavailable
[Log] Entering kDFU mode... 

* Press POWER or HOME button when screen goes black on the device 
[Log] Finding device in DFU mode... 
recv failed: Resource temporarily unavailable
accepted connection, fd = 5
waiting for connection
Number of available devices == 1
Requesting connecion to device handle == 1 (serial: 2ca1f1f9b12804812708684b99ed353f3571914c), port 22
run_ctos_loop: fd = 5
run_stoc_loop: fd = 5
root@127.0.0.1's password: 
recv failed: Resource temporarily unavailable
Connection to 127.0.0.1 closed by remote host.
[Log] Found device in DFU mode. 
./restore.sh: line 295: kill: (20840) - No such process
[Log] Extracting IPSW... 
[Log] Proceeding to idevicerestore... 
resources/tools/idevicerestore_linux: error while loading shared libraries: libimobiledevice-1.0.so.6: cannot open shared object file: No such file or directory

[Log] Restoring done! 
[Log] Downgrade script done!

**Comment by LukeZGD** [comment]
What Linux distro and version? Reinstalling dependencies should work if supported

**Comment by leftkal** [comment]
Ubuntu 18.04! Do you mean running ./restore.sh Install?

**Comment by LukeZGD** [comment]
Oh I forgot about 18.04 support, should be fixed on the latest commit 56fb0dd

**Comment by leftkal** [comment]
Hey thanks for the quick response. I deleted the old folder, downloaded the new one. I ran the script, it downloaded things for a while but ended up in pretty much the same log as above:

[Log] Proceeding to idevicerestore...
resources/tools/idevicerestore_linux: error while loading shared libraries: libimobiledevice-1.0.so.6: cannot open shared object file: No such file or directory
[Log] Restoring done!
[Log] Downgrade script done!

Any other ideas on what could be wrong?

**Comment by LukeZGD** [comment]
Please try again with 810ebb2, should actually be fixed this time

**Comment by LukeZGD** [comment]
Please try again with 810ebb2, should actually be fixed this time

**Comment by leftkal** [comment]
Thanks worked like a charm :)
