### ISSUE TITLE
missing icons

### ISSUE THREAD

**Issue by z33154** [LukeZGD/iOS-OTA-Downgrader#61]
I am missing all jailbreak icons/apps, and can do nothing to get them to show... I have done my best to Google a solution an have found none. 

I have tried restarting the iPad with the volume up button depressed, I have reinstalled patych, I have downgraded patych. Even in no substrate mode cydia/installed ipas (filza, mterminal) will not show on the home screen. 

I am using an iPad gen4 on 8.4.1.Thank you.

**Comment by LukeZGD** [comment]
You may try these steps: https://www.reddit.com/r/jailbreak/comments/3c080x/tutorial_fix_for_missing_jailbroken_app_icons/

If this works for you I may implement this as a fix

**Comment by LukeZGD** [comment]
I have now implemented a fix to be installed as a tweak from [my Cydia repo](https://lukezgd.github.io/repo/)
