### ISSUE TITLE
[Bug] idevicerestore Failed

### ISSUE THREAD

**Issue by mariobrostech** [LukeZGD/iOS-OTA-Downgrader#62]
[Log] Extracting IPSW... 

[Log] Proceeding to idevicerestore... 
./restore.sh: line 383:  5850 Killed: 9               $idevicerestore -y -e -w $IPSW.ipsw

[Log] Restoring done! 
[Log] Downgrade script done!

**Comment by LukeZGD** [comment]
I assume this is macOS 10.15
Try this: In Terminal, cd to where the script is and run `sudo codesign --sign - --force --deep resources/tools/idevicerestore_macos`

**Comment by mariobrostech** [comment]
@LukeZGD This is actually on macOS 10.14.6. Do those instructions still apply in my case?

**Comment by LukeZGD** [comment]
> @LukeZGD This is actually on macOS 10.14.6. Do those instructions still apply in my case?

Yes

If the command worked I will be updating the script

**Comment by mariobrostech** [comment]
That seems to have worked, thank you!

**Comment by LukeZGD** [comment]
I have now applied the changes in the install script

**Comment by mariobrostech** [comment]
Great! Thanks for your help 👍
