### ISSUE TITLE
iOS 8.4.1: Cydia not available on the homescreen

### ISSUE THREAD

**Issue by mariobrostech** [LukeZGD/iOS-OTA-Downgrader#63]
Hi there,

I know that this is a known issue, but I can't see the Cydia icon on my homescreen after downgrading. `cydia://` in Safari works, but even after running it once, there's still no Cydia icon on the homescreen. Is there any way to fix this?

Thanks!

**Comment by LukeZGD** [comment]
You can try the fix that I mentioned in the currently open issue, though I haven't tried this myself yet:

> You may try these steps: https://www.reddit.com/r/jailbreak/comments/3c080x/tutorial_fix_for_missing_jailbroken_app_icons/
> If this works for you I may implement this as a fix

**Comment by mariobrostech** [comment]
That worked! However, the device does require a full reboot, not just a `killall springboard`, for the changes to take effect. Now, I have Cydia on my homescreen! Is there any way you can implement this as a fix?

Thanks again for all your help!

**Comment by LukeZGD** [comment]
Thanks for letting me know, I'll see what I can do to implement this as a fix

**Comment by LukeZGD** [comment]
I have now implemented a fix to be installed as a tweak from [my Cydia repo](https://lukezgd.github.io/repo/)

**Comment by mariobrostech** [comment]
@LukeZGD Is there any way that this can be integrated directly into the utility or have the tweak auto-installed? I have to restore my device to 8.4.1 on a regular basis, so having it fixed automatically would be quite the timesaver for me.

Thanks again!
