### ISSUE TITLE
Jailbreak option not working (says jailbroken in 3utools but no cydia or JB app)

### ISSUE THREAD

**Issue by C-r-e-a-l** [LukeZGD/iOS-OTA-Downgrader#66]
Tried 2 iPads, downgraded both to 6.1.3 and 8.4.1 and says jailbroken on mac and windows but no cydia or jailbreak app. please advise.

**Comment by LukeZGD** [comment]
Please see the readme

- If you can't find Cydia in your home screen, try accessing Cydia through Safari with cydia:// and install "Jailbreak App Icons Fix" package ([Cydia repo](https://lukezgd.github.io/repo))

**Comment by C-r-e-a-l** [comment]
> Please see the readme
> 
> * If you can't find Cydia in your home screen, try accessing Cydia through Safari with cydia:// and install "Jailbreak App Icons Fix" package ([Cydia repo](https://lukezgd.github.io/repo))

Got a blank source in iOS 6.1.3 and 8.4.1 crashes, already tried

**Comment by LukeZGD** [comment]
> Got a blank source in iOS 6.1.3 and 8.4.1 crashes, already tried

What model is the 8.4.1 iPad?

Also for the 6.1.3 iPad do you mean that the default repos are missing?

**Comment by C-r-e-a-l** [comment]
> > Got a blank source in iOS 6.1.3 and 8.4.1 crashes, already tried
> 
> What model is the 8.4.1 iPad?
> 
> Also for the 6.1.3 iPad do you mean that the default repos are missing?

Ran update in iOS 6.1.3 for Cydia and works! Thanks so much man I had to update Cydia, install your tweak. The iOS 8.4.1 iPad is an iPad 3 WiFi White. Date is 2012. I am flashing it with 3utools back to 9.3.5 (Parallels) and gonna downgrade it back to your tool, ticking the n on jailbreak, and try a jailbreak thru 3utools.

**Comment by LukeZGD** [comment]
> Ran update in iOS 6.1.3 for Cydia and works! Thanks so much man I had to update Cydia, install your tweak. The iOS 8.4.1 iPad is an iPad 3 WiFi White. Date is 2012. Upgraded to 9.3.5 to downgrade again, should I try a jailbreak thru 3utools after the downgrade?

For the iPad 3, I personally experienced issues when testing EtasonJB on my iPad 3 Cellular.. You can still try it though

**Comment by C-r-e-a-l** [comment]
It worked! Avoiding the jailbreak in the script and then jailbreaking in a VM using 3utools worked!
