### ISSUE TITLE
Script keeps re-installing dependencies (Manjaro Linux)

### ISSUE THREAD

**Issue by showman15** [LukeZGD/iOS-OTA-Downgrader#68]
When trying to run restore.sh I keep getting this
./autogen.sh: line 14: aclocal: command not found
./autogen.sh: line 15: autoheader: command not found
./autogen.sh: line 16: automake: command not found
./autogen.sh: line 17: autoconf: command not found
./autogen.sh: line 21: ./configure: No such file or directory
./restore.sh: line 656: make: command not found
It happens everytime I type ./restore.sh because it keeps reinstalling the dependencies.
![error](https://user-images.githubusercontent.com/73672095/97638616-d6d77c80-1a34-11eb-8c0b-3c15d73b7fe7.png)

**Comment by LukeZGD** [comment]
pacman -S base-devel

**Comment by LukeZGD** [comment]
Should be fixed with latest commit f93bc38
