### ISSUE TITLE
Can't downgrade to iOS 6.1.3 without jailbreak option

### ISSUE THREAD

**Issue by zx331645** [LukeZGD/iOS-OTA-Downgrader#75]
When I try to downgrade my iPad2,2 with the jailbreak option disabled, it errors with cant upgrade baseband. This is a big problem with me because with the jailbreak option enabled Cydia doesn't install and I need Cydia.

**Comment by LukeZGD** [comment]
Please give terminal output

Also are you sure that Cydia is really not installed when selecting the jailbreak option? Have you tried accessing Cydia through Safari with `cydia://`?

**Comment by zx331645** [comment]
I haven't tried using web cydia i'll try that

**Comment by zx331645** [comment]
YES!! I GOT CYDIA!!

**Comment by LukeZGD** [comment]
Oh, the jailbreak is actually working.. If you can't find Cydia in your home screen, install "Jailbreak App Icons Fix" package ([Cydia repo](https://lukezgd.github.io/repo/))
