### ISSUE TITLE
Add new option restore cfw ch3rryfower. 

### ISSUE THREAD

**Issue by hoanmaster321** [LukeZGD/iOS-OTA-Downgrader#76]
Thanks you very much , tool it is good, but i want restore cfw shsh 7.x.x.

**Comment by LukeZGD** [comment]
iOS-OTA-Downgrader won't have the option for ch3rryflower, there are other tools for that

1. [cherryflowerJB](https://dora2ios.web.app/CFJB/) (updated for macOS)
2. [iPhone4Down](https://github.com/LukeZGD/iPhone4Down) (for Linux, supports iPhone 4 only so it might not be the choice for you)
3. [my fork of ch3rryflower](https://github.com/LukeZGD/ch3rryflower) (contains updated binaries of idevicerestore and idevicererestore for Linux, untested)
