### ISSUE TITLE
5s ota 10.3.3 linux 20.04 error

### ISSUE THREAD

**Issue by hoanmaster321** [LukeZGD/iOS-OTA-Downgrader#77]
[Log] Downgrading device iPhone6,1 in pwnDFU mode... 
[Log] Option: Downgrade 
[Log] Extracting IPSW... 
[Log] Entering pwnREC mode... 
[=========================================         ] 80.9%
[Log] Failed to detect device in pwnREC mode.

**Comment by LukeZGD** [comment]
Unfortunately getting stuck at "Entering pwnREC mode" happens sometimes... (as seen at #41) You just have to hard-reset and try again more

I experienced that as well where irecovery just freezes in entering PWNREC, I had to hard-reset and start over for it to work
