### ISSUE TITLE
Support for other Linux Distributions?

### ISSUE THREAD

**Issue by payload17** [LukeZGD/iOS-OTA-Downgrader#79]
Is it possible to get this running on Debian, and other Linux distros?

**Comment by LukeZGD** [comment]
Yes, as long as all needed dependencies are installed, and/or the needed libraries are symlinked to `resources/lib`. See the `Install` function in `restore.sh` for more details, as well as the command `ldd resources/tools/*linux`

I may add Debian Buster/Bullseye support for the install script sometime later

**Comment by LukeZGD** [comment]
Debian Buster/Bullseye/Sid support now added
