### ISSUE TITLE
Error saving blobs for 6.1.3 failed

### ISSUE THREAD

**Issue by Grandboy46** [LukeZGD/iOS-OTA-Downgrader#81]
./restore.sh

******* iOS-OTA-Downgrader ******* 
   Downgrader script by LukeZGD    

[Log] Finding device in normal mode... 
[Log] Finding device in DFU/recovery mode... 
[Input] Enter ProductType (eg. iPad2,1): iPad2,3
* Platform: macos 11.1 
* HardwareModel: k95ap 
* ProductType: iPad2,3 
* ProductVersion: Unknown 
* UniqueChipID (ECID): 944507563468 

[Log] 32-bit device in DFU mode detected. 
* Advanced options menu - use at your own risk 
* Warning: A6 devices won't have activation error workaround yet when using this method 
[Input] This device is in: 
1) kDFU mode		     3) pwnDFU mode (checkm8 A5)
2) DFU mode (ipwndfu A6)     4) (Any other key to exit)
#? 1
[Log] Downgrading iPad2,3 in kDFU/pwnDFU mode... 
[Input] Select iOS version: 
1) iOS 8.4.1		    3) Other
2) iOS 6.1.3		    4) (Any other key to exit)
#? 2
[Log] Option: Downgrade 
[Input] Jailbreak the selected iOS version? (y/N):  y
[Log] Saving 6.1.3 blobs with tsschecker... 
Version: b9d193aa6e6d24421094873c830692d02d8b32f5 - 304
libfragmentzip version: 0.59-542a470d7be248681dba71d0f04e7dc8c2718b73
[TSSC] manually specified ECID to use, parsed "944507563468" to dec:944507563468 hex:dbe909adcc
[TSSC] opening resources/manifests/BuildManifest_iPad2,3_6.1.3.plist
[WARNING] [TSSC] could not get id0 for installType=Erase. Using fallback installType=Update since user did not specify installType manually
[TSSR] Request URL set to https://gs.apple.com/TSS/controller?action=2
[TSSR] Sending TSS request attempt 1... failure
[Error] ERROR: TSS request failed (status=94, message=This device isn't eligible for the requested build.)

iOS 6.1.3 for device iPad2,3 IS NOT being signed!
ls: 944507563468_iPad2,3_6.1.3-10B329_*.shsh2: No such file or directory

[Error] Saving 6.1.3 blobs failed. Please run the script again 
* It is also possible that 6.1.3 for iPad2,3 is no longer signed

**Comment by LukeZGD** [comment]
This has actually happened before (on iPad2,2's I believe, see #12 #25), it's just Apple's signing servers acting up I guess

Try again after a while or wait a few days

**Comment by Grandboy46** [comment]
it also happens on 8.4.1 and iPad2,2 working fine

**Comment by Grandboy46** [comment]
The weird part is other methods like modifying systemversion.plist works fine

**Comment by Grandboy46** [comment]
one more thing, tsschecker showed 9.3.5 is also not signed for iPad2,3 when it actually is!

**Comment by LukeZGD** [comment]
Nothing I can do about it, it's up to Apple's TSS, maybe you can try again after some time

**Comment by LukeZGD** [comment]
Happens on my end as well btw

![Screenshot_20210220_182152](https://user-images.githubusercontent.com/26163116/108592398-af703b00-73a8-11eb-85d4-17a9b7302cd7.png)

**Comment by Grandboy46** [comment]
ok I will close now

**Comment by Grandboy46** [comment]
Hey @LukeZGD, I have deeply investigated this and the results show that this is a bug with the latest version of tsschecker. It even says 9.3.6 is unsigned when it is signed. Older version of Tsschecker ([v212](https://github.com/tihmstar/tsschecker/releases/tag/v212)) works fine and tells it is signed.

**Comment by Grandboy46** [comment]
<img width="572" alt="Screen Shot 2021-07-11 at 22 48 15" src="https://user-images.githubusercontent.com/77637465/125208307-424b3c80-e29a-11eb-86a5-c8eda4b4e964.png">

**Comment by LukeZGD** [comment]
Thanks for letting me know, I will be adding tsschecker 212 as fallback to fix this

**Comment by LukeZGD** [comment]
Please try again with the latest commit d3d27a0, it should fix this issue now

**Comment by Grandboy46** [comment]
I tested, Cydia not showing when downgrading with jailbreak.

**Comment by LukeZGD** [comment]
> I tested, Cydia not showing when downgrading with jailbreak.

That seems to happen on the iPads, you can access Cydia through Safari with cydia:// and install "Jailbreak App Icons Fix" package from my Cydia repo

**Comment by LukeZGD** [comment]
Since the main issue of being unable to save blobs is now fixed, I will now be closing this
