### ISSUE TITLE
Error code -3 while trying to downgrade my ipad2

### ISSUE THREAD

**Issue by iAlcatrazZ** [LukeZGD/iOS-OTA-Downgrader#83]
Greeting Luke,
I this error message below while trying to downgrade my ipad2 from 9.3.5 to 6.1.3 for a second time.

[WARNING] failed to read BasebandGoldCertID from device! Is it already in recovery?
[WARNING] using tsschecker's fallback to get BasebandGoldCertID. This might result in invalid baseband signing status information
[TSSC] opening /tmp/futurerestore/basebandManifest.plist
[TSSR] User specified to request only a Baseband ticket.
ERROR: Unable to get BasebandFirmware node
ERROR: Unable to find required BbGoldCertId in parameters
Request URL set to https://gs.apple.com/TSS/controller?action=2
TSS server returned: STATUS=49&MESSAGE=An internal error occurred.
ERROR: TSS request failed (status=49, message=An internal error occurred.)
Sending TSS request attempt 1... [Error] baseband firmware isn't signed
Failed with errorcode=-3

At first my device was on 9.3.5 then I was able to downgrade to 6.1.3 using the script successfully with jailbreak option. But when I enter the home screen, Cydia wasn't installed. I didn't know how to install Cydia with jailbreak enabled ios 6 so I decided to restore back to 9.3.5 with iTunes then jailbreak again with 3uTools and tried downgrading it again with the script but it failed with error message as above. If possible is teach me how to fix it or bypass the baseband checking process all together since I only use the device with wifi, there is absolutely no need to use cellular data. Thank you

**Comment by LukeZGD** [comment]
I'm guessing this is an iPad2,3, 6.1.3 and 8.4.1 OTA are not signed for that device right now.. There's nothing I can do about it

Same issue as #81

**Comment by LukeZGD** [comment]
I can see that you have actually successfully downgraded but did not see Cydia in the home screen, havae you tried opening Cydia in safari using `cydia://` ?

**Comment by davidiesel** [comment]
@LukeZGD i have a 12 pro max on 14.4 can I downgrade to 14.3 or 14.3 rc anyway possible as I missed the window

**Comment by iAlcatrazZ** [comment]
both 6.1.3 are still signed by apple. while downgrading for the first time I did observer the process, the console return 6.1.3 as signed. the second time I downgrade it, it failed because of the baseband firmware, I believe baseband firmware is not included in the ios ipsw package

**Comment by LukeZGD** [comment]
Pleasegive full terminal output

**Comment by iAlcatrazZ** [comment]
> I can see that you have actually successfully downgraded but did not see Cydia in the home screen, have you tried opening Cydia in Safari using `cydia://` ? Because Cydia may have been installed but it is just not visible in the home screen.
> 
> In any case, if it is 6.1.3/8.4.1 is not signed anymore, there's nothing I can do about it, only Apple controls the signing

**Comment by iAlcatrazZ** [comment]
> Please give full terminal output

******* iOS-OTA-Downgrader ******* 
   Downgrader script by LukeZGD    

[Log] Finding device in normal mode... 
* Platform: linux  
* HardwareModel: k94ap 
* ProductType: iPad2,2 
* ProductVersion: 9.3.5 
* UniqueChipID (ECID): 993899646252 

*** Main Menu *** 
[Input] Select an option: 
1) Downgrade device
2) Save OTA blobs
3) Just put device in kDFU mode
4) (Re-)Install Dependencies
5) (Any other key to exit)
#? 1
[Input] Select iOS version: 
1) iOS 8.4.1
2) iOS 6.1.3
3) Other (use SHSH blobs)
4) (Any other key to exit)
#? 2
[Log] Option: Downgrade 
[Input] Jailbreak the selected iOS version? (y/N):  n
[Log] Saving 6.1.3 blobs with tsschecker... 
Version: 7895a76c8ac57e45b87bb756e6d8a617740aab62 - 317
libfragmentzip version: 0.60-120447d0f410dffb49948fa155467fc5d91ca3c8
[TSSC] manually specified ECID to use, parsed "993899646252" to dec:993899646252 hex:e769090d2c
[TSSC] opening resources/manifests/BuildManifest_iPad2,2_6.1.3.plist
[TSSR] Checking BuildIdentity 0
[WARNING] [TSSC] could not get BuildIdentity for installType=Erase. Using fallback installType=Update since user did not specify installType manually
[TSSR] Checking BuildIdentity 0
[TSSR] Selected BuildIdentity for request
[TSSR] Request URL set to https://gs.apple.com/TSS/controller?action=2
[TSSR] Sending TSS request attempt 1... success
[TSSR] Checking BuildIdentity 0
[Error] [TSSR] Error: could not get BuildIdentity for installType=Erase
Saved shsh blobs!

iOS 6.1.3 for device iPad2,2 IS being signed!
[Log] Successfully saved 6.1.3 blobs. 
[Log] Verifying IPSW... 
[Log] Patching iBSS... 
[Log] Copying stuff to device via SSH... 
* Make sure OpenSSH/Dropbear is installed on the device! 
* Enter root password of your iOS device when prompted, default is 'alpine' 
Creating listening port 2222 for device port 22
bind(): Address already in use
Error creating socket for listen port 2222: Address already in use
New connection for 2222->22, fd = 5
waiting for connection
Requesting connecion to USB device handle 1 (serial: e4c05b63883d3302ab94e921f9efd7ca4a42e1ab), port 22
The authenticity of host '[127.0.0.1]:2222 ([127.0.0.1]:2222)' can't be established.
RSA key fingerprint is SHA256:st71yZ+YG9uuy3gv0U+J4liOyLo0XKAsNgZtrnAqOHw.
Are you sure you want to continue connecting (yes/no/[fingerprint])? yes
Warning: Permanently added '[127.0.0.1]:2222' (RSA) to the list of known hosts.
root@127.0.0.1's password: 
kloader                                                                                                                               100%   51KB   3.4MB/s   00:00    
pwnediBSS                                                                                                                             100%   76KB   1.3MB/s   00:00    
[Log] Entering kDFU mode... 

* Press POWER or HOME button when screen goes black on the device 
[Log] Finding device in DFU mode... 
New connection for 2222->22, fd = 5
waiting for connection
Requesting connecion to USB device handle 1 (serial: e4c05b63883d3302ab94e921f9efd7ca4a42e1ab), port 22
root@127.0.0.1's password: 
Connection to 127.0.0.1 closed by remote host.
[Log] Found device in DFU mode. 
/home/ubuntu/Downloads/iOS-OTA-Downgrader-master/restore.sh: line 321: kill: (3155) - No such process
[Log] Extracting IPSW... 
[Log] Preparing for futurerestore... (Enter root password of your PC/Mac when prompted) 
[Log] Downloading baseband... 
Initializing download for Firmware/ICE3_04.12.09_BOOT_02.13.Release.bbfw...
Downloading: 100%
Initializing download for BuildManifest.plist...
Downloading: 100%
[Log] Proceeding to futurerestore... 
Version: b99eb8140d8e6c23f34e950102bb79e61c72384d - 152
Libipatcher Version: f32e41d850f51448bd6c588ead9c7d6455733f3c - 44
Odysseus Support: yes
[INFO] 32bit device detected
futurerestore init done
reading ticket 993899646252_iPad2,2_6.1.3-10B329_5f067585760907dee7ca0cbd12557b53f9ae9c5a.shsh2 done
Did set sep+baseband path and firmware
[WARNING] failed to read BasebandGoldCertID from device! Is it already in recovery?
[WARNING] using tsschecker's fallback to get BasebandGoldCertID. This might result in invalid baseband signing status information
[TSSC] opening BuildManifest.plist
[TSSR] User specified to request only a Baseband ticket.
ERROR: Unable to get BasebandFirmware node
ERROR: Unable to find required BbGoldCertId in parameters
Request URL set to https://gs.apple.com/TSS/controller?action=2
TSS server returned: STATUS=49&MESSAGE=An internal error occurred.
ERROR: TSS request failed (status=49, message=An internal error occurred.)
Sending TSS request attempt 1... [Error] baseband firmware isn't signed
Failed with errorcode=-3

[Log] Restoring done! 
[Log] Stopping local server... (Enter root password of your PC/Mac when prompted) 
[Log] Downgrade script done! 

> Hi, I'm sorry for the late reply, above is the full terminal output

**Comment by LukeZGD** [comment]
Hmm doesn't look like anything wrong except for futurerestore itself... Does selecting Y in the jailbreak option work fine, though?

**Comment by LukeZGD** [comment]
"An internal error occurred." indicates that it's something wrong on Apple's end, so it's out of my control.. So your only choice might be to try again with the jailbreak option

**Comment by iAlcatrazZ** [comment]
> Hmm doesn't look like anything wrong except for futurerestore itself... Does selecting Y in the jailbreak option work fine, though?


> "An internal error occurred." indicates that it's something wrong on Apple's end, so it's out of my control.. So your only choice might be to try again with the jailbreak option

I had tried restoring to 9.3.5 with itunes and rejailbreak with 3uTools, but still fail. But anyway I was able to restore with 3uTools using a firm downloaded from their page
