### ISSUE TITLE
Support for apple m1

### ISSUE THREAD

**Issue by Yaya48** [LukeZGD/iOS-OTA-Downgrader#87]
Hey do you have any plan of supporting apple m1 computer?

**Comment by LukeZGD** [comment]
No plans of M1 support anytime soon, sorry

I don't have plans on getting any M1 Mac either, I only have Hackintosh and VMs (which I might be able to use to cross-compile sometime but I don't know how yet)

**Comment by Yaya48** [comment]
Ok ty, I already tried by using procursus stuff, but look like it doesn't send the patched IBSS correctly, I'm gonna investigate that.

**Comment by Yaya48** [comment]
Update I got it to work.

**Comment by LukeZGD** [comment]
Please share some details on your steps of making things work for you on the M1, I think it would be useful info

**Comment by Yaya48** [comment]
First thing I done was to point libimobiledevice suite to procursus one, secondly was to make irecovery send a dummy txt file with random things before the patched ibss and thirdly was to make the custom ipsw to delete after use to make it repatching things when I re use it gonna upload my fork to my gh repo after I make sure it work well.

**Comment by Yaya48** [comment]
https://github.com/Yaya48/iOS-OTA-Downgrader i forked even thought everything is hardcoded for procursus stuff so tats why I included ipwndfu in because libusbfinder automatically redirect to procursus one.

**Comment by LukeZGD** [comment]
#91
