### ISSUE TITLE
Support for Daibutsu Untether by Dora2ios

### ISSUE THREAD

**Issue by Grandboy46** [LukeZGD/iOS-OTA-Downgrader#93]
@LukeZGD, As you know iOS 8.4.1 got a new untether for 32 but devices. Can you please test it especially for a5 rev and a5x devices which has problems with etason untether and if it’s better than etason untether, can you please use daibutsu untether on ipsw files and on the script instead of etason untether especially on a5 rev and a5x devices which have problems with etason untether. Link for the untether is in below:

https://github.com/dora2-iOS/daibutsu/tree/main/untether

**Comment by LukeZGD** [comment]
Yeah that's the plan, to finally fix issues caused by EtasonJB untether.. I'll try testing it then switching to it later on if I can

**Comment by mariobrostech** [comment]
Is there any way you could enable GitHub Projects so the community can see your progress on this as new developments occur?

**Comment by LukeZGD** [comment]
> Is there any way you could enable GitHub Projects so the community can see your progress on this as new developments occur?

There's no progress/new developments, right now daibutsu supports too few devices for me to add support for it

**Comment by UInt2048** [comment]
That's a shame; it would probably help those devices that EtasonJB has problems with. 😞

**Comment by dora2-iOS** [comment]
Hi, What devices should support it? Specifically, it is a device that has a problem with the existing untether. I could add dyld_haxx offsets for those devices.

**Comment by LukeZGD** [comment]
> Hi, What devices should support it? Specifically, it is a device that has a problem with the existing untether. I could add dyld_haxx offsets for those devices.

I have seen the etasonJB untether not working and/or bootlooping mostly on iPad mini 1 and iPad 3rd gen devices, I think the iPad 2 Rev A also has these issues, but I have not seen much reports for it. Let me know if I can be of any help..

**Comment by dora2-iOS** [comment]
OK. It looks like an A5 with something other than 8940. 
I have iPad2,4, so it could be supported soon. But iPad 3rd/mini have to be acquired offsets for the cellular and Wi-Fi versions respectively, so it can be a bit time. Well, that's just a matter of downloading the firmware and getting the cache, so it won't have much a problem.

**Comment by UInt2048** [comment]
@dora2-iOS どうもありがとうございます。古い電子機器を助けるは難しいです。

**Comment by dora2-iOS** [comment]
daibutsu now supports all 8942 & 8945 devices in v1.0b3.  Anyone try it on iPad 3rd or iPad mini?
https://twitter.com/sakurdev/status/1411793304769818624?s=21

**Comment by Grandboy46** [comment]
I will try on my iPad 3rd generation

**Comment by Grandboy46** [comment]
Daibutsu untether works fine on iPad 3. @LukeZGD can you also do the final testing on your iPad 3 before adding it on iOS-OTA-Downgrader?

**Comment by LukeZGD** [comment]
> daibutsu now supports all 8942 & 8945 devices in v1.0b3. Anyone try it on iPad 3rd or iPad mini?
> https://twitter.com/sakurdev/status/1411793304769818624?s=21

Thank you very much for the update! I will be trying it soon

> Daibutsu untether works fine on iPad 3. @LukeZGD can you also do the final testing on your iPad 3 before adding it on iOS-OTA-Downgrader?

I'm sure that it will take a while to add, so I'll see what I can do when I get some time to work on it

**Comment by dora2-iOS** [comment]
applying this using CFW-based restore requires a bit of ingenuity.  In addition to installing the untether package, we need to move most LaunchDaemons to /Library and apply changes to dyld_shared_cache. I think it needs to do that when creating the CFW, or replace restored_external or /sbin/reboot and do it.

**Comment by piaomiaoguhong10** [comment]
Thanks for your efforts. I tried Daibutsu on my iPad mini. But the apps disappeared after jb, left the home screen to be blank.

**Comment by Grandboy46** [comment]
> Thanks for your efforts. I tried Daibutsu on my iPad mini. But the apps disappeared after jb, left the home screen to be blank.

I had the same issue as well, but it turns out it's a general issue with 8.4.1. I also had the same issue with EtasonJB as well.

**Comment by LukeZGD** [comment]
Here's what I attempted to do (in the [`daibutsu`](https://github.com/LukeZGD/iOS-OTA-Downgrader/tree/daibutsu) branch): the script extracts the already patched dyld_shared_cache from the device (that must be already jailbroken with daibutsu), and I [modified xpwn ipsw patch](https://github.com/LukeeGD/xpwn/tree/daibutsu) to do the file moving, as well as deleting the existing dyld_shared_cache then replacing it with the patched one. Well, this approach did not work haha

I guess dyld_shared_cache really must be patched in the restore process, so that means modifying the restore ramdisk by moving /sbin/reboot and replacing it with the dyld patcher (I can do this by modifying ipsw patch, but what I don't know is how to update/compile/use the dyld patcher)

**Comment by dora2-iOS** [comment]
I think it's a good idea to move the daemons and such when creating the CFW. The dyld patch is a good way to remount the rootfs and patch it after the restore. (That is, it hijack /sbin/reboot.) So I have created [a sample project](https://github.com/dora2-iOS/daibutsuCFW) using some of the code used in daibutsu ipa. I have tested it on iPhone5,2 only. This may be useful for someone else?

**Comment by LukeZGD** [comment]
> I think it's a good idea to move the daemons and such when creating the CFW. The dyld patch is a good way to remount the rootfs and patch it after the restore. (That is, it hijack /sbin/reboot.) So I have created [a sample project](https://github.com/dora2-iOS/daibutsuCFW) using some of the code used in daibutsu ipa. I have tested it on iPhone5,2 only. This may be useful for someone else?

Thank you very much for this! I was able to successfully create and restore a custom IPSW with daibutsu! I think I can now add this to iOS-OTA-Downgrader soon. Would it be ok for me to add the compiled binaries to the repo?

**Comment by Grandboy46** [comment]
Thanks, what devices do you plan to use daibutsu untether on?

**Comment by dora2-iOS** [comment]
@LukeZGD  Of course, it can be distributed under gplv3 (under the license of xpwn). I also added some missing source code.

**Comment by LukeZGD** [comment]
> @LukeZGD Of course, it can be distributed under gplv3 (under the license of xpwn). I also added some missing source code.

Thanks for clarifying!

> Thanks, what devices do you plan to use daibutsu untether on? I would recommend using it on all A5 devices except iPad2,1, iPad2,2 and iPad2,3. Etason is more stable on A6 devices while daibutsu is more stable on A5 devices.

daibutsu will be used on all A5 Rev A and A5X devices

**Comment by Grandboy46** [comment]
> > @LukeZGD Of course, it can be distributed under gplv3 (under the license of xpwn). I also added some missing source code.
> 
> Thanks for clarifying!
> 
> > Thanks, what devices do you plan to use daibutsu untether on? I would recommend using it on all A5 devices except iPad2,1, iPad2,2 and iPad2,3. Etason is more stable on A6 devices while daibutsu is more stable on A5 devices.
> 
> daibutsu will be used on all A5 Rev A and A5X devices

You can also use it on 4s if you want

**Comment by LukeZGD** [comment]
iOS-OTA-Downgrader with daibutsu CFW can now be tested in the [`daibutsu`](https://github.com/LukeZGD/iOS-OTA-Downgrader/tree/daibutsu) branch ([download](https://github.com/LukeZGD/iOS-OTA-Downgrader/archive/refs/heads/daibutsu.zip))

I have only tested it on my iPad3,3 and so far it works nicely

**Comment by Grandboy46** [comment]
I can't test now because of #128
