### ISSUE TITLE
iPad2,5 will jailbreak but no Cydia

### ISSUE THREAD

**Issue by shadoez** [LukeZGD/iOS-OTA-Downgrader#94]
I said yes to the jailbreak prompt but when my device booted up there was no Cydia. I checked with 3uTools & it said I was jailbroken though 🤔.

**Comment by LukeZGD** [comment]
This is already addressed in the readme:

> If you cannot find Cydia in your home screen, try accessing Cydia through Safari with `cydia://` and install "Jailbreak App Icons Fix" package from my Cydia repo

Also,

> The jailbreak option might not work on A5 Rev A devices (see issue #70)
